### ISSUE TITLE
Implement action to run instrumentation unit tests

### ISSUE THREAD

**Issue by jeffalder** [newrelic/newrelic-java-agent#10]
An action should run on pull requests that runs the instrumentation unit tests via `./gradlew instrumentation:test`. 

Use [caching](https://docs.github.com/en/actions/configuring-and-managing-workflows/caching-dependencies-to-speed-up-workflows).

The hardest part will be the Rabbit tests which currently require compatibility with hans/frau. If you pick up this ticket you either have to figure out how to install erlang to match hans/frau or we have to take the hit and break compatibility with hans/frau.

**Comment by kford-newrelic** [comment]
Currently being worked as part of the migration to GHA

**Comment by twcrone** [comment]
We have a vast majority of the instrumentation unit tests running in our new GHA environment and intend to see if using Gradle Enterprise will help us fix some of our more flaky tests.
