### ISSUE TITLE
Lettuce Cluster Instrumentation missing command

### ISSUE THREAD

**Issue by kandogu** [newrelic/newrelic-java-agent#1019]
New relic shows singleton redis commands clearly in transaction and databases section, but couldn't see cluster commands in the sections.

## Feature Description
So is it possible to add lettuce cluster instrumentation feature to new relic java agent? So that transaction details of redis commands can be seen on the new relic. 
## Priority
Priority is 'Must Have'

Thank you

**Comment by kford-newrelic** [comment]
@kandogu thanks for the suggested feature - we'll review this request as part of our regular product planning cycles
