### ISSUE TITLE
Issue with grpc 1.4.x agent not properly generating and propagating trace information

### ISSUE THREAD

**Issue by mbazos** [newrelic/newrelic-java-agent#1023]
When upgrading gRPC from 1.3.x to 1.4.x the handling of trace identifiers no longer works. Meaning the trace information is always empty for gRPC 1.4.x but works fine for 1.3.x

Regardless of  the version of grpc the tracing should work

## Steps to Reproduce
Attached is a spring-boot application that has a grpc server and client. You can run the server setting the appropriate new relic agent settings and then run `com.priceline.grpc.demo.demo.ClientGrpcRunner` and you will see output similar to:
```
Hello Mike Bazos your trace id is[]
```

## Your Environment
Azul Java 17 (Please see the attached logs which include the same program running with grpc 1.3.x and 1.4.x)
[grpc_1_4_logs.txt](https://github.com/newrelic/newrelic-java-agent/files/9668510/grpc_1_4_logs.txt)
[grpc_1_3_logs.txt](https://github.com/newrelic/newrelic-java-agent/files/9668511/grpc_1_3_logs.txt)
[grpc_new_relic_issue.zip](https://github.com/newrelic/newrelic-java-agent/files/9668512/grpc_new_relic_issue.zip)

**Comment by kford-newrelic** [comment]
@mbazos Thank you for the detailed info (and repro) on this issue. Do you currently have a workaround to this issue that you're using?

**Comment by atyulmankov** [comment]
> @mbazos Thank you for the detailed info (and repro) on this issue. Do you currently have a workaround to this issue that you're using?

@kford-newrelic I am not aware of any workarounds, and I am waiting for resolution on this as well.

**Comment by mbazos** [comment]
Yeah @kford-newrelic I am not aware of any workarounds, I didn't have time to dig deeper into the new relic agent code to see exactly what the problem is.

**Comment by kford-newrelic** [comment]
Understood, thank you for the feedback. We don't have the capacity to take this up in the current Oct-Dec quarter but we'll consider this for our next quarter's planning.

**Comment by mbazos** [comment]
You can get this from the logs but just wanted to let people know the version of grpc that the issue is caused by based on my logs is grpc 1.44.1. I see there is instrumentation for 1.4.0 & 1.40.0 
https://github.com/newrelic/newrelic-java-agent/tree/main/instrumentation/grpc-1.4.0

**Comment by kford-newrelic** [comment]
@mbazos Great analysis - thank you!

Discussing with the team to see if we can build on your findings
