### ISSUE TITLE
IntelliJ Build Instructions Seem Incomplete

### ISSUE THREAD

**Issue by kittylyst** [newrelic/newrelic-java-agent#1025]
## Description

Following the IntelliJ setup instructions, the build fails on a complex Gradle / Groovy error report, and the project is left in a half-configured state with e.g. source directories not correctly recognized.

## Expected Behavior

The build to complete correctly.

## Steps to Reproduce

Attempt to follow the build steps as given on a clean install of IntelliJ

## Your Environment

Mac OS Monterey, Intel, JDK 8 & 17

**Comment by jasonjkeller** [comment]
@kittylyst Nice to hear from you! 

Can you clarify what exactly the failure is that you're seeing? We all recently set up new dev machines and haven't encountered any issues getting the agent project set up in Intellij.
