### ISSUE TITLE
Newrelic Agent licensing related query

### ISSUE THREAD

**Issue by rajivml** [newrelic/newrelic-java-agent#103]
HI Newrelic Team,

If we are shipping newrelic java agent as part of our docker image with our customers but if they are actually not using it since they don't have an newrelic license procured, in that case is it fine to ship the newrelic java agent library along with our docker image ?

right now we are using the same base docker image both for both our SaaS and PaaS solution and for SaaS we have newrelic license procured but for PaaS we are shipping the newrelic agent along with the docker image but it won't be used by the customer as he doesn't have a license procured and so there won't be any sink to dump this data.. 

So, do you think we have to build an separate image for PaaS so that we are not distributing newrelic agent zip file that has been downloaded onto the docker image ?

Thanks

**Comment by tspring** [comment]
Hi @rajivml 
Starting with version 6.0.0, the New Relic Java agent is licensed under Apache-2.0. This license allows for both modification and distribution provided you adhere to the following re: attribution https://github.com/newrelic/newrelic-java-agent/blob/main/LICENSE#L94-L128 . Let us know if you have any other questions.

**Comment by rajivml** [comment]
thanks @tspring this is how we download the binary and use , we don't modify the source anywhere and I hope it's fine based on your reply 

```
RUN cd /app; curl -L -O https://download.newrelic.com/newrelic/java-agent/newrelic-agent/6.1.0/newrelic-java.zip; unzip newrelic-java.zip
java -javaagent:/app/newrelic/newrelic.jar -jar -Dspring.profiles.active=${SPRING_PROFILES_ACTIVE:-dev} -Dnewrelic.environment=$ENV deployer-server.jar
```
```

        <dependency>
           <groupId>com.newrelic.logging</groupId>
           <artifactId>logback</artifactId>
           <version>1.1</version>
        </dependency>
```

**Comment by rajivml** [comment]
Thanks @tspring , it clarifies my question... you can close the ticket
