### ISSUE TITLE
Allow 2 agents running on the same host to be differentiated.

### ISSUE THREAD

**Issue by obenkenobi** [newrelic/newrelic-java-agent#1035]
## Is your feature request related to a problem? Please describe.
Yes. When 2 JVMs are running on the same host, yet are in different IPs and the same port, the 2 agents report themselves as the same.

## Feature Description
To allow the agent to distinguish itself from any other agents running on the same host.

## Describe Alternatives
A workaround to get the 2 agents to be differentiated even if the IPs are different is to configure the agent to say the applications are running on a different port using the configuration `-Dnewrelic.config.appserver_port=8081`. 

https://docs.newrelic.com/docs/apm/agents/java-agent/configuration/java-agent-configuration-config-file/#cfg-appserver_port

This is related to this internal ticket: [NR-53866](https://issues.newrelic.com/browse/NR-53866)

**Comment by kford-newrelic** [comment]
Not chosen for the agent roadmap.
