### ISSUE TITLE
Java agent v7.10.0 not working with resin-pro-4.0.63 and java 17.0.3.1

### ISSUE THREAD

**Issue by kford-newrelic** [newrelic/newrelic-java-agent#1041]
The customer is trying to add java agent newrelic.jar to resin-pro-4.0.63 with java 17. When using java 8 they have added the agent flag to resin.properties -javaagent:/usr/local/share/newrelic/newrelic.jar.

But now they are trying to install with java 17 by adding it to resinctl but that not working. They also have tried adding to the [resin.sh](https://resin.sh/) method as mentioned [here](https://docs.newrelic.com/install/java/?framework=resin&deployment=appServer) but that doesn't work either - they get a startup and shutdown of the agent but reports nothing. The agent gets attached to the startup process, and exits along with it. The agent never gets attached to the actual running resin process. The customer is wondering what is the right way to install the new relic agent into resin with java 17?

(Note : We had tried this internally with Java 17 and were able to start resin, so it's not clear what the difference is between what the customer tried and what we tried. Will need some additional focused attention on this, also to ensure that our instrumentation is working as expected too)

**Comment by meiao** [comment]
Loaded modules in app running on Java 8

```
com.newrelic.instrumentation.jdbc-generic
com.newrelic.instrumentation.jdbc-mysql-3.0.8
com.newrelic.instrumentation.jdbc-mysql-connection-5.1.4
com.newrelic.instrumentation.jdbc-mysql-multihost-connections-5.1.3
com.newrelic.instrumentation.jdbc-socket
com.newrelic.instrumentation.jms-1.1
com.newrelic.instrumentation.jsp-2.4
com.newrelic.instrumentation.mongodb-2.12
com.newrelic.instrumentation.resin-4
com.newrelic.instrumentation.resin-jmx
com.newrelic.instrumentation.servlet-2.4
com.newrelic.instrumentation.spring-4.0.0
com.newrelic.instrumentation.spring-jms-2
com.newrelic.instrumentation.spymemcached-2.12.0 
```

**Comment by kford-newrelic** [comment]
Will not be able to target this for the Oct-Dec quarter; will consider for the agent roadmap in the Jan-Mar quarter.

**Comment by kford-newrelic** [comment]
Not targeted for the Jan-Mar quarter. Will consider for a future quarter.

**Comment by jasonjkeller** [comment]
Documentation has been updated to reflect the proper way to add the Java agent with Java versions 9+: https://docs.newrelic.com/docs/apm/agents/java-agent/additional-installation/include-java-agent-jvm-argument/#Installing_on_Resin
