### ISSUE TITLE
Java Agent creating too many NewRelicMetricsReporter threads when used with Kafka instrumentation

### ISSUE THREAD

**Issue by kford-newrelic** [newrelic/newrelic-java-agent#1056]
Current agent design/implementation causes an unnecessary number of `NewRelicMetricsReporter` thread to be created when the agent is used with Kafka 3.x instrumentation. Refactoring this implementation would be best - perhaps to leverage a singleton instance, etc.

**Comment by kford-newrelic** [comment]
Will consider for the Jan-Mar roadmap

**Comment by kford-newrelic** [comment]
Targeted for the Jan-Mar quarter

**Comment by obenkenobi** [comment]
A solution lives on the branch [NEWRELIC-4832-reduce-thread-count](https://github.com/newrelic/newrelic-java-agent/tree/NEWRELIC-4832-reduce-thread-count). This bug is put on hold for higher priority tasks.
