### ISSUE TITLE
Invalid Class Cast Exception in Graphql Instrumentation

### ISSUE THREAD

**Issue by crsunik** [newrelic/newrelic-java-agent#1064]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
Class Cast Exception is being thrown in New Relic agent:
com.newrelic.agent.instrumentation.ClassTransformerServiceImpl FINER: An error was thrown from instrumentation library com.newrelic.instrumentation.graphql-java-16.2 -- class graphql.schema.GraphQLNonNull cannot be cast to class graphql.schema.GraphQLObjectType (graphql.schema.GraphQLNonNull and graphql.schema.GraphQLObjectType are in unnamed module of loader 'app')

## Expected Behavior
No Exception should be thrown

## [Troubleshooting]
In both graphql instrumentation versions
https://github.com/newrelic/newrelic-java-agent/blob/main/instrumentation/graphql-java-16.2/src/main/java/com/nr/instrumentation/graphql/GraphQLSpanUtil.java#L41
and
https://github.com/newrelic/newrelic-java-agent/blob/main/instrumentation/graphql-java-17.0/src/main/java/com/nr/instrumentation/graphql/GraphQLSpanUtil.java#L41

GraphQLOutputType (actual return type of invocation parameters.getExecutionStepInfo().getType()) is casted to GraphQLObjectType without checking if the returned object is the right implementation of the interface. Based on the exception message it is easy to see that it is not the case. Simple check with instanceof should solve the issue.

**Comment by kford-newrelic** [comment]
@crsunik Thanks for bringing this issue to our attention!

We don't have any agent releases planned for the remainder of 2022 - how are you working around this issue?

**Comment by crsunik** [comment]
I didn't find a working solution for this. Trace is broken into two

**Comment by twcrone** [comment]
@crsunik I just opened a PR for this fix.  Please take a look!  https://github.com/newrelic/newrelic-java-agent/pull/1082
