### ISSUE TITLE
Using @Trace on a method in a utility class in an instrumentation module does not work

### ISSUE THREAD

**Issue by philsttr** [newrelic/newrelic-java-agent#1073]
## Description

According to the [README.md for instrumentation modules](https://github.com/newrelic/newrelic-java-agent/blob/main/instrumentation/README.md#introduction), an instrumentation module consists of _weave_ classes, _utility_ classes, and _SkipIfPresent_ classes.

The `@Trace` annotation is handled properly on methods in _weave_ classes.  Unfortunately, it is not handled properly on methods in _utility_ classes.

For example, [this usage](https://github.com/newrelic/newrelic-java-agent/blob/85e48ab8f4bc76b478006902040395c856c87c4d/instrumentation/netty-reactor-0.9.0/src/main/java/com/nr/instrumentation/reactor/netty/TokenLinkingSubscriber.java#L65) of `@Trace` on a utility class is not handled.  Specifically, the token will not be linked properly [here](https://github.com/newrelic/newrelic-java-agent/blob/85e48ab8f4bc76b478006902040395c856c87c4d/instrumentation/netty-reactor-0.9.0/src/main/java/com/nr/instrumentation/reactor/netty/TokenLinkingSubscriber.java#L68), because the  `@Trace` is not handled properly.

## Expected Behavior
I expect  `@Trace` to work correctly when placed on a method in a utility class in an instrumentation module.

## Steps to Reproduce

The easiest way to see the non-working behavior is to:
1. Turn on logging at the FINEST level
2. Turn on [token debugging](https://github.com/newrelic/newrelic-java-agent/blob/cf3007cf6db521e9543e5745fe6316fd04805814/newrelic-agent/src/main/java/com/newrelic/agent/DebugFlag.java#L13)
3. Run an application that exercises code that uses `@Trace` in a utility class of an instrumentation module.  For example, [here](https://github.com/newrelic/newrelic-java-agent/blob/85e48ab8f4bc76b478006902040395c856c87c4d/instrumentation/netty-reactor-0.9.0/src/main/java/com/nr/instrumentation/reactor/netty/TokenLinkingSubscriber.java#L65-L68)
4. Look in the logs for messages like the following....

```
2022-11-10T18:53:13,317+0100 [7219 78] com.newrelic FINER: Transaction com.newrelic.agent.Transaction@11ee9b3: ignoring link call because there is no started txa to link to: null.

2022-11-10T18:53:13,317+0100 [7219 78] com.newrelic WARN: Token: com.newrelic.agent.TokenImpl@100c4133 was NOT linked because there was no Transaction in progress. Did you forget to add @Trace(async = true) to: com.nr.instrumentation.reactor.netty.TokenLinkingSubscriber.withNRToken(TokenLinkingSubscriber.java:68)?
```

This message indicates that the `@Trace(async = true)` annotation is not on the method in the utility class.  However it actually _IS_ on the method.  This is a symptom of the `@Trace` not being handled properly on the method in the utility class.

## Troubleshooting

I have determined that the problem seems to be related to [where AgentPostprocessors handles utility classes](https://github.com/newrelic/newrelic-java-agent/blob/cf3007cf6db521e9543e5745fe6316fd04805814/newrelic-agent/src/main/java/com/newrelic/agent/instrumentation/weaver/preprocessors/AgentPostprocessors.java#L64-L71).

Specifically [here](https://github.com/newrelic/newrelic-java-agent/blob/cf3007cf6db521e9543e5745fe6316fd04805814/newrelic-agent/src/main/java/com/newrelic/agent/instrumentation/weaver/preprocessors/AgentPostprocessors.java#L65), `tracedWeaveInstrumentationTrackers` is always null, because the post processor's `tracedWeaveInstrumentationDetails` map is always empty.  It appears that the post processor's [`setTracedWeaveInstrumentationDetails`](https://github.com/newrelic/newrelic-java-agent/blob/cf3007cf6db521e9543e5745fe6316fd04805814/newrelic-agent/src/main/java/com/newrelic/agent/instrumentation/weaver/preprocessors/AgentPostprocessors.java#L54) method is never called, therefore the `tracedWeaveInstrumentationDetails` map is always empty.

Because `tracedWeaveInstrumentationTrackers` is always null... when the `TraceClassVisitor` visits the method annotated with `@Trace` in the utility class, the [`TraceDetails` is always null](https://github.com/newrelic/newrelic-java-agent/blob/cf3007cf6db521e9543e5745fe6316fd04805814/newrelic-agent/src/main/java/com/newrelic/agent/instrumentation/tracing/TraceClassVisitor.java#L97-L99).  Therefore the tracer logic is never injected into the utility class bytecode.

To confirm this theory, in a debugger I have explicitly called `AgentPostprocessors.setTracedWeaveInstrumentationDetails` with the return value of `AgentPreprocessor.getTracedWeaveInstrumentationDetails` before the post processor is executed in [`PackageValidationResult.computeUtilityClassBytes`](https://github.com/newrelic/newrelic-java-agent/blob/cf3007cf6db521e9543e5745fe6316fd04805814/newrelic-weaver/src/main/java/com/newrelic/weave/weavepackage/PackageValidationResult.java#L553-L563).  After doing so, the tracer logic is injected properly into the utility class bytecode, and the `@Trace` functionality works properly.

## Your Environment
newrelic-java-agent 7.11.0

**Comment by kford-newrelic** [comment]
Targeted for the Jan-Mar quarter

**Comment by kford-newrelic** [comment]
Moving review of this to the Apr-Jun quarter - no capacity to take this up currently

**Comment by kford-newrelic** [comment]
@jenerallyErrorFree apologies but we haven't had the capacity to take this up. Unfortunately, no ETA at the moment

**Comment by jasonjkeller** [comment]
We tested this and determined that @Trace annotation does work as expected on instrumentation utility classes.

The "non-working" example that was cited was the [TokenLinkingSubscriber](https://github.com/newrelic/newrelic-java-agent/blob/main/instrumentation/netty-reactor-0.9.0/src/main/java/com/nr/instrumentation/reactor/netty/TokenLinkingSubscriber.java) utility class in our own `netty-reactor-0.9.0` instrumentation. If you debug the [TransactionPropagationTest](https://github.com/newrelic/newrelic-java-agent/blob/main/instrumentation/netty-reactor-0.9.0/src/test/java/com/nr/agent/instrumentation/TransactionPropagationTest.java) in that instrumentation package while adding breakpoints in the places that were called out you can see it working correctly.

> when the TraceClassVisitor visits the method annotated with @Trace in the utility class, the [TraceDetails is always null](https://github.com/newrelic/newrelic-java-agent/blob/cf3007cf6db521e9543e5745fe6316fd04805814/newrelic-agent/src/main/java/com/newrelic/agent/instrumentation/tracing/TraceClassVisitor.java#L97-L99). Therefore the tracer logic is never injected into the utility class bytecode.

`TraceDetails` is not null when the `TraceClassVisitor` visits the `withNRToken` method annotated with `@Trace` in the utility class

<img width="1655" alt="TraceDetails" src="https://github.com/newrelic/newrelic-java-agent/assets/3496648/bf2bea56-f292-41d8-8455-89c4a70dc193">

>Specifically [here](https://github.com/newrelic/newrelic-java-agent/blob/cf3007cf6db521e9543e5745fe6316fd04805814/newrelic-agent/src/main/java/com/newrelic/agent/instrumentation/weaver/preprocessors/AgentPostprocessors.java#L65), tracedWeaveInstrumentationTrackers is always null, because the post processor's tracedWeaveInstrumentationDetails map is always empty. It appears that the post processor's [setTracedWeaveInstrumentationDetails](https://github.com/newrelic/newrelic-java-agent/blob/cf3007cf6db521e9543e5745fe6316fd04805814/newrelic-agent/src/main/java/com/newrelic/agent/instrumentation/weaver/preprocessors/AgentPostprocessors.java#L54) method is never called, therefore the tracedWeaveInstrumentationDetails map is always empty.

>Because tracedWeaveInstrumentationTrackers is always null...

`tracedWeaveInstrumentationTrackers` is not null and `tracedWeaveInstrumentationDetails` is not empty

<img width="1658" alt="UtilityClassProcessing" src="https://github.com/newrelic/newrelic-java-agent/assets/3496648/bf0ac6e9-d1e8-47c2-b108-ea3ebdce1d1d">

>For example, [this usage](https://github.com/newrelic/newrelic-java-agent/blob/85e48ab8f4bc76b478006902040395c856c87c4d/instrumentation/netty-reactor-0.9.0/src/main/java/com/nr/instrumentation/reactor/netty/TokenLinkingSubscriber.java#L65) of @Trace on a utility class is not handled. Specifically, the token will not be linked properly [here](https://github.com/newrelic/newrelic-java-agent/blob/85e48ab8f4bc76b478006902040395c856c87c4d/instrumentation/netty-reactor-0.9.0/src/main/java/com/nr/instrumentation/reactor/netty/TokenLinkingSubscriber.java#L68), because the @Trace is not handled properly.

The `token.link() `call in `withNRToken` (within the `TokenLinkingSubscriber` utility class) is successful

<img width="1658" alt="TokenLinkSuccess" src="https://github.com/newrelic/newrelic-java-agent/assets/3496648/d940d1a3-f255-4833-8008-edd13ece5a2b">

The only obvious reason why the token linking would fail in this scenario is if the `link()` method were to get a null `Transaction` reference, meaning that no `Transaction` was actually started or that the context was lost at the point where the link was attempted.

<img width="1651" alt="TokenLinkFailure" src="https://github.com/newrelic/newrelic-java-agent/assets/3496648/431f9c0d-8328-4d4f-868d-82ce99990f49">

---

It's not clear if this ticket is specifically meaning to call out a perceived issued with the `netty-reactor-0.9.0` instrumentation or if a similar issue was discovered when attempting to write a custom instrumentation module. If it's the former, then it appears to be working correctly, if it's the latter we would need to know more details about the specific scenario.

**Comment by philsttr** [comment]
Hi Jason.  Thank you so much for your time and investigation!  I really appreciate it since this problem is blocking some of the custom instrumentation we would like to write, and therefore preventing us from adopting newrelic in more of our services.

I originally found the problem when writing some custom instrumentation, and I spent a lot of time debugging it.
Before filing the original [support case](https://support.newrelic.com/s/case/5008W00000wZM8PQAW) for the problem, I wanted to find and provide a minimal reproducible scenario.
That's when I noticed that I could also reproduce the bug with the reactor-netty instrumentation and `TokenLinkingSubscriber`.
So I used that as an example, since I thought it would be easier for newrelic to reproduce.

Something must be different when running the newrelic java agent in an application as I have done (which demonstrates the problem), versus running the `TransactionPropagationTest` as you have done  (which does not demonstrate the problem).
Perhaps `TransactionPropagationTest` is setting up something that is not quite the same as when running in an application.
I haven't looked into that yet, but I can most definitely reproduce the problem in a running application, so _something_ has to be different.  I'd like to understand what.

When I filed the original support case, I provided an example project and a short video and that 
* showed how to setup the test case
* demonstrated the problem,
* stepped through a debugger showing where the problem occurs, and 
* demonstrated calling `AgentPostprocessors.setTracedWeaveInstrumentationDetails` in the debugger to "fix" the problem.

The support folks directed me to file a bug here.  I should have included the video and project here when I filed this bug for you to review.  I will link them below.

I would really appreciate it if you could review [the full video](https://youtu.be/o98JP25OZuE), and use [the project](https://github.com/newrelic/newrelic-java-agent/files/12136121/newrelic-trace-on-util.zip) to reproduce the problem as I have done, rather than a separate testcase with different setup.
I would love to hear your diagnosis on why the problem can be reproduced in a running application, but not in the `TransactionPropagationTest`.  In the meantime, I will also look into how `TransactionPropagationTest` is setup, to see if I can identify what is different about that working test case.

Again, thank you for your time.  I really hope we can identify what is causing the behavior I am seeing, so we can rollout newrelic to more of our services.

**Comment by jasonjkeller** [comment]
Hey @philsttr , thanks for the additional context, it does help to clarify a bit. 

The project that you linked didn't have any controllers in it but I added the following based on what you were showing in the YT video. Let me know if this is not correct for the repro.

```
@RestController
public class ExampleController {

    @GetMapping(path = "/works")
    public Mono<String> works() {
        return Mono.fromCallable(() -> "Works");
    }

    @GetMapping(path = "/does-not-work")
    public Mono<String> doesNotWork() {
        return Mono.fromCallable(() -> "Does Not Work").subscribeOn(Schedulers.boundedElastic());
    }
}
```

I am able to see some of the things you pointed out in the debugger when running the repro app but I'm not entirely clear on what the impact is that is blocking your custom instrumentation.

Here's a trace I see when hitting the `/does-not-work` route. It is correctly named after the controller route and the utility class method `com.nr.instrumentation.reactor.netty.TokenLinkingSubscriber/withNRToken` is getting traced. Can you elaborate on what you are expecting to see (or not see) when hitting the `/does-not-work` route and how it would differ from this? 

<img width="999" alt="does-not-work-trace" src="https://github.com/newrelic/newrelic-java-agent/assets/3496648/823b80c6-c94b-4b52-b89a-bdb7c73466fd">

Also, what version of the Java agent are you using when debugging? Do you have the same issues with the latest version of the agent? We've had quite a few fixes/improvements around Spring/Reactor/Netty/Token linking instrumentation over the past year or so, so if you haven't tested with a recent agent release it would be worth doing so to see if the issue has been resolved.

Even though I can see the things you pointed out when hitting the `/does-not-work` route at times while debugging, I also see things that are to the contrary.

For instance, these screenshots show the token being linked when `withNRToken` is called and the `/does-not-work` route is hit. It also shows the `TraceDetails` being instantiated when hitting the same route.

<img width="1687" alt="withNRTokenLinked" src="https://github.com/newrelic/newrelic-java-agent/assets/3496648/2945d3a3-cee4-42e9-9e1e-45a6170af988">

<img width="1686" alt="TraceDetails2" src="https://github.com/newrelic/newrelic-java-agent/assets/3496648/ad2cc531-34e0-4eed-9c60-9cb39bc2692a">

All of the screenshots are captured while debugging with Java agent version 8.4.0.

Generally speaking, using `@Trace` in a utility class is not a problem as we know that it works but there might be a gap in instrumentation somewhere that is causing the transaction context to get lost with your custom instrumentation and thus preventing token linking. 

In the past, we've seen cases where an unexpected thread hop due to the use of `subscribeOn(Schedulers.boundedElastic())` caused token linking failures. That's a problem that we thought was addressed, and which appears to be looking at the trace I posted, but perhaps there's a gap still present in more complicated scenarios. In cases where the `boundedElastic` scheduler was causing issues it would manifest as the transaction being named something like `NettyDispatcher` instead of being correctly named after the Spring controller route.

**Comment by philsttr** [comment]
> The project that you linked didn't have any controllers in it but I added the following based on what you were showing in the YT video. Let me know if this is not correct for the repro.

Oops, I attached the wrong zip.  But the controller you mentioned is correct.  It's a simple project.

> Also, what version of the Java agent are you using when debugging?  Do you have the same issues with the latest version of the agent? 

When I recorded the video in November, I was using 7.11.0, which was the latest at the time.

I have retested today with 8.4.0.

I still see the problem with 8.4.0, but the behavior is _slightly_ different, as I'll describe below...

Regarding the breakpoint in [`TraceClassVisitor.visitMethod`](https://github.com/newrelic/newrelic-java-agent/blob/v8.4.0/newrelic-agent/src/main/java/com/newrelic/agent/instrumentation/tracing/TraceClassVisitor.java#L99), restricted to this condition: `this.className.contains("com/nr/instrumentation/reactor/netty/TokenLinkingSubscriber") && name.equals("withNRToken")`...

That breakpoint will be hit on application startup, where the `TraceDetails` will be null.  This is the same behavior in 8.4.0 as seen in the video for 7.11.0.  It shows that the `TokenLinkingSubscriber` class is not instrumented properly on application startup.

Resume from the breakpoint, allow the app to finish startup, and then call the `does-not-work` endpoint.
You will see the following logs repeated in the newrelic log, assuming you enabled the debuging/logging system properties I mentioned in the video.  This is the exact same behavior as in the video, and demonstrates the link failures in 8.4.0.

```
2023-07-26T13:28:09,312+0200 [10743 63] com.newrelic FINER: Transaction com.newrelic.agent.Transaction@9c94c1: ignoring link call because there is no started txa to link to: null.
2023-07-26T13:28:09,313+0200 [10743 63] com.newrelic WARN: Token: com.newrelic.agent.TokenImpl@772d239e was NOT linked because there was no Transaction in progress. Did you forget to add @Trace(async = true) to: com.nr.instrumentation.reactor.netty.TokenLinkingSubscriber.withNRToken(TokenLinkingSubscriber.java:68)?
```

But, this is where things are slightly different for 8.4.0.  Specifically, in 8.4.0 you'll also see this log message, due to [this change](https://github.com/newrelic/newrelic-java-agent/commit/8383d4cd5d64b56c56d65e6139f4e38299d2c4de#diff-70ddce336c17986192f634432e307e26bdd2f158cb91cd64366d1a5d6231358cR1427)...

```
2023-07-26T13:52:34,845+0200 [18461 63] com.newrelic.agent.instrumentation.ClassTransformerServiceImpl FINE: Retransforming com.nr.instrumentation.reactor.netty.TokenLinkingSubscriber.withNRToken for instrumentation.
```

It appears the link failure now schedules a reinstrumentation of the `TokenLinkingSubscriber` class, which was not instrumented correctly on startup (when `TraceDetails` was null above).

A few seconds later, when the [`PeriodicRetransformer`](https://github.com/newrelic/newrelic-java-agent/blob/v8.4.0/newrelic-agent/src/main/java/com/newrelic/agent/reinstrument/PeriodicRetransformer.java#L25) runs, the [`TraceClassVisitor.visitMethod`](https://github.com/newrelic/newrelic-java-agent/blob/v8.4.0/newrelic-agent/src/main/java/com/newrelic/agent/instrumentation/tracing/TraceClassVisitor.java#L99) breakpoint will be hit again.  This time the `TraceDetails` will be non-null when instrumenting `TokenLinkingSubscriber`.

If you call the `does-not-work` endpoint again, you won't see the WARN in the logs anymore, which indicates that linking is now working.

Yay!  However, all is not working quite yet.  Even though token linking in `TokenLinkingSubscriber` works after it is re-instrumented (when `TraceDetails` was not null), transaction details are not available where I would expect them to be.

To demonstrate the problem, change the controller to this:

```
@RestController
public class ExampleController {

	@GetMapping(path = "/works")
	public Mono<String> works() {
		return Mono.fromCallable(() -> response("works"));
	}

	@GetMapping(path = "/does-not-work")
	public Mono<String> doesNotWork() {
		return Mono.fromCallable(() -> response("does-not-work"))
				.subscribeOn(Schedulers.boundedElastic());
	}

	private String response(String endpoint) {
		NewRelic.setTransactionName("custom", endpoint + "-custom-transaction-name");
		NewRelic.addCustomParameter("custom.param", endpoint);

		Transaction transaction = NewRelic.getAgent().getTransaction();
		TracedMethod tracedMethod = transaction.getTracedMethod();
		return endpoint
				+ "\nTransaction:  " + transaction
				+ "\nTracedMethod: " + tracedMethod;
	}
}
```

I expect the custom transaction name and parameter to be set in all cases.
However, the `does-not-work` endpoint will fail to set the custom transaction name and parameter after the `TokenLinkingSubscriber` class is reinstrumented after the first call.

1. Start the application
2. Call `does-not-work`.  Observe that the transaction seen in the response is an instance of `TransactionApiImpl`
3. Wait for `TokenLinkingSubscriber` to be reinstrumented (as described above)
4. Call `does-not-work` again. Observe that the transaction seen in the response is an instance of `NoOpTransaction`, and the custom transaction and custom parameter are not properly set.

I'm not sure if this behavior is related to the original problem, or something else.


To summarize...

There is still a bug in 8.4.0 in the initial (lack of) instrumentation of `TokenLinkingSubscriber` during application startup, where `TokenDetails` is observed as null in [`TraceClassVisitor.visitMethod`](https://github.com/newrelic/newrelic-java-agent/blob/v8.4.0/newrelic-agent/src/main/java/com/newrelic/agent/instrumentation/tracing/TraceClassVisitor.java#L99).  The missing instrumentation on startup is obvious due to the WARN log message on the first call to `does-not-work`.

There also appears to be a different problem after the reinstrumentation of `TokenLinkingSubscriber`.

I'd like to resolve the first problem before focusing too much on the second problem.
Specifically, I'd like to get the initial instrumentation of `TokenLinkingSubscriber` during application startup working.

**Comment by philsttr** [comment]
Another observation I made... When testing our custom instrumentation that uses a `@Trace` annotation on a method in a utility class with newrelic-java-agent 8.4.0, I noticed that it does not trigger the reinstrumentation that I mentioned above (the "Retransforming" log line).  Therefore, the failed instrumentation of the utility classes during application startup continues to affect the application for the lifetime of the application.

I believe there is sufficient evidence to prove that instrumentation of these utility classes is not working properly during application startup.  I believe you have seen this evidence for yourself.  Specifically:
* It can be seen in a debugger: when [`TraceDetails` is null](https://github.com/newrelic/newrelic-java-agent/blob/v8.4.0/newrelic-agent/src/main/java/com/newrelic/agent/instrumentation/tracing/TraceClassVisitor.java#L99) when visiting the method annotated with `@Trace` in a utility class, causing [the instrumentation for that method](https://github.com/newrelic/newrelic-java-agent/blob/v8.4.0/newrelic-agent/src/main/java/com/newrelic/agent/instrumentation/tracing/TraceClassVisitor.java#L100-L265) to be skipped.
* It can also be seen in the logs: with the message `Did you forget to add @Trace(async = true)`, when it is clear that `@Trace(async = true)` is not missing.


Additionally, the "fix" I mentioned in this issue description and in the video of calling `((AgentPostprocessors)weavePackage.getConfig().getPostprocessor()).setTracedWeaveInstrumentationDetails(((AgentPreprocessors)weavePackage.getConfig().getPreprocessor()).getTracedWeaveInstrumentationDetails())` in [`PackageValidationResult.computeUtilityClassBytes`](https://github.com/newrelic/newrelic-java-agent/blob/v8.4.0/newrelic-weaver/src/main/java/com/newrelic/weave/weavepackage/PackageValidationResult.java#L555-L565) for the utility class in a debugger during application startup continues to solve the problem in 8.4.0.  In other words, if I do this, then the initial instrumentation of the utility class during application startup works, and `TokenLinkingSubscriber.withNRToken` works the first time, and my custom instrumentation works as well.

Since...
1. it is clear that instrumentation of `@Trace` on a method on some (all?) utility classes is not working on startup, and
2. I can "fix" that instrumentation on startup by setting the `tracedWeaveInstrumentationDetails` in a debugger, and 
3. the `@Trace` method works properly every time after that (without needing to be reinstrumented), and
4. reinstrumentation of utility classes is not guaranteed to happen after the first failed attempt during startup

... I believe it is critical to fix the problem identified while instrumenting utility classes on startup.

**Comment by jasonjkeller** [comment]
@philsttr 

I opened PR https://github.com/newrelic/newrelic-java-agent/pull/1443 to test a change that explicitly calls `AgentPostprocessors.setTracedWeaveInstrumentationDetails`.

As you observed, it has the effect of changing the behavior such that the following is no longer logged, and TokenLinkingSubscriber is no longer being retransformed after calling the `/does-not-work` endpoint:

```
WARN: Token: com.newrelic.agent.TokenImpl@772d239e was NOT linked because there was no Transaction in progress
```

There is a custom build of the agent that you can find here if you want to do any testing with it: https://github.com/newrelic/newrelic-java-agent/actions/runs/5827290767

That said, it does not seem to address the problem that you pointed out with the refactoring of the controller where you are setting the transaction name (i.e. `NewRelic.setTransactionName("custom", endpoint + "-custom-transaction-name");`). Specifically, the renaming still isn't working when calling the `/does-not-work` endpoint. I am not entirely sure what is going on other than that a valid transaction doesn't seem to be linked where the response method is being called. There's also a couple of tokens involved in the lifecycle of the transaction.

```
// TokenImpl@5d74ef44 created
2023-08-10T16:25:39,362-0700 [43821 58] com.newrelic INFO: Token: com.newrelic.agent.TokenImpl@5d74ef44 created for Transaction: com.newrelic.agent.Transaction@5322c2e5, at: io.netty.bootstrap.NettyDispatcher.channelRead(NettyDispatcher.java:50)
2023-08-10T16:25:39,371-0700 [43821 58] com.newrelic INFO: Token: com.newrelic.agent.TokenImpl@5d74ef44 linked for Transaction: com.newrelic.agent.Transaction@5322c2e5, at: reactor.netty.http.server.HttpTrafficHandler.channelRead(HttpTrafficHandler.java)
2023-08-10T16:25:39,377-0700 [43821 58] com.newrelic INFO: Token: com.newrelic.agent.TokenImpl@5d74ef44 link ignored for Transaction: com.newrelic.agent.Transaction@5322c2e5, at: reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java)

// TokenImpl@34923295 created
2023-08-10T16:25:39,378-0700 [43821 58] com.newrelic INFO: Token: com.newrelic.agent.TokenImpl@34923295 created for Transaction: com.newrelic.agent.Transaction@5322c2e5, at: org.springframework.web.server.adapter.HttpWebHandlerAdapter.createExchange(HttpWebHandlerAdapter.java)
2023-08-10T16:25:39,382-0700 [43821 70] com.newrelic INFO: Token: com.newrelic.agent.TokenImpl@34923295 linked for Transaction: com.newrelic.agent.Transaction@5322c2e5, at: com.nr.instrumentation.reactor.netty.TokenLinkingSubscriber.withNRToken(TokenLinkingSubscriber.java:68)
2023-08-10T16:25:39,382-0700 [43821 70] com.newrelic INFO: Token: com.newrelic.agent.TokenImpl@34923295 linked for Transaction: com.newrelic.agent.Transaction@5322c2e5, at: com.nr.instrumentation.reactor.netty.TokenLinkingSubscriber.withNRToken(TokenLinkingSubscriber.java:68)
2023-08-10T16:25:39,383-0700 [43821 58] com.newrelic INFO: Token: com.newrelic.agent.TokenImpl@5d74ef44 linked for Transaction: com.newrelic.agent.Transaction@5322c2e5, at: reactor.netty.http.server.HttpTrafficHandler.channelRead(HttpTrafficHandler.java)
2023-08-10T16:25:39,383-0700 [43821 70] com.newrelic INFO: Token: com.newrelic.agent.TokenImpl@34923295 linked for Transaction: com.newrelic.agent.Transaction@5322c2e5, at: com.nr.instrumentation.reactor.netty.TokenLinkingSubscriber.withNRToken(TokenLinkingSubscriber.java:68)
2023-08-10T16:25:39,383-0700 [43821 58] com.newrelic INFO: Token: com.newrelic.agent.TokenImpl@5d74ef44 link ignored for Transaction: com.newrelic.agent.Transaction@5322c2e5, at: reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java)

// TokenImpl@5d74ef44 expired
2023-08-10T16:25:39,386-0700 [43821 58] com.newrelic INFO: Token: com.newrelic.agent.TokenImpl@5d74ef44 expired for Transaction: com.newrelic.agent.Transaction@5322c2e5, at: com.agent.instrumentation.netty40.NettyUtil.processResponse(NettyUtil.java:52)
2023-08-10T16:25:39,386-0700 [43821 58] com.newrelic INFO: Token: com.newrelic.agent.TokenImpl@34923295 linked for Transaction: com.newrelic.agent.Transaction@5322c2e5, at: com.nr.instrumentation.reactor.netty.TokenLinkingSubscriber.withNRToken(TokenLinkingSubscriber.java:68)
2023-08-10T16:25:39,387-0700 [43821 58] com.newrelic INFO: Token: com.newrelic.agent.TokenImpl@34923295 link ignored for Transaction: com.newrelic.agent.Transaction@5322c2e5, at: com.nr.agent.instrumentation.spring.reactive.Util$TokenLinkingSubscriber.withNRToken(Util.java:78)

// TokenImpl@34923295 expired
2023-08-10T16:25:39,387-0700 [43821 58] com.newrelic INFO: Token: com.newrelic.agent.TokenImpl@34923295 expired for Transaction: com.newrelic.agent.Transaction@5322c2e5, at: com.nr.agent.instrumentation.spring.reactive.Util$TokenLinkingSubscriber.withNRToken(Util.java:78)
```

Out of curiosity, with your custom instrumentation, is it specifically failing due to this issue with `TokenLinkingSubscriber.withNRToken`? Or have you introduced a new utility class in your instrumentation that is showing the same behavior?

**Comment by philsttr** [comment]
Thanks @jasonjkeller !

> There is a custom build of the agent that you can find here

Great! I'll test it next week, and let you know how it goes.

> That said, it does not seem to address the problem that you pointed out with the refactoring of the controller where you are setting the transaction name

Ok, that might not have been the best test.  I'll test our custom instrumentation where I first noticed the problem to confirm the fix.

> Out of curiosity, with your custom instrumentation, is it specifically failing due to this issue with TokenLinkingSubscriber.withNRToken? Or have you introduced a new utility class in your instrumentation that is showing the same behavior?

Our custom instrumentation has a new utility class, with some methods annotated with `@Trace`.  This is where I first noticed the problem.  Then I looked for other locations that might be affected by the same problem and found the `TokenLinkingSubscriber` had the same problem.

**Comment by philsttr** [comment]
I had some time to do a quick test on the custom build today.  It does indeed solve the problem.  The util classes in our custom instrumentation work properly now. :)

**Comment by jasonjkeller** [comment]
Awesome, that's great to hear!

I'll go ahead and submit the PR to the team for review so that we can look to get it into an upcoming agent release.

**Comment by jasonjkeller** [comment]
Going to close out this issue as the PR with the fix has been merged and will be included in the next agent release unless any issues crop up between now and then. https://github.com/newrelic/newrelic-java-agent/pull/1443

I've also gone ahead and filed another ticket for the issue regarding transaction renaming when using `subscribeOn(Schedulers.boundedElastic())`. Not sure when this one will make it on to our roadmap though. https://github.com/newrelic/newrelic-java-agent/issues/1450

Thanks again for all of your help on this issue @philsttr !
