### ISSUE TITLE
Missing newrelic-java.zip in current folder

### ISSUE THREAD

**Issue by honsq90** [newrelic/newrelic-java-agent#1080]
## Description
We currently download from https://download.newrelic.com/newrelic/java-agent/newrelic-agent/current/newrelic-java.zip to stay up to date.

## Expected Behavior

Expected the zip file to exist.

## Troubleshooting

The contents of https://download.newrelic.com/newrelic/java-agent/newrelic-agent/7.11.1/ vs https://download.newrelic.com/newrelic/java-agent/newrelic-agent/current shows that there's newrelic-java-7.11.1.zip but not newrelic-java.zip.

<img width="779" alt="Screenshot 2022-11-16 at 07 25 07" src="https://user-images.githubusercontent.com/1791439/202018490-b5da494d-8ba3-4b82-827f-11928d144d3b.png">
<img width="766" alt="Screenshot 2022-11-16 at 07 25 13" src="https://user-images.githubusercontent.com/1791439/202018505-787fc857-6ce6-4241-8a2b-916eaf2e6341.png">

## Steps to Reproduce

Visit https://download.newrelic.com/newrelic/java-agent/newrelic-agent/current/newrelic-java.zip

**Comment by meiao** [comment]
This has been fixed.
