### ISSUE TITLE
Memory leak in java newrelic agent with java 1.8.0_342

### ISSUE THREAD

**Issue by gauravFarEye** [newrelic/newrelic-java-agent#1107]
We can see newrelic agent is holding elastic search response for long time even GC was run.

## Description
In eclipse memory analyser tool , we are seeing com.newrelic.agent.deps.com.github.benmanes.caffeine.cache.BoundedLocalCache$BoundedLocalManualCache class is holding object of Elastic search response.

## Expected Behavior
It should not hold these objects.

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results
[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

## Steps to Reproduce
connect java application with elastic search 7.17 version using elastic-rest-client 7.17 and make search request, response from elastic search is being captured in com.newrelic.agent.deps.com.github.benmanes.caffeine.cache.BoundedLocalCache$BoundedLocalManualCache class.

## Your Environment
newrelic agent version -> 7.10.0
java version -> 1.8.0_342
elasticsearch version -> 7.17

## Additional context
[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )

**Comment by gauravFarEye** [comment]
![Screenshot from 2022-12-29 09-52-47](https://user-images.githubusercontent.com/80401080/209934854-579c3c94-c474-4911-b498-7c5ba1b991c5.png)

**Comment by kford-newrelic** [comment]
@gauravFarEye thanks for raising this issue to our attention

However "memory leak" type of issues typically require more information that's gathered with the help of one of our support engineers - are you able to open a support case on this issue?

**Comment by kford-newrelic** [comment]
@gauravFarEye closing this issue - please open a support case so we can have an engineer work closely with you to collect information needed for further troubleshooting
