### ISSUE TITLE
NullPointerException thrown when calling addCustomAttributes

### ISSUE THREAD

**Issue by dhilpipre** [newrelic/newrelic-java-agent#1115]
[NOTE]: # In a least one use case, a NullPointerExeception is thrown when calling any of the addCustomAttribute or addCustomAttributes method on TracedMethod.  The exception is being thrown in the shouldAddAttribute() of AbstractTracer.

## Description
If the following is true then a NullPointerExeception is  thrown by the Agent,  The async token is created but no transaction is started (No-op token created).   If a method is called with the @Trace attribute async set to true and the token is linked then if you try to add an attribute to TracedMethod it results in a NullPointerExeception.    This seems to happen because when the resulting TransactionActivity is created its Transaction object is set to null.
 In some cases it results in the application not working properly.

## Expected Behavior
The code for shouldAddAttribute should check if the getTransaction is returning null if if it is return false.

## Steps to Reproduce
Attached is a simple Java application that illustrates the problem
[code.tar.gz](https://github.com/newrelic/newrelic-java-agent/files/10339137/code.tar.gz)

(Replicate to Jira)

## Your Environment
Simply running the attached code from the command line with the Java Agent enabled.

## Additional context
All that is probably needed is make a simple update to the code for shouldAddAttribute to include a check for a null transaction

**Comment by kford-newrelic** [comment]
@dhilpipre thanks for letting us know about this issue!
