### ISSUE TITLE
Increasing minor gc when i use Spring Webflux with Newrelic java agent

### ISSUE THREAD

**Issue by jiwoongleee** [newrelic/newrelic-java-agent#1117]
I wonder if the problem in the link is solved.

[Link](https://discuss.newrelic.com/t/too-many-transactionservices-updatequeue-object-created-so-increasing-minor-gc-when-i-use-spring-webflux-with-newrelic-java-agent/75636)

**Comment by kford-newrelic** [comment]
@jiwoongleee we'll assume that the issue you link to resolves the issue you created. If not, please re-open and provide more details on the nature of the issue, how to reproduce it and if possible example code that reproduces it. Thank you!
