### ISSUE TITLE
Support for environment variable substitution in the agent config file

### ISSUE THREAD

**Issue by zsrv** [newrelic/newrelic-java-agent#1122]
## Feature Description
It should be possible to use environment variables in the New Relic Java agent config file.

Example: Using `log_file_path: ${MY_LOG_FILE_PATH}` in newrelic.yml should substitute the value of environment variable `MY_LOG_FILE_PATH` for `${MY_LOG_FILE_PATH}`.

I have a working implementation [here](https://github.com/zsrv/newrelic-java-agent/commit/87e429f0105abba59a1d4cfad5e67d18d922e98c) (mostly taken from SnakeYAML's code [here](https://github.com/snakeyaml/snakeyaml/blob/master/src/main/java/org/yaml/snakeyaml/env/EnvScalarConstructor.java), more information [here](https://bitbucket.org/snakeyaml/snakeyaml/wiki/Variable%20substitution)), but I'm not sure how production-worthy this code is.

## Additional context
A Java application is being deployed to a managed platform that has a predefined set of environment variables containing values that I want to use in the New Relic agent's configuration. It is not possible to define custom environment variables on this platform. It is possible to set Java system properties but I would rather keep most of the configuration in newrelic.yml.

## Priority
Really Want

**Comment by kford-newrelic** [comment]
Hi @zsrv thanks for the enhancement request/suggestion

Most of the agent [configuration](https://docs.newrelic.com/docs/apm/agents/java-agent/configuration/java-agent-configuration-config-file/) can be set either through the config file, system properties or even **directly through environment variables** - have you tried setting environment variables directly?

**Comment by zsrv** [comment]
Hi @kford-newrelic, the problem is that on the (legacy, in-house) platform we are deploying our application on does not let us set our own environment variables. There is a predefined set of variables that we can use if we want. For example, there could be predefined variable `APP_NAME` that has the name of our application that we can use, but we couldn't set our own variable `NEW_RELIC_APP_NAME`.

We can set Java system properties, and is in fact what we are doing right now, but I only consider this to be a workaround since it makes configuration much messier for us.

**Comment by kford-newrelic** [comment]
@zsrv we discussed this in-depth but unfortunately decided that we would not add this to our agent roadmap. We know that's disappointing but we cannot accept every enhancement request.

**Comment by philomory** [comment]
I think you should reconsider this request, if only for feature parity with the New Relic Infrastructure Agent, which *does* offer this functionality (although, it is so poorly documented I wouldn't fault even New Relic employees for not being aware of that)
