### ISSUE TITLE
Programmatic access to intercept/filter reported exceptions

### ISSUE THREAD

**Issue by koenpunt** [newrelic/newrelic-java-agent#1127]
## Is your feature request related to a problem? Please describe.

Not entirely sure where the solution lies, so I've opened a [related issue](https://github.com/spring-projects/spring-graphql/issues/600) on the spring-graphql repository.

We're using spring-graphql to build a graphql server, and are using NewRelic for monitoring and error reporting. However, the NewRelic agent incorrectly captures exceptions that are also handled by the framework, and thus shouldn't be interpreted/reported as an exception. 
It seems to me that the agent instruments reactive streams, and reports exceptions that are emitted in those streams, but somehow also captures exceptions that are handled in other ways. 
I don't know exactly how errors are handled in spring-graphql (or graphql-java), but if it can't be prevented that errors are captured by the agent, at least a programmatic way of intercepting them, and possible discarding them would be a helpful feature.

## Feature Description

A programmatic way of intercepting and/or discarding captured exceptions.

## Describe Alternatives

Completely ignoring the specific exception, but since there are also valid use cases for the exception it would cause them to go unnoticed.

## Additional context

See the issue on the spring-graphql repo for additional details: https://github.com/spring-projects/spring-graphql/issues/600

## Priority

Nice to Have; we currently have noise in our error reporting.

**Comment by koenpunt** [comment]
Any feedback on this?

**Comment by kford-newrelic** [comment]
Hi @koenpunt have you taken a look at the ability to `ignore` or `expect` errors from our [documentation](https://docs.newrelic.com/docs/apm/agents/java-agent/configuration/java-agent-error-configuration/)? Does this give you anything close to what you're looking for?

**Comment by koenpunt** [comment]
Afaik it's only possible to ignore an exception completely, but since there are valid cases for the exception that's not a solution. Hence my question for programmatic interception, where we can make the decision in code whether or not we want to report an exception.

**Comment by koenpunt** [comment]
Apart from that; any idea why this exception is reported to NewRelic even when it's also handled by the library?

**Comment by kford-newrelic** [comment]
Thanks for the additional context - we'll review your request for one of our upcoming quarters but there's no guarantee that it will be selected

Let me check with other engineers on your specific question about the exception handling

**Comment by kford-newrelic** [comment]
@koenpunt we discussed your suggested enhancement and while we felt it is a good one, we decided against adding it to our agent roadmap. We know this will be disappointing to hear but we do not have the ability to accept all enhancement requests

Regarding your question about why the exception is still seen by our agent when it's handled by the library; we're not completely sure. If you could create a simple repro app that demonstrates the problem, we could take a look
