### ISSUE TITLE
H2 Database Metrics are not collected when running JDK 11

### ISSUE THREAD

**Issue by RobertTTaylor9517** [newrelic/newrelic-java-agent#117]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )
When using the Java Agent with an application running JDK 8, New Relic is able to receive metrics for my H2 database. After upgrading my JDK to Open JDK 11 I can no longer see my H2 database metrics. I was able to confirm that the instrumentation for my H2 database is still being loaded. 

Support Ticket #: 431564

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen. )
To be able to receive metrics for our H2 database calls as we did when using JDK 8.

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results
[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )
Logs are further details are in the support ticket below.

## Steps to Reproduce
[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )
There is a sample application in the support ticket.

## Additional context
[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )
Internal support ticket with details: https://newrelic.zendesk.com/agent/tickets/431564

(Migrate to Jira)

**Comment by XiXiaPdx** [comment]
I've confirmed the lack of database activity in the test app. The H2 database instrumentation is different between Java 8 and 11.  With JDK 11, we are skipping jdbc-generic instrumentation of the H2 database classes. 

Java 8 
<img width="1124" alt="Screen Shot 2020-11-17 at 1 07 52 PM" src="https://user-images.githubusercontent.com/24482401/99450823-28f21c00-28d6-11eb-846f-309eb8c8abdc.png">


Java 11
<img width="845" alt="Screen Shot 2020-11-17 at 1 09 27 PM" src="https://user-images.githubusercontent.com/24482401/99450841-2e4f6680-28d6-11eb-93f6-44d4efc60ab7.png">

**Comment by fbessai** [comment]
Hi @XiXiaPdx , this issue is happening also for MySql. It's not only specific to H2

**Comment by kford-newrelic** [comment]
@richard-gibson not necessarily specific to our Spring Reactive initiative but let's start under the assumption that we can leverage this for that too... We can switch gears and create a separate/new issue if that makes more sense.

**Comment by kford-newrelic** [comment]
Not selected for the next quarter's product roadmap. Will consider for a future quarter.

**Comment by kford-newrelic** [comment]
Need to spike on this a bit. Are more supported instrumentation modules affected (or just H2)? More JDK versions (or just 11)?

**Comment by jtduffy** [comment]
I took an old Spring boot 2 project with H2, and tested with J11, 17 and 21. In all cases, the transactions reported successfully, including the H2 interactions. All relevant JDBC and H2 instrumentation also applied properly.
