### ISSUE TITLE
Java 20 support?

### ISSUE THREAD

**Issue by seancorfield** [newrelic/newrelic-java-agent#1211]
## Is your feature request related to a problem? Please describe.

Java 20 has been available for about a month so we've been testing against it in dev/test/CI for a few weeks and would like to get it into our staging environment -- but New Relic 8.1.0 doesn't support 20 yet so we're blocked from any further testing.

Do you have a sense of when Java 20 support will be available in New Relic?

Our main reason for wanting to move to JDK 20 is that we'd been testing on JDK 19 and ran into two memory leak bugs in the JDK, one of which was fixed in an update to 19 but the other is only fixed in 20, and has not been backported to 19.

**Comment by tbradellis** [comment]
Hey @seancorfield .  I don't have an exact release date or version, but it's on our current quarter roadmap and is in progress.
For testing purposes, you could run with this option:
`-Dnewrelic.config.experimental_runtime=true`

This is what we use internally to test ahead of our currently supported version.  Often support just means us getting changes in to run our integration and other tests and confirm everything is passing. We also go through each JEP and ensure there are no issues.  Of course, at various times there have been changes we had to address for compatibility (usually on LTS versions). But, this setting might get you unblocked from a testing perspective. Hope that helps!

**Comment by seancorfield** [comment]
@tbradellis Great to hear this is on the roadmap -- thank you!

Also, good to know that we can at least _try_ JDK 20 with the current NR agent in staging. I'll report back if we run into anything strange.

**Comment by seancorfield** [comment]
I added that option on our staging environment and confirmed apps were starting up with it:
```
----------
Java version is: 20. This version of the New Relic Agent does not support versions of Java greater than 19.
Experimental runtime mode is enabled. Usage of the agent in this mode is for experimenting with early access or upcoming Java releas
es or at your own risk.
----------
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
2023-04-20T22:55:16,234+0000 [107319 1] com.newrelic INFO: New Relic Agent: Loading configuration file "/var/www/worldsingles/build/
config/newrelic.yml"
2023-04-20T22:55:16,369+0000 [107319 1] com.newrelic INFO: experimental_runtime is enabled
```
I'm seeing some custom traces reported to APM but none of the usual transaction stuff -- so it looks like you might have some work to do with the agent to make it JDK 20 compatible...?

We'll roll back to JDK 18 for now. Happy to test a prerelease of the Agent that has JDK 20 support if you want...

**Comment by iherasymenko** [comment]
I was able to get the APM and Logging to work on JDK 20 by using the latest 8.2.0 snapshot agent.

https://oss.sonatype.org/content/repositories/snapshots/com/newrelic/agent/java/newrelic-agent/8.2.0-SNAPSHOT/

Make sure you download the `newrelic-agent-8.2.0-20230502.191334-20.jar` or a more recent version.

**Comment by seancorfield** [comment]
Good to know, Ihor, thanks!

**Comment by seancorfield** [comment]
Just tested the 8.2.0 release against Temurin JDK 20 on our staging environment and it looks good, so I'm closing this out.

Thank you for the swift update!
