### ISSUE TITLE
Auto app naming doesn't work well with distributed tracing

### ISSUE THREAD

**Issue by gfuller1** [newrelic/newrelic-java-agent#124]
## Description

With the temporary fix for [https://github.com/newrelic/newrelic-java-agent/issues/123](https://github.com/newrelic/newrelic-java-agent/issues/123), the agent still reports span events under the wrong app name. It reports all span events under the default app name from the config, which is wrong.

## Expected Behavior

I would expect the agent to report span events under the app name that is on the span event.

## Historical Context

This used to partially work starting in agent version 4.9.0. What used to happen is it would report the transaction event to the proper app and then all the spans for that transaction would report to the base app. Since we decided to remove transaction events from the distributed trace UI and use the root span event instead it is unclear which app the span events are coming from.

Here's an example of an auto app naming application which has a base app and a second app who's name was set by our bridge API. Notice that all span events are still reported under the base app. [https://user-images.githubusercontent.com/58712431/100002710-cab3b600-2d79-11eb-87a9-67ec138f931b.png](https://user-images.githubusercontent.com/58712431/100002710-cab3b600-2d79-11eb-87a9-67ec138f931b.png)

There are two paths forward as I see it. We either provide several reservoirs for span sampling and report each one to its own application, or we keep 1 span reservoir and breakout the spans when we send them so they go to each of their respective endpoints. The first approach matches what we do with other services for auto app naming.

Aha! Link: https://newrelic.aha.io/features/JAVA-266

**Comment by XiXiaPdx** [comment]
WIP branch - https://github.com/newrelic/newrelic-java-agent/tree/spans-auto-app-name

code research for issue - https://docs.google.com/document/u/1/d/1QR9qMqfSA2ILtmGzgkxe6OdSN9knVHOx8e5tid91_MY/edit?usp=drive_web&ouid=111226347375403716922
