### ISSUE TITLE
Spring-Webflux, webclient doesn't capture Mono::switchIfEmpty external calls

### ISSUE THREAD

**Issue by tspring** [newrelic/newrelic-java-agent#125]

**Comment by jasonjkeller** [comment]
The New Relic Java agent (as of 6.2.1) currently isn't instrumenting some parts of the Spring WebFlux reactive code.

Namely, the Spring `WebClient` instrumentation doesn't capture:
* `Mono::switchIfEmpty` external calls
* `Flux::flatMap` external calls

It looks like the latter (`Flux::flatMap`) is a direct result of not instrumenting `switchIfEmpty` which is eventually called in the [DefaultWebClient](https://github.com/spring-projects/spring-framework/blob/master/spring-webflux/src/main/java/org/springframework/web/reactive/function/client/DefaultWebClient.java#L551-L563):

```java
		private <T> Mono<T> handleBodyMono(ClientResponse response, Mono<T> body) {
			body = body.onErrorResume(WebClientUtils.WRAP_EXCEPTION_PREDICATE, exceptionWrappingFunction(response));
			Mono<T> result = applyStatusHandlers(response);
			return (result != null ? result.switchIfEmpty(body) : body);
		}

		private <T> Publisher<T> handleBodyFlux(ClientResponse response, Flux<T> body) {
			body = body.onErrorResume(WebClientUtils.WRAP_EXCEPTION_PREDICATE, exceptionWrappingFunction(response));
			Mono<T> result = applyStatusHandlers(response);
			return (result != null ? result.flux().switchIfEmpty(body) : body);
		}
```

Here's an app that repros the issue: https://github.com/jasonjkeller/spring-webflux-repro

**Comment by tspring** [comment]
Closing as this is resolved in the current main branch
