### ISSUE TITLE
Support for java.net.http.HttpClient

### ISSUE THREAD

**Issue by mpostupalski** [newrelic/newrelic-java-agent#128]
## Is your feature request related to a problem? Please describe.
`java.net.http.HttpClient` is a standard Java http client so it would be nice to have it instrumented automatically

## Feature Description
`java.net.http.HttpClient` is instrumented automatically along with other 3rd party libraries

## Describe Alternatives
So far we are using custom instrumentation which is confusing. We can also switch to some 3rd party http client but we want to keep our client lightweight.

## Additional context
_none_

## Priority
Please help us better understand this feature request by choosing a priority from the following options: 
Really Want

Aha! Link: https://newrelic.aha.io/features/JAVA-192

**Comment by tspring** [comment]
Hi @mpostupalski , Thanks for creating this. Instrumentation for java.net.http.HttpClient has been on our roadmap for some time but I'm hopeful we'll get to it sometime in the next few weeks.

**Comment by tbradellis** [comment]
I've started work on this one.
