### ISSUE TITLE
Instrumentation Support for Jetty Server 12+

### ISSUE THREAD

**Issue by tbradellis** [newrelic/newrelic-java-agent#1300]
Jetty 12 has not released yet.
It was originally slated for June 1st, but there was no GA version released.
 https://www.eclipse.org/jetty/
Jetty 12 will have support for Jakarta EE 10

Download site:
https://www.eclipse.org/jetty/download.php

We capped our instrumentation as exclusive start 12-alpha
https://github.com/newrelic/newrelic-java-agent/blob/06c4e2ef4c5c66d5573d294acbf729a943d709e2/instrumentation/jetty-11/build.gradle#L13

Jetty Version | Servlet | License | Java
-- | -- | -- | --
Jetty 12.0.x | 6.0, 5.0, 4.0, 3.1 | JakartaEE 10/jakartaee.servlet.*JakartaEE 9/jakartaee.servlet.*JakartaEE 8/javax.servlet.* | Java 17+

Priority:
Must have

**Comment by seancorfield** [comment]
Is this planned to be in 8.7.0 along with JDK 21 support? We're eager to move to JDK 21 + Jetty 12 for the vthreads stuff (we're on JDK 20 + Jetty 11 right now, and we've been testing JDK 21 + Jetty 12 locally).

**Comment by meiao** [comment]
Unfortunately this did not make the cut for 8.7.0.

**Comment by seancorfield** [comment]
Thanks, @meiao -- do you know if Jetty 12 will make 8.8.0? (I assume JDK 21 is the focus right now for 8.7.0, which will at least move us forward one step).

**Comment by meiao** [comment]
We will start working on this soon. We expect it to be in 8.8.0.
