### ISSUE TITLE
Ensure all verifications run on internal jenkins for each pull request

### ISSUE THREAD

**Issue by jack-berg** [newrelic/newrelic-java-agent#131]
## Feature Description
The verification process is currently split between tasks that run as a part of github actions, and tasks that run internally on jenkins servers on a fixed schedule (the tasks are run against the main branch ~ 1 / day).

We should eventually move all the verification tasks to github actions, and add merge checks that require that all have passed. For now though, we'd at least like to be able to run all the jenkins verification tasks for each PR branch, rather than on a fixed schedule for the main branch. This would improve the PR flow because although external contributors wouldn't be able to see the results of the builds, the team would still be able to verify that all verification checks have passed before merging, and thus improve confidence in the code.

**Comment by kford-newrelic** [comment]
Currently being worked as part of the migration to GHA

**Comment by twcrone** [comment]
Tests running with PRs on GHA now.  Still work to be done on AITs but we will address on a different ticket after 7.5.0 release.
