### ISSUE TITLE
JBoss EAP 7.4 support

### ISSUE THREAD

**Issue by kford-newrelic** [newrelic/newrelic-java-agent#1336]
### Description
The current Compatibility and requirements for the Java agent document states
JBoss EAP 6.0 to 7.3 are supported (newer versions of JBoss EAP are not supported out of the box)

https://docs.newrelic.com/docs/apm/agents/java-agent/getting-started/compatibility-requirements-java-agent#app-web-servers
Need to add JBoss EAP 7.4 to the list of supported products.

### Acceptance Criteria
The NR Java Agent will properly instrument JBoss EAP 7.4 applications out-of-the-box.

### Design Consideration/Limitations
Need to review current instrumentation and the reported telemetry and compare/contrast .vs EAP 7.4 and resolve differences.

### Dependencies
N/A

### Additional context
Related issues:
* https://github.com/newrelic/newrelic-java-agent/issues/694
* https://github.com/newrelic/newrelic-java-agent/issues/697

**Comment by avation-ajayk** [comment]
Hi, We are in the middle of the integration for Jboss 7.4 and NR so any ETA on this ?

**Comment by meiao** [comment]
This is scheduled for Jul-Sep quarter.

**Comment by avation-ajayk** [comment]
@meiao @kford-newrelic  any updates on this any ETA?
