### ISSUE TITLE
Java agent OTEL convergence FY24Q2

### ISSUE THREAD

**Issue by kford-newrelic** [newrelic/newrelic-java-agent#1337]
### Description
Amongst our customer base there are early adopters who would like to use OTEL data and metric format whilst at the same time benefiting from the unique feature the java agent can offer. 

To that purpose a [prototype](https://github.com/newrelic/newrelic-opentelemetry-java/blob/main/README.md) has been built.

This work effort aims to investigate and implement the required changes to the prototype to a higher level of functionality for an internal preview test.

### Acceptance Criteria
TBD. Generally speaking, the intent is to add enough functionality to be able to conduct an internal preview.

### Design Consideration/Limitations
N/A

### Dependencies
N/A

### Additional context
N/A

**Comment by jasonjkeller** [comment]
This issue is resolved: https://issues.newrelic.com/browse/NR-152435
