### ISSUE TITLE
Improving unit testing code coverage (FY24Q2)

### ISSUE THREAD

**Issue by kford-newrelic** [newrelic/newrelic-java-agent#1339]
### Description
We have identified tools to measure unit test code coverage. We'll identify and put measures in place to reach 80% coverage. 

For FY24Q2, we at least want to show improvement to 70% (if 80% or better is not achievable)

### Acceptance Criteria
TBD

### Design Consideration/Limitations
N/A

### Dependencies
N/A

### Additional context
N/A

**Comment by jtduffy** [comment]
Unit test code coverage target of 70% reached on the java agent project, per CodeCov metrics
https://app.codecov.io/gh/newrelic/newrelic-java-agent
