### ISSUE TITLE
∞T Polish

### ISSUE THREAD

**Issue by jodeev** [newrelic/newrelic-java-agent#134]
As a user of Infinite Tracing, I expect to get my k8s metadata in the same way I would with the standard agent collector pipeline. Also, as a user of Infinite Tracing, I expect that I would not lose span data when New Relic redirects my traffic to a different cell.

These represent a small amount of additional work to get all agents to the same level with Infinite Tracing. We want to get this work done by end of November. This work does not block ∞T GA.

The spec PRs:  
 [https://source.datanerd.us/agents/agent-specs/pull/534](https://source.datanerd.us/agents/agent-specs/pull/534)  
 [https://source.datanerd.us/agents/agent-specs/pull/543](https://source.datanerd.us/agents/agent-specs/pull/543)

Part of the work is represented here: [https://newrelic.atlassian.net/browse/JAVA-5982](https://newrelic.atlassian.net/browse/JAVA-5982)

Aha! Link: https://newrelic.aha.io/features/JAVA-186

**Comment by kford-newrelic** [comment]
Discussed in the PM planning session. Agreement is to flesh out the requirements on this, then determine target for commitment.
