### ISSUE TITLE
Automate dependency scanning in active repos

### ISSUE THREAD

**Issue by kford-newrelic** [newrelic/newrelic-java-agent#1344]
### Description
Automate dependency scanning in active repos.

### Acceptance Criteria
Investigate trigger for automation (eg: Schedule? Activity?) and implement.

### Design Consideration/Limitations
Snyk or Dependabot?

### Dependencies
N/A

### Additional context
Duplicates [NR-127644](https://issues.newrelic.com/browse/NR-127644). See for additional details.

**Comment by deleonenriqueta** [comment]
Dependency scanning has been implemented for all active repos. We are utilizing Snyk and have set dependency scanning to be triggered with any pushes to main and on a weekly schedule.
