### ISSUE TITLE
Improve integration tests gap

### ISSUE THREAD

**Issue by kford-newrelic** [newrelic/newrelic-java-agent#1345]
### Description
Reduce the number of integration test gaps (reported "integration test issues" at the start of FY24Q2) by 5 or more.

### Acceptance Criteria
Fix at least 5 broken/missing integration tests (specific tests to be identified).

### Design Consideration/Limitations
N/A

### Dependencies
N/A

### Additional context
N/A

**Comment by jbedell-newrelic** [comment]
https://docs.google.com/spreadsheets/d/1wwhigbYyUcI9FLmZPHroElnZQ8LRgfeBPiGeyzaYxTI/edit?pli=1#gid=0

Looks like we've got our 5 for the quarter?

**Comment by jbedell-newrelic** [comment]
We've reduced by 5, and a 6th is being worked on.  See spreadsheet above.  Closing this issue.
