### ISSUE TITLE
Spike Sonarqube 9.9 issues

### ISSUE THREAD

**Issue by kford-newrelic** [newrelic/newrelic-java-agent#1348]
### Description
Investigate why Sonarqube 9.9 won't start up unless agent is run in lite_mode (further discussion on Sonarqube site [here](https://community.sonarsource.com/t/sonarqube-9-9-loading-always/90604/31)

- They are able to run our Java APM agent on SonarQube version 9.7 with no problem
- They upgraded their SonarQube version to 9.9 which makes use of Java 17 and our APM agent doesn’t function properly unless they run it in ‘lite_mode’
- The ask is that we investigate why / what issues we are having with running our agent in normal mode

### Acceptance Criteria
Agent is able to properly run with Sonarqube 9.9 and above.

### Design Consideration/Limitations
N/A

### Dependencies
N/A

### Additional context
[Support case](https://newrelic-neworg.lightning.force.com/lightning/r/Case/5008W000014bJsxQAE/view) and it looks like SonarQube isn't starting up (causes the app to crash)

**Comment by kanderson250** [comment]
Verified that SQ Server 9.7 runs with the agent and SQ Server 9.9 breaks. 

This was fixed by adding the following classes to `excludes`:

```
java/util/AbstractList$RandomAccessSpliterator
java/util/stream/MatchOps$MatchOp
java/util/stream/MatchOps$BooleanTerminalSink
javax/security/auth/Subject$SecureSet$1
```

- These were not added to the default agent excludes. 
- The exclusions were tested against our PR suite with all tests passing.

**Comment by kanderson250** [comment]
Update: The classes above were added to the default excludes file for the agent, so they will be excluded by default on the next release. 

Until the next release, customers can manually exclude the classes in their `newrelic.yml` file:

```
class_transformer:
    excludes: 
      ^java/util/AbstractList\$RandomAccessSpliterator, 
      ^java/util/stream/MatchOps\$MatchOp,
      ^java/util/stream/MatchOps\$BooleanTerminalSink, 
      ^javax/security/auth/Subject\$SecureSet\$1
```
