### ISSUE TITLE
Agent W3C Trace Context API

### ISSUE THREAD

**Issue by jodeev** [newrelic/newrelic-java-agent#135]
Support for W3C Trace Context in the API for customers who are have manual instrumentation. They need this API for header propagation.  
  
The Java agent currently does not support accepting W3C trace context formatted headers from manually instrumented external services. This breaks traces for customers such as those using services based Kafka and need this API in the Java agent to propagate trace headers.

This work is required to provide full support for W3C Trace Context.

---

Success criteria:
* The Java agent provides a public API that can create and accept W3C payloads over HTTP and non-HTTP
* Customers can find documentation on how to do these things as well as look at a working example
* Old `DistributedTracePayload` APIs are deprecated

Aha! Link: https://newrelic.aha.io/features/JAVA-138

**Comment by gfuller1** [comment]
I've written a document summarizing context and the work that needs to get done here: https://docs.google.com/document/d/1szf9UpDwGv52rODitBlwqDSiVA89W7y42ylrVAOalyQ/edit?usp=sharing
