### ISSUE TITLE
New Relic agent on Wildfly 28

### ISSUE THREAD

**Issue by saulocn** [newrelic/newrelic-java-agent#1373]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
Wildfly 28 with new relic agent is sending Web transactions as Other transactions. The web throughput is not shown correctly.

## Expected Behavior
Web transactions shown as Web throughput.

## Steps to Reproduce
Just upgraded an Wildfly 27 to Wildfly 28 and the information stop to be shown. On Wildfly 27 its fine. Maybe some incompatibility with an upgraded framework.
Tried with the last version of agent (8.4.0).

## Your Environment
The environment is an application Jakarta 10 running on Wildfly 28 on CentOS dockerized.

**Comment by kford-newrelic** [comment]
Need to check #875 and ensure that instrumentation properly works for Wildfly 27 too.

**Comment by obenkenobi** [comment]
@saulocn Yes it will. We have a [PR](https://github.com/newrelic/newrelic-java-agent/pull/1461) open that will allow us to support wildfly 23 till latest (i.e. 29)

**Comment by meiao** [comment]
@saulocn No, this will be in 8.6.0.
