### ISSUE TITLE
Spring 6 (Boot3) does not report underlying exception/stacktrace when a @RestControllerAdvice class is used

### ISSUE THREAD

**Issue by jtduffy** [newrelic/newrelic-java-agent#1393]
With Spring 5 (Boot v2), NR instrumentation reports the underlying exception when utilizing a @RestControllerAdvice class.  In Spring v6 (Boot v3) the underlying exception is not reported.

### Goals:
- Verify the exception behavior with Spring 5 and Spring 6
  - Reported exception behavior with @RestControllerAdvice
  - Reported exception behavior without @RestControllerAdvice 
- Investigate and document underlying cause
- Implement a fix or open an additional ticket if the fix is a heavy lift

#### UI Screenshot showing exception for Spring v5

![Springv5ShowingException](https://github.com/newrelic/newrelic-java-agent/assets/5081648/74ad1564-e09e-448a-85c9-aa9c8487a91b)

#### UI Screenshot showing examples with and without RestControllerAdvice

![RestControllerAdviceUI](https://github.com/newrelic/newrelic-java-agent/assets/5081648/a6470981-1790-4e87-9445-7e1beeca5a42)

#### Example repro code
![SampleSourceCode](https://github.com/newrelic/newrelic-java-agent/assets/5081648/ed3fbd56-9a07-4125-8efd-91a6a59b33c6)

**Comment by shashikantfayke** [comment]
Any update on this issue ? Recently we are also migrated to  spring boot3  with newrelic java  agent 8.5.0 and we are facing the same issue as well

**Comment by kford-newrelic** [comment]
@shashikantfayke not at the moment - we are planning to investigate further in the coming oct-dec quarter

**Comment by gustavodaquino** [comment]
I'm facing the same problem since we migrated our applications to SB 3.x due compliance reasons.
