### ISSUE TITLE
Plain Servlet isn't sending user data for code.namespace

### ISSUE THREAD

**Issue by kford-newrelic** [newrelic/newrelic-java-agent#1394]
The Span data collected for an app that only uses Servlet and no other web framework is collecting library data in its code.namespace value.

since this [query](https://api.newrelic.com/graphiql?#query=%7B%0A%20%20actor%20%7B%0A%20%20%20%20user%20%7B%0A%20%20%20%20%20%20email%0A%20%20%20%20%7D%0A%20%20%20%20accounts%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%7D%0A%20%20%20%20entity%28guid%3A%20%22MjA0Njg5N3xBUE18QVBQTElDQVRJT058MTA3NTAwNjkwNg%22%29%20%7B%0A%20%20%20%20%20%20name%0A%20%20%20%20%20%20permalink%0A%20%20%20%20%7D%0A%20%20%20%20account%28id%3A%202046897%29%20%7B%0A%20%20%20%20%20%20names%3A%20nrql%28query%3A%20%22select%20%2A%20from%20Span%20where%20%60entity.guid%60%3D%27MjA0Njg5N3xBUE18QVBQTElDQVRJT058MTA3NTAwNjkwNg%27%20and%20name%20like%20%27%25helloServlet%25%27%20since%20300%20minutes%20ago%22%29%20%7B%0A%20%20%20%20%20%20%20%20results%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20tx%3A%20nrql%28query%3A%20%22select%20%2A%20from%20Transaction%20where%20%60entity.guid%60%3D%27MjA0Njg5N3xBUE18QVBQTElDQVRJT058MTA3NTAwNjkwNg%27%20and%20name%20like%20%27%25WebTransaction%2FServlet%2FhelloServlet%25%27%20since%20300%20minutes%20ago%22%29%20%7B%0A%20%20%20%20%20%20%20%20results%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20spanTraces%3A%20nrql%28query%3A%20%22select%20code.function%20from%20Span%20where%20%60entity.guid%60%3D%27MjA0Njg5N3xBUE18QVBQTElDQVRJT058MTA3NTAwNjkwNg%27%20and%20traceId%3D%27d375319aa6fdbee4f5d7aec273f7bbec%27%20since%20300%20minutes%20ago%22%29%20%7B%0A%20%20%20%20%20%20%20%20results%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A) could age out, i'll add a screenshot of its results below. 

With this Span data below, you can see that the Span name is more accurately describing user code, and the code.namespace property appears to be library code. 

I'm not a java expert, and can't say if it's possible, but in this use case, i believe the user's expectation is that code.namespace would be "com.example.javaeehelloworld.HelloServlet" and "service" would map to `onGet` (if that's even possible). this would allow CodeStream to show a code lens for it in the IDE. there's a screenshot of the user's code file attached here too.

"code.function": "service",
"code.namespace": "jakarta.servlet.http.HttpServlet",
"entity.name": "Glassfish A",
"entityGuid": "MjA0Njg5N3xBUE18QVBQTElDQVRJT058MTA3NTAwNjkwNg",   
"name": "Servlet/com.example.javaeehelloworld.HelloServlet/service",

slack thread: https://newrelic.slack.com/archives/C025T6V8R5X/p1671567123137479

**Comment by deleonenriqueta** [comment]
https://github.com/newrelic/newrelic-java-agent/pull/1329
