### ISSUE TITLE
Test Scala 2.13 PRs

### ISSUE THREAD

**Issue by jodeev** [newrelic/newrelic-java-agent#140]
The outcome of this MMF is to make a decision on whether or not to merge Scala 2.13 PRs.

If we do decide to merge, we will combine a release of the Java agent with a couple other open issues.

Work includes:

- Recover SNAP test that used to be run every release.
- Test junder31 and FIT contributions to determine the coverage, and assess the following:
  - support for Scala 2.13, at parity with Scala 2.12
  - support for latest Netty version
  - support for latest Akka version
  - support for latest Akka HTTP version
  - support for latest Akka HTTP Core version
  - support for latest Play Framework version
- Do performance benchmarking but not tuning.

Aha! Link: https://newrelic.aha.io/features/JAVA-207

**Comment by jasonjkeller** [comment]
PR for scala 2.13 https://github.com/newrelic/newrelic-java-agent/pull/109

FIT instrumentation
- [Netty](https://source.datanerd.us/FIT?utf8=%E2%9C%93&q=Netty&type=&language=)
- [Akka](https://source.datanerd.us/FIT?utf8=%E2%9C%93&q=Akka&type=&language=)
- [Play Framework](https://source.datanerd.us/FIT?utf8=%E2%9C%93&q=Play&type=&language=)

**Comment by tspring** [comment]
This work is finished
