### ISSUE TITLE
Review FIT Scala/Akka/Netty/Play instrumentation

### ISSUE THREAD

**Issue by jasonjkeller** [newrelic/newrelic-java-agent#142]
This issue belongs to the [Test Scala 2.13 PRs Epic](https://github.com/newrelic/newrelic-java-agent/issues/140)

We should investigate the following FIT instrumentation and determine if any of it can be contributed to the agent main branch:

FIT instrumentation
- [Netty](https://source.datanerd.us/FIT?utf8=%E2%9C%93&q=Netty&type=&language=)
- [Akka](https://source.datanerd.us/FIT?utf8=%E2%9C%93&q=Akka&type=&language=)
- [Play Framework](https://source.datanerd.us/FIT?utf8=%E2%9C%93&q=Play&type=&language=)
- [Scala](https://source.datanerd.us/FIT?utf8=%E2%9C%93&q=scala&type=&language=)

**Comment by tspring** [comment]
I took a quick look at FIT instrumentation and there aren't any general purpose solutions to for any of the above frameworks/libraries that aren't already covered by existing builtin agent instrumentation. Calling this done.
