### ISSUE TITLE
OOM on API Key change

### ISSUE THREAD

**Issue by agustiza** [newrelic/newrelic-java-agent#1428]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
[NOTE]: # ( Describe the problem you're encountering. )
Running inside docker containers.

We recently had an API key rotation for the new relic agent on our non productive environments as a way to save costs by disabling monitoring and logging.

We suddenly found out that we were having constant OOMs. Troubleshooting a bit we found out that the culprit was the New Relic Agent.

Sadly I cannot share a reproducible project.

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results
[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

## Steps to Reproduce

Very little I can share but it's pretty standard setup.

``` 
## Dockerfile
RUN wget "http://download.newrelic.com/newrelic/java-agent/newrelic-agent/current/newrelic-java.zip"
RUN unzip newrelic-java.zip -d "/app"

##Bash Script that runs on entrypoint
if [ "$USE_NEW_RELIC" = "true" ]; then
        echo -n "Setting New Relic..."
        if [ -f /run/secrets/newrelic_license_key ]; then
            NEWRELIC_LICENSE_KEY=$(cat /run/secrets/newrelic_license_key)
            NEW_RELIC="-javaagent:/app/newrelic/newrelic.jar"
            NEW_RELIC=$NEW_RELIC" -Dnewrelic.environment="${ENVIRONMENT}
            NEW_RELIC=$NEW_RELIC" -Dnewrelic.config.license_key="${NEWRELIC_LICENSE_KEY}
            NEW_RELIC=$NEW_RELIC" -Dnewrelic.config.app_name="${ENVIRONMENT}_${SERVICE_NAME}
            echo "New Relic set."
        else
            echo "New Relic licence key is not set."
            exit 1
        fi
    fi
```

```
apk add openjdk8
jps #pid 547
jcmd 547 GC.class_histogram | less
/app # jstat -gcutil 547 250 10
  S0     S1     E      O      M     CCS    YGC     YGCT    FGC    FGCT     GCT
  0.00   0.00  99.68  99.99  97.34  95.57 164830 1507.445 113654 254514.054 256021.499
  0.00   0.00 100.00  99.99  97.34  95.57 164830 1507.445 113654 254514.054 256021.499
  0.00   0.00 100.00  99.99  97.34  95.57 164830 1507.445 113654 254514.054 256021.499
  0.00   0.00 100.00  99.99  97.34  95.57 164830 1507.445 113654 254514.054 256021.499
  0.00   0.00 100.00  99.99  97.34  95.57 164830 1507.445 113654 254514.054 256021.499
  0.00   0.00 100.00  99.99  97.34  95.57 164830 1507.445 113654 254514.054 256021.499
  0.00   0.00 100.00  99.99  97.34  95.57 164830 1507.445 113654 254514.054 256021.499
  0.00   0.00 100.00  99.99  97.34  95.57 164830 1507.445 113654 254514.054 256021.499
  0.00   0.00 100.00  99.99  97.34  95.57 164830 1507.445 113654 254514.054 256021.499
  0.00   0.00 100.00  99.99  97.34  95.57 164830 1507.445 113655 254516.281 256023.726
```

![image](https://github.com/newrelic/newrelic-java-agent/assets/7284873/09fe06a5-76a4-40bf-969b-2c6ec5c30e6c)

## Your Environment
Docker container using openjdk:8-jre-alpine openjdk:8-jdk-alpine
Current New Relic Agent version

**Comment by kford-newrelic** [comment]
@agustiza can you confirm : when you did the key rotation, was the new key a valid or invalid key?

**Comment by agustiza** [comment]
I'm not 100% sure but I think it was a purposedly invalid key. 

Should be around 25-26th April 2023.
