### ISSUE TITLE
Review/test proposed Scala 2.13 instrumentation

### ISSUE THREAD

**Issue by jasonjkeller** [newrelic/newrelic-java-agent#143]
This issue belongs to the [Test Scala 2.13 PRs Epic](https://github.com/newrelic/newrelic-java-agent/issues/140)

We have a community submitted PR for Scala 2.13 support: https://github.com/newrelic/newrelic-java-agent/pull/109

We need to review the PR and validate that there are no performance or behavior regressions from our Scala 2.12 instrumentation. 

We should also compare and contrast this instrumentation with modules created by FIT. How does their Scala 2.13 instrumentation compare? Does this instrumentation play nicely with other FIT instrumentation in the ecosystem (Netty, Akka, Play)? See https://github.com/newrelic/newrelic-java-agent/issues/142

**Comment by tspring** [comment]
Performance and functionality of both the scala-2.13 and combined scala and akka-http-core_2.13 work is inline with our existing 2.12. I'm going to call this work done and merge them to main
