### ISSUE TITLE
Remove agent exclusions and run tests (IAST support)

### ISSUE THREAD

**Issue by kford-newrelic** [newrelic/newrelic-java-agent#1447]
### Description
Remove the current agent exclusions referenced in:

- [NR-137973](https://issues.newrelic.com/browse/NR-137973)
- [NR-137989](https://issues.newrelic.com/browse/NR-137989)
- [NR-138138](https://issues.newrelic.com/browse/NR-138138)

And test the agent for proper operation. Do **not** merge until Team discussion/review.

Intention is to support the IAST feature enhancement.

### Acceptance Criteria
Modify, test and report results

### Design Consideration/Limitations
N/A

### Dependencies
N/A

### Additional context
N/A

**Comment by jasonjkeller** [comment]
@kford-newrelic I’ve left a summary of the tests results and my findings on each of the tickets below. 

- [NR-137973](https://issues.newrelic.com/browse/NR-137973) - Exclude `net/sf/saxon.*` 
  - Original issue: https://newrelic.atlassian.net/browse/JAVA-2471
- [NR-137989](https://issues.newrelic.com/browse/NR-137989) - Exclude `java/security/.*`
  -  Original issue: https://newrelic.atlassian.net/browse/JAVA-2544
- [NR-138138](https://issues.newrelic.com/browse/NR-138138) - Exclude `javax/crypto/` 
  - Original issue: https://newrelic.atlassian.net/browse/JAVA-1399

For each of them, I've left a link to the "Original issue" in Jira where I believe the work was initially done to add the excludes. These were all added nearly a decade ago and I can no longer access these Jira tickets, if you are able to then it might help to dig up a bit more context on the origin of the issues that warranted the excludes to be put in place. That said, as part of the summary on each ticket I did leave details what issues can occur if the excludes were to be removed.

---

One approach that was briefly discussed was to only remove the excludes if the security agent is enabled. While that would seem to narrow the scope of the potential problems down to lower level environments that are using IAST, I believe that would only be a short term approach as eventually RASP mode will be introduced to enable the security agent to be run full time in production environments, in which case we would be fully re-introducing all of the problems solved by the excludes.

**Comment by jasonjkeller** [comment]
PR with proposed solution: https://github.com/newrelic/newrelic-java-agent/pull/1453

**Comment by jasonjkeller** [comment]
PR https://github.com/newrelic/newrelic-java-agent/pull/1453 has been merged and will be in the 8.8.0 agent
