### ISSUE TITLE
Java 21 Support

### ISSUE THREAD

**Issue by SentryMan** [newrelic/newrelic-java-agent#1451]
## Is your feature request related to a problem? Please describe.

Might be a little early, but the first Java 21 release candidate is [now available](https://jdk.java.net/21/), so why not start initial testing with it now?

**Comment by SentryMan** [comment]
Java 20 support ended a while ago, and we still can't use NR, do you know when this will be released?

**Comment by meiao** [comment]
The release is scheduled for next week.
