### ISSUE TITLE
Release Request for CVE Fix

### ISSUE THREAD

**Issue by nathanschile** [newrelic/newrelic-java-agent#147]
When is the next release (6.2.2?/6.3?) planned? We are needing the security fix from https://github.com/newrelic/newrelic-java-agent/commit/d42e46c12ffd65ae1ef54755f00b020a4245c4ef Thanks

**Comment by tspring** [comment]
Hi @nathanschile , I can't say for sure as we always do some manual testing before release that may delay things, but we aim to release near the end of each month. Given the upcoming holidays, I'd expect that to be either a little earlier (next week maybe) or the beginning of January. I'll close this, but feel free to reopen if you have any other questions about it. Cheers.
