### ISSUE TITLE
Define log output format

### ISSUE THREAD

**Issue by raphael-afanyan** [newrelic/newrelic-java-agent#1473]
## Is your feature request related to a problem? Please describe.
The New Relic Java Agent log output format is text and thus cannot be used properly in NR logs

## Feature Description
Allow log format configuration with JSON option like [infrastructure agent](https://docs.newrelic.com/docs/infrastructure/install-infrastructure-agent/configuration/infrastructure-agent-configuration-settings/#log-format)

## Priority
Really Want

**Comment by kford-newrelic** [comment]
@raphael-afanyan thank you for this feature request submission!

We've considered the benefits of adding this to our agent and while it's a good suggestion, we've decided against adding this to our planned roadmap.

Thank you again for suggesting this!
