### ISSUE TITLE
Add New Instrumentation for Jedis-5.0.0

### ISSUE THREAD

**Issue by deleonenriqueta** [newrelic/newrelic-java-agent#1475]
### Description
Current instrumentation modules are incompatible with the latest jedis version

**Comment by meiao** [comment]
Weave violations
     ReferenceViolation{type=INVALID_REFERENCE, weaveClass=redis/clients/jedis/Connection, originalClass=redis/clients/jedis/Protocol$Command, violationMessage=missing field. weave code expects field: QUITLredis/clients/jedis/Protocol$Command;}
     WeaveViolation{type=EXPECTED_NEW_FIELD_ANNOTATION, clazz=redis/clients/jedis/JedisPubSub, field=client}
     WeaveViolation{type=METHOD_NEW_CALL_ORIGINAL_UNSUPPORTED, clazz=redis/clients/jedis/JedisPubSub, method=proceed(Lredis/clients/jedis/Connection;[Ljava/lang/String;)V}
     WeaveViolation{type=METHOD_NEW_NON_PRIVATE_UNSUPPORTED, clazz=redis/clients/jedis/JedisPubSub, method=proceed(Lredis/clients/jedis/Connection;[Ljava/lang/String;)V}
     WeaveViolation{type=METHOD_NEW_CALL_ORIGINAL_UNSUPPORTED, clazz=redis/clients/jedis/JedisPubSub, method=proceedWithPatterns(Lredis/clients/jedis/Connection;[Ljava/lang/String;)V}
     WeaveViolation{type=METHOD_NEW_NON_PRIVATE_UNSUPPORTED, clazz=redis/clients/jedis/JedisPubSub, method=proceedWithPatterns(Lredis/clients/jedis/Connection;[Ljava/lang/String;)V}
     WeaveViolation{type=METHOD_NEW_INVOKE_UNSUPPORTED, clazz=redis/clients/jedis/JedisPubSub, method=onMessage(Ljava/lang/String;Ljava/lang/String;)V}
     WeaveViolation{type=METHOD_NEW_CALL_ORIGINAL_UNSUPPORTED, clazz=redis/clients/jedis/JedisPubSub, method=onMessage(Ljava/lang/String;Ljava/lang/String;)V}
     WeaveViolation{type=METHOD_NEW_NON_PRIVATE_UNSUPPORTED, clazz=redis/clients/jedis/JedisPubSub, method=onMessage(Ljava/lang/String;Ljava/lang/String;)V}
     WeaveViolation{type=METHOD_NEW_INVOKE_UNSUPPORTED, clazz=redis/clients/jedis/JedisPubSub, method=onPMessage(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V}
     WeaveViolation{type=METHOD_NEW_CALL_ORIGINAL_UNSUPPORTED, clazz=redis/clients/jedis/JedisPubSub, method=onPMessage(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V}
     WeaveViolation{type=METHOD_NEW_NON_PRIVATE_UNSUPPORTED, clazz=redis/clients/jedis/JedisPubSub, method=onPMessage(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V}
     WeaveViolation{type=METHOD_NEW_INVOKE_UNSUPPORTED, clazz=redis/clients/jedis/JedisPubSub, method=onSubscribe(Ljava/lang/String;I)V}
     WeaveViolation{type=METHOD_NEW_CALL_ORIGINAL_UNSUPPORTED, clazz=redis/clients/jedis/JedisPubSub, method=onSubscribe(Ljava/lang/String;I)V}
     WeaveViolation{type=METHOD_NEW_NON_PRIVATE_UNSUPPORTED, clazz=redis/clients/jedis/JedisPubSub, method=onSubscribe(Ljava/lang/String;I)V}
     WeaveViolation{type=METHOD_NEW_INVOKE_UNSUPPORTED, clazz=redis/clients/jedis/JedisPubSub, method=onUnsubscribe(Ljava/lang/String;I)V}
     WeaveViolation{type=METHOD_NEW_CALL_ORIGINAL_UNSUPPORTED, clazz=redis/clients/jedis/JedisPubSub, method=onUnsubscribe(Ljava/lang/String;I)V}
     WeaveViolation{type=METHOD_NEW_NON_PRIVATE_UNSUPPORTED, clazz=redis/clients/jedis/JedisPubSub, method=onUnsubscribe(Ljava/lang/String;I)V}
     WeaveViolation{type=METHOD_NEW_INVOKE_UNSUPPORTED, clazz=redis/clients/jedis/JedisPubSub, method=onPUnsubscribe(Ljava/lang/String;I)V}
     WeaveViolation{type=METHOD_NEW_CALL_ORIGINAL_UNSUPPORTED, clazz=redis/clients/jedis/JedisPubSub, method=onPUnsubscribe(Ljava/lang/String;I)V}
     WeaveViolation{type=METHOD_NEW_NON_PRIVATE_UNSUPPORTED, clazz=redis/clients/jedis/JedisPubSub, method=onPUnsubscribe(Ljava/lang/String;I)V}
     WeaveViolation{type=METHOD_NEW_INVOKE_UNSUPPORTED, clazz=redis/clients/jedis/JedisPubSub, method=onPSubscribe(Ljava/lang/String;I)V}
     WeaveViolation{type=METHOD_NEW_CALL_ORIGINAL_UNSUPPORTED, clazz=redis/clients/jedis/JedisPubSub, method=onPSubscribe(Ljava/lang/String;I)V}
