### ISSUE TITLE
Java Code Coverage plugin adoption

### ISSUE THREAD

**Issue by kford-newrelic** [newrelic/newrelic-java-agent#1491]
### Description
We have a [New Relic Coverage report plugin](https://source.datanerd.us/commune/newrelic-gradle-plugins/blob/master/docs/plugins/newrelic-coverage-report.md) that feeds a [New Relic Dashboard](https://source.datanerd.us/commune/newrelic-gradle-plugins/blob/master/docs/plugins/newrelic-coverage-report.md) where teams, managers and leads can check the current Unit Test Coverage in an easy and centralized way.

This work request is to make your team’s Java & Kotlin service repositories to report Code Coverage metrics to NR1 by using the [New Relic Coverage Report ](https://source.datanerd.us/commune/newrelic-gradle-plugins/blob/master/docs/plugins/newrelic-coverage-report.md)gradle plugin.

Please follow the [plugin documentation ](https://source.datanerd.us/commune/newrelic-gradle-plugins/blob/master/docs/plugins/newrelic-coverage-report.md)to add the dependency and enable it.

If you have any questions or issues while adding the plugin, please reach out to [Rodrigo Martin](https://issues.newrelic.com/secure/ViewProfile.jspa?name=rmartin)

When creating a work item for your team from this WR create a Feature with [NR-158017](https://issues.newrelic.com/browse/NR-158017) as Parent Epic.

### Acceptance Criteria
Java Agent unit test code coverage data is reported and visible on the central dashboard.

### Design Consideration/Limitations
N/A

### Dependencies
N/A

### Additional context
N/A

**Comment by kanderson250** [comment]
Rodrigo and the testing team clarified that this initiative doesn't apply to us as an agent team, so I'm closing this.
