### ISSUE TITLE
trying to login in webview 

### ISSUE THREAD

**Issue by somesingh95** [newrelic/newrelic-java-agent#1494]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
[NOTE]: 'Error in Navigation!', [Error: Couldn't find a navigation context. Have you wrapped your app with 'NavigationContainer'? See https://reactnavigation.org/docs/getting-started for setup instructions.]
[TIP]:  using login in weview getting error in IOS only , android working fine

## Expected Behavior
[NOTE]: not able to login in webview

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results
[NOTE]: Error in Navigation!', [Error: Couldn't find a navigation context. Have you wrapped your app with 'NavigationContainer'? See https://reactnavigation.org/docs/getting-started for setup instructions.]
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

## Steps to Reproduce
[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )

## Your Environment
[TIP]:     "react-native": "0.69.3",

    "newrelic-react-native-agent": "^1.2.1",

## Additional context
[TIP]:  import NewRelic from 'newrelic-react-native-agent';
import Config from 'react-native-config';

let appToken=Config.NEWRELIC_TOKEN;

const agentConfiguration = {
    
  //Android Specific
  // Optional:Enable or disable collection of event data.
  analyticsEventEnabled: true,

  // Optional:Enable or disable crash reporting.
  crashReportingEnabled: true,

  // Optional:Enable or disable interaction tracing. Trace instrumentation still occurs, but no traces are harvested. This will disable default and custom interactions.
  interactionTracingEnabled: true,

  // Optional:Enable or disable reporting successful HTTP requests to the MobileRequest event type.
  networkRequestEnabled: true,

  // Optional:Enable or disable reporting network and HTTP request errors to the MobileRequestError event type.
  networkErrorRequestEnabled: true,

  // Optional:Enable or disable capture of HTTP response bodies for HTTP error traces, and MobileRequestError events.
  httpRequestBodyCaptureEnabled: true,

 // Optional:Enable or disable agent logging.
  loggingEnabled: true,

  // Optional:Specifies the log level. Omit this field for the default log level.
  // Options include: ERROR (least verbose), WARNING, INFO, VERBOSE, AUDIT (most verbose).
  logLevel: NewRelic.LogLevel.INFO,

  // iOS Specific
  // Optional:Enable/Disable automatic instrumentation of WebViews
  // webViewInstrumentation: true,

  // Optional:Set a specific collector address for sending data. Omit this field for default address.
  // collectorAddress: "",

  // Optional:Set a specific crash collector address for sending crashes. Omit this field for default address.
  // crashCollectorAddress: "",

  // Optional:Enable or disable reporting data using different endpoints for US government clients
  // fedRampEnabled: false
};

NewRelic.startAgent(appToken,agentConfiguration);
NewRelic.setJSAppVersion(version);

**Comment by jtduffy** [comment]
@somesingh95  
This issue belongs to another agent team (maybe iOS?), not the Java agent team.

**Comment by somesingh95** [comment]
@jtduffy any solutions for this?

**Comment by jtduffy** [comment]
You've opened this issue under the wrong team/repository. You will need to open the issue under the correct repository, or contact New Relic support for more assistance.
