### ISSUE TITLE
Docs - Update the Java config page on log_level changes

### ISSUE THREAD

**Issue by kford-newrelic** [newrelic/newrelic-java-agent#1500]
### Description
Need to update the Java Agent [config page](https://docs.newrelic.com/docs/apm/agents/java-agent/configuration/java-agent-configuration-config-file/#cfg-log_level) to point out that the dynamic change for the `log_level` only applies to the agent config file - not changes to either environment variables or system properties.

### Acceptance Criteria
Customers have clarification on situations where the `log_level` can be dynamically changed.

### Design Consideration/Limitations
Consider whether we should expand this to reference what else can be dynamically changed but if that's not practical, limit this to the `log_level`.

### Dependencies
N/A

### Additional context
N/A

**Comment by jasonjkeller** [comment]
https://github.com/newrelic/docs-website/pull/15053

**Comment by jasonjkeller** [comment]
PR merged
