### ISSUE TITLE
Docs - Update Java Agent attributes page for HTTP response

### ISSUE THREAD

**Issue by kford-newrelic** [newrelic/newrelic-java-agent#1501]
### Description
Review the agent attributes [docs](https://docs.newrelic.com/docs/apm/agents/java-agent/configuration/java-agent-configuration-config-file/#cfg-log_level) page and determine whether the HTTP related attributes need to be updated.

### Acceptance Criteria
Docs are reviewed and updated as appropriate.

### Design Consideration/Limitations
N/A

### Dependencies
N/A

### Additional context
Changes have been shipped that have altered the HTTP related attributes populated by the agent and the current documentation may not be up-to-date.

**Comment by jasonjkeller** [comment]
`httpResponseCode` and `httpResponseMessage` should be replaced by `http.statusCode` and `http.statusText`, respectively.

**Comment by jasonjkeller** [comment]
https://github.com/newrelic/docs-website/pull/15050

**Comment by jasonjkeller** [comment]
Changes have been merged
