### ISSUE TITLE
Docs - Review Java Agent SSL page for removal of use_private_ssl config setting

### ISSUE THREAD

**Issue by kford-newrelic** [newrelic/newrelic-java-agent#1502]
### Description
Since the last remaining agent versions that supported the `use_private_ssl config` setting have gone EOL, we should take a look to see if it's appropriate to remove this reference from the docs page.

### Acceptance Criteria
If appropriate to remove the reference, update the docs page accordingly.

### Design Consideration/Limitations
N/A

### Dependencies
N/A

### Additional context
[Prior discussion](https://newrelic.slack.com/archives/G96BPDE4Q/p1671040357694649?thread_ts=1671030210.640789&cid=G96BPDE4Q) on the topic. Check with the team for consensus. If general agreement among the team, let's update and remove.

**Comment by jasonjkeller** [comment]
Conversation [here](https://newrelic.slack.com/archives/G96BPDE4Q/p1698875768531909)

**Comment by jasonjkeller** [comment]
PR to remove config: https://github.com/newrelic/docs-website/pull/15056

**Comment by jasonjkeller** [comment]
PR is merged
