### ISSUE TITLE
Docs - Modify JFR page to remove on by default callout

### ISSUE THREAD

**Issue by kford-newrelic** [newrelic/newrelic-java-agent#1503]
### Description
Docs page to update - https://docs.newrelic.com/docs/apm/agents/java-agent/configuration/java-agent-configuration-config-file/#jfr-real-time-profiling

Need to remove the callout that says that JFR is on by default as of the 7.1.0 release.

### Acceptance Criteria
JFR page no longer erroneously says that JFR is on by default.

### Design Consideration/Limitations
N/A

### Dependencies
N/A

### Additional context
Review the rest of the information on the page to ensure that it's still up-to-date and accurate.

**Comment by jasonjkeller** [comment]
The message in the doc is correct. It accurately states that it is on by default only for version 7.1.0 and that for all other agent versions it needs to be explicitly enabled.

>   Real-time profiling with JFR is on by default in Java agent version 7.1.0. If you are on any other agent version 7.0.0 or higher, you can turn on JFR by changing the value to `true`.
