### ISSUE TITLE
Docs Feedback: Custom JMX YAML examples - possible clarification?

### ISSUE THREAD

**Issue by kford-newrelic** [newrelic/newrelic-java-agent#1509]
### Description
This customer feedback came in through the docs.newrelic.com "Was this doc helpful?" form.

**User comment:** Is it a file apart from the new relic agent config file =?
**Doc link:** https://docs.newrelic.com/docs/apm/agents/java-agent/custom-instrumentation/custom-jmx-yaml-examples/

### Acceptance Criteria
Review the current docs. Can we clarify where/how the JMX YAML is? Eg: is it added as a part of the current agent configuration file? Is it a separate file and if so, does it need to get referenced in the agent config file, etc?

### Design Consideration/Limitations
N/A

### Dependencies
N/A

### Additional context
N/A

**Comment by jasonjkeller** [comment]
We already document this exact info: https://docs.newrelic.com/docs/apm/agents/java-agent/custom-instrumentation/java-agent-custom-jmx-instrumentation-yaml/#file_location
