### ISSUE TITLE
Docs: Add information about the server side toggle of JFR

### ISSUE THREAD

**Issue by kford-newrelic** [newrelic/newrelic-java-agent#1512]
### Description
Review the docs for Java Agent JFR config and determine whether they need to be updated.

Aspects to consider:

- Note that a change to the enabled setting (true/false) does NOT require a restart of the agent
- Explain the new server side configuration option in NR that allows the toggle of JFR without modifying the config file. This setting can be found under Settings > Application and the toggle exists near the bottom of the panel under "Java Flight Recorder" label (screenshot attached)
 
### Acceptance Criteria
If the JFR docs are determined to be out-of-date/not accurate, update them accordingly.

### Design Consideration/Limitations
N/A

### Dependencies
N/A

### Additional context
Existing JFR docs:
https://docs.newrelic.com/docs/apm/agents/java-agent/configuration/java-agent-configuration-config-file/#jfr-real-time-profiling

GH location of mdx doc file:
https://github.com/newrelic/docs-website/blob/develop/src/content/docs/apm/agents/java-agent/configuration/java-agent-configuration-config-file.mdx

**Comment by jasonjkeller** [comment]
https://github.com/newrelic/docs-website/pull/15043

**Comment by jasonjkeller** [comment]
https://github.com/newrelic/docs-website/pull/15045

**Comment by jasonjkeller** [comment]
Both of the doc update PRs have now been merged.
