### ISSUE TITLE
Docs : Improve archived Micrometer repo

### ISSUE THREAD

**Issue by kford-newrelic** [newrelic/newrelic-java-agent#1514]
### Description
Documentation on the archived [Micrometer repo](https://github.com/newrelic/micrometer-registry-newrelic) should be reviewed for possible improvements, which will make it easier for customers to migrate to the recommended OTel solution instead.

Review and consider the following:

- Archived repo `README`. Review to see if we can improve our documentation by linking to our [NR example](https://github.com/open-telemetry/opentelemetry-java-examples/tree/main/micrometer-shim), instead of the generic OTel shim example
- Archived repo `README`. We also identified that the summary UI mentioned - with screenshots - **doesn't work** with the OTel shim. We need to have a clear separation in the doc about what applies to the OTel shim (the top part) and what applies to the archived NR registry (the bottom part)

### Acceptance Criteria
Review the archived repo's `README` and if appropriate, update it to be more accurate/helpful.

### Design Consideration/Limitations
N/A

### Dependencies
N/A

### Additional context
N/A

**Comment by jasonjkeller** [comment]
These changes were put in place a couple of months ago.
