### ISSUE TITLE
Equivalent to OTEL `@WithSpan` annotation

### ISSUE THREAD

**Issue by JesseLaughlin** [newrelic/newrelic-java-agent#1516]
There is an annotation in the OTEL agent called `@WithSpan` that can allows developers to specify which method traces should generate Span events.

https://opentelemetry.io/docs/instrumentation/java/automatic/annotations/

This customer is looking to suppress the creation of Span events for specific method traces.

https://forum.newrelic.com/s/hubtopic/aAX8W000000PHYEWA4/control-over-span-creation

They would like us to implement an equivalent annotation.

Really Want

**Comment by jtduffy** [comment]
This issue would be used to address the problem where `excludeFromTransactionTrace` does not exclude the target method from traces derived from distributed traces.
