### ISSUE TITLE
Scala - IllegalAccessError occurring on some applications

### ISSUE THREAD

**Issue by kford-newrelic** [newrelic/newrelic-java-agent#1592]
### Description
New customer's application causing `java.lang.IllegalAccessError: Update to non-static final field xyz.controllers.RfqRoutes.DoubleNumber attempted from a different method` error to be thrown, preventing the application from starting.

### Acceptance Criteria
Need to identify what causes this type of error to occur and resolve.

### Design Consideration/Limitations
This appears to be similar to #620 and #1069 - which were thought to be resolved with prior agent updates.

### Dependencies
N/A

### Additional context
Customer was able to downgrade to a `6.4.x` agent version, which worked, to resolve the issue.

**Comment by kanderson250** [comment]
A customer provided this [repro app](https://github.com/mattbernst/akka-http-new-relic) for Java 11, Scala 2.12, and NR Agent 7.2+.

**Comment by jtduffy** [comment]
Our advice to customers who run across this error is to upgrade to Scala 2.13. We haven't been able to repro this issue when running v2.13.
