### ISSUE TITLE
Review how the Java Agent handles HTTP responses

### ISSUE THREAD

**Issue by kford-newrelic** [newrelic/newrelic-java-agent#1648]
### Description
The Java Agent _could be_ unnecessarily holding onto HTTP responses, which translates into a larger amount of memory use. Need to investigate this a bit more to determine whether we can avoid this or whether it's a necessary cost.

If we determine that holding onto the response is necessary, we should further investigate a possible optimization by preventing child traces from being generated? Should that be something that we allow to be configurable by customers? What's the impact to the trace in doing this?

### Acceptance Criteria
Need to determine whether the agent _is_ in fact holding onto HTTP responses too long. If yes, then we need to determine whether an optimized solution can be implemented.

### Design Consideration/Limitations
N/A

### Dependencies
N/A

### Additional context
Original Jira issue - [NR-82809](https://new-relic.atlassian.net/browse/NR-82809)

**Comment by kford-newrelic** [comment]
Should be configuration driven

**Comment by jbedell-newrelic** [comment]
Resolved by https://github.com/newrelic/newrelic-java-agent/pull/1775
