### ISSUE TITLE
Investigate null response on httpclient5

### ISSUE THREAD

**Issue by meiao** [newrelic/newrelic-java-agent#1649]
### Description
In some cases, after an async request is made using httpclient5, the call is completed and a null Object is passed as the response.

This causes an NPE when the instrumentation is trying to get the http response code. Further, this prevents a segment from being finished, causing the transaction to appear to have taken 10 minutes (due to segment timeout).

### Acceptance Criteria
Code is guarded to prevent NPE when the response is being read at https://github.com/newrelic/newrelic-java-agent/blob/9f144fd80f85e69fa735c2713cd1bc138337e659/instrumentation/httpclient-5.0/src/main/java/com/nr/agent/instrumentation/httpclient50/InstrumentationUtils.java#L80

Also, end the segment in a finally block.

**Comment by kford-newrelic** [comment]
Additional reference - [NR-214951](https://new-relic.atlassian.net/browse/NR-214951)

**Comment by jbedell-newrelic** [comment]
Resolved by: https://github.com/newrelic/newrelic-java-agent/pull/1719
