### ISSUE TITLE
[Spike] Create spans instead of TTs - discovery and research

### ISSUE THREAD

**Issue by kford-newrelic** [newrelic/newrelic-java-agent#1654]
### Description
Replace agent implementation of Transaction Traces with Spans.

[Initiative Brief](https://docs.google.com/document/d/1Z3cwnr86sRjIrpWAGhipzedgdCZduOBlAFVUirJYTrk/edit?usp=sharing).

### Acceptance Criteria
Discovery spike. Get familiar with the initiative brief and intention for the agent to produce spans instead of transaction traces.

Identify additional work to be done and create appropriate issues reflecting that work.

### Design Consideration/Limitations
N/A

### Dependencies
N/A

### Additional context
Original Jira Issue - [NR-186693](https://new-relic.atlassian.net/browse/NR-186693)
Jira Issue - [NR-187782](https://new-relic.atlassian.net/browse/NR-187782)

[NR-186693]: https://new-relic.atlassian.net/browse/NR-186693?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[NR-187782]: https://new-relic.atlassian.net/browse/NR-187782?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by jasonjkeller** [comment]
I’ve put together a doc to summarize the findings from the Java agent spike. https://docs.google.com/document/d/17CtLrNOCvCPY32uxhm7PC7zDeXCKn1zPjAYyIrXn2J4/edit?usp=sharing

**Comment by jasonjkeller** [comment]
Closing this as a completed spike as summarized by the doc linked above. With the provided info, the path forward lies with product management.
