### ISSUE TITLE
AIM: Add support for Bedrock (AI SDK) instrumentation

### ISSUE THREAD

**Issue by kford-newrelic** [newrelic/newrelic-java-agent#1660]
### Description
Add agent instrumentation support for the Amazon Bedrock (AI) SDK. 

### Acceptance Criteria
TBD

### Design Consideration/Limitations
TBD

### Dependencies
TBD

### Additional context
The Python Team has implemented this. These docs can serve as a starting point for understanding.

Bedrock: [Python Agent Bedrock Instrumentation](https://newrelic.atlassian.net/wiki/spaces/INST/pages/3019702738/Python+Agent+Bedrock+Instrumentation)
User Feedback: [AI Feedback CDD](https://newrelic.atlassian.net/wiki/spaces/AIO11y/pages/3000696867/AI+Feedback+CDD)
Some additional context that might be useful: [Python Agent OpenAI Instrumentation](https://newrelic.atlassian.net/wiki/spaces/INST/pages/2961604827/Python+Agent+OpenAI+Instrumentation)
Instrumentation demo from Node agent (skip to 28:10): https://drive.google.com/file/d/12tRwnb0oEOvp3INYoSSeOXsIYfk2aLtc/view

**Comment by jasonjkeller** [comment]
## SDKs

Amazon Bedrock is part of the AWS SDK for Java. It appears to be supported in AWS SDK for Java, version 2 and to some extent in AWS SDK for Java, version 1. It's not clear exactly how the two versions might differ and if we need to support both.
https://docs.aws.amazon.com/sdk-for-java/

There are two different clients included in the SDK: a synchronous [BedrockRuntimeClient](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/bedrockruntime/BedrockRuntimeClient.html) as well as an asynchronous [BedrockRuntimeAsyncClient](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/bedrockruntime/BedrockRuntimeAsyncClient.html).

Each client supports [InvokeModel](https://docs.aws.amazon.com/bedrock/latest/APIReference/API_runtime_InvokeModel.html) and [InvokeModelWithResponseStream](https://docs.aws.amazon.com/bedrock/latest/APIReference/API_runtime_InvokeModelWithResponseStream.html). For the first iteration of this work our goal is to only support `InvokeModel`.

## Models

Instrument each model and based on the model id, parse out the necessary results, and record `LlmChatCompletionSummary` event and one or more `LlmChatCompletionMessage`.

Models to Support (only text models no image processing (see `LLMs` agent spec)):
- Anthropic Claude
- Amazon Titan
- Meta Llama 2
- Cohere Command
- AI21 Labs Jurassic

Each of these models will have differing request/response structures that will require unique parsing.

## Agent Spec

Draft: https://source.datanerd.us/agents/agent-specs/pull/657

## Agent APIs

The following new agent APIs will be required:
- getLlmMessageIds (see `LLM Message ID API Requirements` agent spec)
- recordLlmFeedbackEvent (see `LLM Feedback Recording API Requirements ` agent spec)

## Metrics/Events/Attributes

See the `LLMs` agent spec for full details on the metrics, events, and attributes that must be generated by the instrumentation. Agents will capture information about embeddings and chat completions and generate multiple LLM events. Metrics will be generated for LLM function calls and to indicate that the instrumentation module applied.

## Configuration

New configuration will be required to enable/disable various `ai_monitoring` features. Some consideration will also need to be given to increasing the `custom_insights.max_samples_stored` default value as LLM events will count towards this limit.

## Testing

This is one of the biggest unknowns currently and will likely be a significant amount of work given the complexity of setup and the number of supported models.

## Documentation

At a minimum we'll need to update the [Java agent config doc](https://docs.newrelic.com/docs/apm/agents/java-agent/configuration/java-agent-configuration-config-file/). It's unclear if any documentation beyond that will be required or if the docs team will be responsible for a general purpose feature doc that applies to all agents.

## Unknowns

There are a number of potential requirement changes being discussed regarding the data generated by the instrumentation that could ultimately require refactoring.

**Comment by jasonjkeller** [comment]
All of the implementation work for this is on https://github.com/newrelic/newrelic-java-agent/tree/aws-bedrock-support
