### ISSUE TITLE
Requesting AWS IMDS every transaction is causing instances to hit their 1024pps limit on ENIs, please impliment cache

### ISSUE THREAD

**Issue by zbintliff** [newrelic/newrelic-java-agent#1676]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
We noticed apps in our cluster were having issues resolving DNS queries. Following [this AWS doc](https://repost.aws/knowledge-center/vpc-find-cause-of-failed-dns-queries) we were able to look at the the `linklocal_allowance_exceeded` and see it was constantly breaking the threshold.  From the same doc it says:

>The linklocal_allowance_exceeded metric indicates the number of packets shaped and dropped due to PPS rate allowance exceeded for local services. Examples of local services are Amazon VPC DNS Service, Instance Metadata Service (IMDS), and Amazon Time Sync Service

We dug into what was causing the packet traffic as the number of DNS requests were relatively low. It appears from [amazon's public IMDS tracer](https://github.com/aws/aws-imds-packet-analyzer) that is is NR making the transactions.  

We dove into the NR code briefly and see that there is no caching on the instance metadata [here](https://github.com/newrelic/newrelic-java-agent/blob/da6c37f6daa10f2ebd54075e54d94bce50b6e6df/newrelic-agent/src/main/java/com/newrelic/agent/utilization/AWS.java#L55), which means it queries the metadata on every transactions. For high throughput application this can hit the limit very quickly! As we run this on a virtualization platform multiple containers can be on the same node expanding the problem.

This information doesn't change, we should please cache it.

## Expected Behavior
This IMDS call should only happen once.

## Steps to Reproduce
[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )

**Comment by zbintliff** [comment]
Actually digging into this more. The request that is spamming hte IMDS is: 
```
 GET /metadata/instance/compute?api-version=2017-03-01
 ```

From the code base this is actually queried by [the Azure discovery](https://github.com/newrelic/newrelic-java-agent/blob/da6c37f6daa10f2ebd54075e54d94bce50b6e6df/newrelic-agent/src/main/java/com/newrelic/agent/utilization/Azure.java#L28)

**Comment by jtduffy** [comment]
I reviewed code paths related to fetching cloud provider information, and found that this data is fetched only under the following circumstances:
- On initial startup of the agent, prior to the first connect cycle to NR
- Anytime the agent gets a "restart" command from the server and the UtilizationService is restarted

https://github.com/newrelic/newrelic-java-agent/blob/da6c37f6daa10f2ebd54075e54d94bce50b6e6df/newrelic-agent/src/main/java/com/newrelic/agent/RPMService.java#L176

https://github.com/newrelic/newrelic-java-agent/blob/da6c37f6daa10f2ebd54075e54d94bce50b6e6df/newrelic-agent/src/main/java/com/newrelic/agent/utilization/UtilizationService.java#L111

@zbintliff  If you still believe that the NR agent is causing excessive traffic by collecting cloud provider data, I encourage you to contact NR support and open a ticket.

**Comment by zbintliff** [comment]
Hey Jerry, definitely still an issue we escalated with NR support. Shared packet captures and IMDS logs showing that its the agent hitting the Azure endpoint constantly. (sending over 1k packets a second)
