### ISSUE TITLE
SlowTransactionManager prints stack trace

### ISSUE THREAD

**Issue by bertdewolf** [newrelic/newrelic-java-agent#1680]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )

The SlowTransactionService prints a stack trace for no reason:
[https://github.com/newrelic/newrelic-java-agent/blob/v8.8.0/newrelic-agent/src/mai[…]elic/agent/service/slowtransactions/SlowTransactionService.java](https://github.com/newrelic/newrelic-java-agent/blob/v8.8.0/newrelic-agent/src/main/java/com/newrelic/agent/service/slowtransactions/SlowTransactionService.java#L199) 

It ends up in our logs and in turn generates alerts.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen. )
No stack trace printed

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results
[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

## Steps to Reproduce
[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )

## Your Environment
[TIP]:  # ( Include as many relevant details about your environment as possible including the running version of New Relic software, JVM vendor and version, framework versions, and any relevant configuration. )
New relic java agent 8.8.0

## Additional context
[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )

**Comment by bertdewolf** [comment]
Thank you for fixing this. Any idea when this will be included in a new release?

**Comment by meiao** [comment]
Sorry, but right now we don't have a date for the next release.
