### ISSUE TITLE
Add support for Apache Pekko

### ISSUE THREAD

**Issue by baukekogelman** [newrelic/newrelic-java-agent#1692]
## Is your feature request related to a problem? Please describe.
Currently our company is using Akka Http for our microservices. Due to a license change for Akka Http we like to migrate existing microservices to Apache Pekko to prevent any license issues with Lightband. See https://www.lightbend.com/akka/license-faq

## Feature Description
APM Support for Apache Pekko

## Describe Alternatives
--

## Additional context
--

## Priority
This is currently blocking to migrate to Pekko.

**Comment by kford-newrelic** [comment]
@baukekogelman thanks for the suggestion - we're going to see if we can add support for Pekko in the next quarter

**Comment by kford-newrelic** [comment]
Duplicate Jira - [NR-149523](https://new-relic.atlassian.net/browse/NR-149523)

**Comment by kanderson250** [comment]
Breaking this into two separate issues:
- First, adding support for the core Pekko Actor library (done, see PR above) 
- Second, adding support for [Pekko HTTP](https://github.com/newrelic/newrelic-java-agent/issues/1816) (added as a second issue, to be worked on next)

Both have been added to the Apache Pekko Milestone: https://github.com/newrelic/newrelic-java-agent/milestone/54
