### ISSUE TITLE
Improved Support For Spring Controller Methods Annotated To Handle Both GET and POST Methods

### ISSUE THREAD

**Issue by kford-newrelic** [newrelic/newrelic-java-agent#1696]
## Is your feature request related to a problem? Please describe.
We've spotted an issue with the Java agent when Controller methods annotated to handle both `GET` and `POST` methods eg:

```
@GetMapping(Value="/Home.html")
@PostMapping(Value="/Home.html")
public string handleHome ( ) {
...
}
```

When the java agent is loaded, the `@GetMapping` annotations are not registered with spring. This works OK when java agent is not loaded.

Currently it looks like the would prioritize processing the PostMapping over the GetMapping, assuming they are using spring 4.3 or later and changing this behavior would be considered a feature request.

## Feature Description
Want the ability to use the Java Agent with controllers that are annotated as both `GET` and `POST` endpoints

## Describe Alternatives
N/A

## Additional context
Original FR - [NR-181683](https://new-relic.atlassian.net/browse/NR-181683)

## Priority
Really Want

**Comment by jtduffy** [comment]
We believe this will be corrected via #1675 
This PR will now fetch the HTTP verb from the request object instead of relying on the order of the `@XXXXMapping` annotations.
