### ISSUE TITLE
JDK versions in Readme do not align with required JDK versions for compilation

### ISSUE THREAD

**Issue by ahornerr** [newrelic/newrelic-java-agent#17]
## Description
The Readme states that JDK 7 and 8 are required to build the agent under `Building > JDK requirements`.
If only JDKs 7 and 8 are in `~/.gradle/gradle.properties` an exception is thrown when trying to perform a Gradle sync.

## Expected Behavior
I expect to be able to Gradle sync and build the agent.

## Steps to Reproduce
With only `jdk7` and `jdk8` in my `~/.gradle/gradle.properties` and running `./gradlew build` I get the following
```
❯ ./gradlew build

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/ahorner/Documents/newrelic/newrelic-java-agent/module_test_10/build.gradle' line: 33

* What went wrong:
A problem occurred evaluating project ':module_test_10'.
> Could not get unknown property 'jdk10' for project ':module_test_10' of type org.gradle.api.Project.
```

Installing JDK 10 and adding it to `~/.gradle/gradle.properties`:
```
❯ ./gradlew build

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/ahorner/Documents/newrelic/newrelic-java-agent/module_test_11/build.gradle' line: 33

* What went wrong:
A problem occurred evaluating project ':module_test_11'.
> Could not get unknown property 'jdk11' for project ':module_test_11' of type org.gradle.api.Project.
```

Installing JDK 11 and adding it to the properties:
```
❯ ./gradlew build

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/ahorner/Documents/newrelic/newrelic-java-agent/module_test_9/build.gradle' line: 33

* What went wrong:
A problem occurred evaluating project ':module_test_9'.
> Could not get unknown property 'jdk9' for project ':module_test_9' of type org.gradle.api.Project.
```

Installing JDK 9 and adding it to the properties file finally dismisses these exceptions.

`~/.gradle/gradle.properties`:
```
jdk7=/Library/Java/JavaVirtualMachines/jdk1.7.0_80.jdk/Contents/Home
jdk8=/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home
jdk9=/Library/Java/JavaVirtualMachines/adoptopenjdk-9.jdk/Contents/Home
jdk10=/Library/Java/JavaVirtualMachines/adoptopenjdk-10.jdk/Contents/Home
jdk11=/Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home
```

## Your Environment
```
❯ echo $JAVA_HOME
/Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home

~
❯ javac --version
javac 11.0.7
```

## Additional context
I would expect the docs to be updated to mention that all 5 JDKs are required, or for only 7 and 8 to be setup. Perhaps the issue is that the build step also runs the JDK-specific testing tasks.

**Comment by jeffalder** [comment]
Oh, I see what's going on. Yeah, this is also a symptom of running gradle with Java 11 -- those projects are only imported if you're running gradle with Java past those versions. We should probably remove those projects and find another way to do it.

Thanks, @ahornerr !

**Comment by breedx-nr** [comment]
@ahornerr @jeffalder I'm not sure what you are suggesting that we do about this.  I could see a couple of approaches, which one do you prefer (if any):

* Update the readme to indicate that you should define all lower jdk versions than the version you are building with
* Update the readme to indicate that JDK1.8+ is required to build 
* Change the build to not include or build the 9/10/11 modules when running with a lower jdk?

**Comment by jeffalder** [comment]
The readme already states that Java 8 is required to build - not Java 8+. Defining Java 9, 10, and 11 was only required because @ahornerr was trying to build with Java 11. So I don't think there's really anything to do here, and this issue can be closed.

Since we require Java 8 to build, it might make sense to remove the module_test directories. They'll only be included for Java 9+, but we explicitly don't support that.

I think the right answer is that module_test_* should be folded into our AITs so we can continue to track agent behavior on module-based code.
