### ISSUE TITLE
Memory Leak due to newly introduced Postgresql Instrument in 8.8 release of New Relic Java Agent

### ISSUE THREAD

**Issue by Maggie552** [newrelic/newrelic-java-agent#1702]
We have encountered a memory leak issue when we began using the [new relic 8.8.0 release agent](https://docs.newrelic.com/docs/release-notes/agent-release-notes/java-release-notes/java-agent-880/) which includes the change 
 > Instrument r2dbc-postgresql 0.9.2 till latest [1413](https://github.com/newrelic/newrelic-java-agent/pull/1556).

## Description
When we began use of the 8.8.0 release of the new relic agent we found that our used heap would gradually increase over 3 days until maximum heap limit was reached and we would have to restart our application. This would happen repeatedly and consistently.

## Expected Behavior
N/A

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results
We diagnosed the issue looking at our new relic dashboard and by analysing heap dumps in Eclipse Memory Analyzer. 

In this screen shot from new relic you can see the used heap (the blue line) gradually increasing towards the maximum heap (the green line).
![MicrosoftTeams-image (6)](https://github.com/newrelic/newrelic-java-agent/assets/60889664/7d7897d2-0d65-4943-8096-8637835ac904)

In this screen shot you can see the results of us analysing our heap dump in Eclipse Memory Analyzer and see that the Leak suspect report points towards a package belonging to new relic in relation to postgreql.

![MicrosoftTeams-image (7)](https://github.com/newrelic/newrelic-java-agent/assets/60889664/474ad817-5148-4022-a450-8ae3ae895c82)

We tied this to the newly introduced postgresql instrument as part of the 8.8.0 release for the new relic agent and disabled the instrument, this has stopped the memory leak. However this means we have lost the functionality of this instrument.
## Steps to Reproduce
Run a java web application with connections to a postgresql db using the reactive client(r2dbc) doing simple selects, with the new relic agent version 8.8.0 monitoring metrics. Perform a heap dump and analyse in Eclipse Memory Analyser, you will find the leak suspect pointing towards class com.newrelic.weave.io.r2dbc.postgresql.client.ReactorNettyClient. 

If you set the NEW_RELIC_CLASS_TRANSFORMER_COM_NEWRELIC_INSTRUMENTATION_R2DBC_POSTGRESQL_0_9_2_ENABLED environment variable to false, you will see the memory leak suspect is no longer seen in heap dumps and the used heap will not increase to the maximum as before.

## Your Environment
New Relic Agent 8.8.0
JDK - Temurin 17

**Comment by ilya40umov** [comment]
I was updating from 8.7.0 to 8.9.0 and ran into really high CPU utilization on our dev environment afterwards. Reverting back to 8.7.0 fixed the problem, and we are actually using r2dbc and coroutines, so I'm suspecting that this CPU utilization was coming from NewRelic agent, and specifically from the new r2dbc instrumentation. For now I'm disabling the new instrumentation and bumping up the agent to 8.9.0 again.

**Comment by kford-newrelic** [comment]
@Maggie552 thank you for alerting us to this issue!

@ilya40umov using the `8.9.0` version of the agent - with the r2dbc instrumentation disabled - did the CPU utilization subside?

**Comment by ilya40umov** [comment]
Yep. We've been running in production on `8.9.0` with the r2dbc instrumentation disabled for a few days now without any noticeable problems.

**Comment by obenkenobi** [comment]
Hey @Maggie552 I created a custom jar that refactors our r2dbc-postgres instrumentation. Please try it in a lower level environment to see if the memory leak has been fixed.

Here is the link to the GHA workflow that contains the artifact that contains the jar: https://github.com/newrelic/newrelic-java-agent/actions/runs/9118230737

I am looking forward to your feedback.

**Comment by sikeeoh** [comment]
Our service also experienced the same issue, but it was resolved by disabling r2dbc instrumentation as stated in the comment.
thank you

**Comment by obenkenobi** [comment]
Created a new snapshot for customers to try out (preferably in a lower environment)

https://github.com/newrelic/newrelic-java-agent/actions/runs/9275332934

**Comment by obenkenobi** [comment]
@ilya40umov @sikeeoh @Maggie552 I have created a snapshot of the agent that may fix the r2dbc module. As recommended, we would prefer you run it in a lower level environment (such as staging) to make sure the memory leak is resolved. 

https://github.com/newrelic/newrelic-java-agent/actions/runs/9276458691

My changes largely involved me refactoring how we get database instance information and making sure we add more exception handling. Please let me know if the snapshot resolves the issue.
