### ISSUE TITLE
Postgres calls are marked as Java methods rather than database calls

### ISSUE THREAD

**Issue by jbedell-newrelic** [newrelic/newrelic-java-agent#1703]
A user was unable to see their Postgres calls because they were happening in a Callable passed to an ExecutorService.  They added the [experimental executor instrumentation](https://github.com/newrelic-experimental/newrelic-java-executors) and were able to see the call, but it showed up as a Java method call rather than a database external call.

Further work was done to verify that the instrumentation was working properly when the postgres call was made synchronously.

We're not sure if the experimental instrumentation is playing a role or not.

**Comment by kford-newrelic** [comment]
Ref - [NR-217624](https://new-relic.atlassian.net/browse/NR-217624)

**Comment by kford-newrelic** [comment]
Additional feedback:

> The custom instrumentation (the [experimental executor instrumentation](https://github.com/newrelic-experimental/newrelic-java-executors)) has been used by quite a few customers without this kind of problem.  They submit a callable to the Executor Service and the DB call is recorded.
> 
> The only thing instrumenting the Postgres call is the agent JDBC instrumentation, which should place a SQLTracer on the method and report it as a DB Call

Will need to repro the issue first, for debugging
