### ISSUE TITLE
Add a 'priority' parameter to Java API `noticeError()`

### ISSUE THREAD

**Issue by kford-newrelic** [newrelic/newrelic-java-agent#1727]
## Is your feature request related to a problem? Please describe.
A customer was hitting a condition where they had control over the initial error handler, but not the part of the framework that set the HTTP status code.  The normal agent error logic dictates that if multiple errors are picked up on the same code path, the last one is reported to New Relic.  However, the error details (like stack trace) were being passed up via their initial call to `noticeError()`.  They wanted to see those details, not the default error picked up by the agent when the status code was set later in the same code path.

## Feature Description
We have customers that would like us to add a `priority` parameter to the Java API `noticeError()` method, allowing them to prioritize which error is reported when there are multiple errors in a single code path. 

## Describe Alternatives
The idea here is that if a customer specifically calls `noticeError()`, in most cases they want to see the error details passed up in that API call.  So they should be able to override the default error logic of the agent and say the equivalent of 'no, report this instead'.  There are probably some conditions where they would not want their call to `noticeError()` to take priority, so a possible solution was to add a parameter called `priority` to the `noticeError()` API call, which accepted either a boolean (if only two priority levels are needed) or an int.  Set `priority` to `true` (or to a high number) and the error will be surfaced over other errors in the same code path.  Set it to `false` (or a low number), and the agent's normal error prioritization rules will take precedence.

## Additional context
Not sure how feasible this is, but it seemed like a good idea.

Original Jira - [NR-137142](https://new-relic.atlassian.net/browse/NR-137142)

## Priority
Really Want

**Comment by jasonjkeller** [comment]
I left some similar advice as Andre on the original ticket: https://new-relic.atlassian.net/browse/NR-137142?focusedCommentId=639080

The noticeError APIs are standardized across agents and defined in agent specs, we would want to reach consensus across agent teams for any changes to the API.

**Comment by kford-newrelic** [comment]
Desired functionality can already be achieved as mentioned above. Closing without further action.
