### ISSUE TITLE
Instrument Glassfish 8.0.0

### ISSUE THREAD

**Issue by meiao** [newrelic/newrelic-java-agent#1731]
### Description
The `verifyInstrumentation` failed for Glassfish 8.0.0-M2. This likely indicates that it will not apply to Glassfish 8.0.0.

### Acceptance Criteria
The agent works with Glassfish 8.0.0.

**Comment by kford-newrelic** [comment]
We'll hold until the next milestone to see if the instrumentation is still broken or not.

**Comment by meiao** [comment]
Superseded by https://github.com/newrelic/newrelic-java-agent/issues/1806
