### ISSUE TITLE
AIM: Enhance Linking Metadata API

### ISSUE THREAD

**Issue by jasonjkeller** [newrelic/newrelic-java-agent#1737]
# Enhance Linking Metadata API

Our [linking metadata API](https://source.datanerd.us/agents/agent-specs/blob/main/APIs/linking.md) (i.e. `NewRelic.getAgent().getLinkingMetadata()`) currently returns an opaque map with a limited number of attributes in it.

We want to make a few enhancements to this API.
- Add the `transaction.id` as an attribute returned in the map by the API
- Possible add `account` as an attribute as well???
- Add a new API method that returns the linking metadata as an encoded + serialized  (base64 / JSON) payload, instead of a map
- Add a new API method that can decode the serialized (base64 / JSON) payload

https://github.com/newrelic/newrelic-java-agent/blob/main/newrelic-agent/src/main/java/com/newrelic/agent/AgentLinkingMetadata.java

**Comment by jbedell-newrelic** [comment]
This work is no longer needed, and thus no longer planned.  Closing this.
