### ISSUE TITLE
Unable to Send Events to New Relic Within Spring Boot Application Threads

### ISSUE THREAD

**Issue by rutaks** [newrelic/newrelic-java-agent#1740]
## Description
When attempting to send events to New Relic from within a separate thread in our Spring Boot application, the events are not being successfully reported. The following code snippet illustrates the problem:

```java
new Thread(
       () -> {
            NewRelic.addCustomParameter("error.code", errorCode);
            NewRelic.addCustomParameter("error.cause", errorCause);
            NewRelic.addCustomParameter("error.component", component);
            NewRelic.addCustomParameter("error.message", errorMessage);
            NewRelic.noticeError(e);
       }
).start();
```

Maven Dependency use:
```xml
        <dependency>
            <groupId>com.newrelic.agent.java</groupId>
            <artifactId>newrelic-api</artifactId>
            <version>8.7.0</version>
        </dependency>
```

## Expected Behavior
We expect that events sent to New Relic within a separate thread should be successfully reported and visible in the New Relic dashboard, similar to events sent from the main thread.

Note: When run the code snippet outside of a new thread, the event is received without any issues

## Steps to Reproduce
Trigger an error condition within the application.
Attempt to report the error to New Relic from within a separate thread using the provided code snippet.

## Your Environment
Spring Boot version: 2.2.4.RELEASE
New Relic agent version: 8.7.0
Java version: 1.8.0_202
OS: Mac OS 14.1 (23B74) - Mac M1 `This has occurred on other OS such as CentOS

**Comment by rutaks** [comment]
This works, thanks @meiao. Also noticed that using the `@Trace(dispatcher = true)`  annotation can be another alternative as seen [here](https://docs.newrelic.com/docs/apm/agents/java-agent/async-instrumentation/java-agent-api-asynchronous-applications/#use-gettoken)

**Comment by meiao** [comment]
Indeed, `@Trace(dispatcher = true)` also works. But it will create a different transaction if you don't link a token someplace during the call of the method.

Also, `@Trace(async = true)` is optimized for when you are going to link a token.
