### ISSUE TITLE
Transactions details missing after version upgrade

### ISSUE THREAD

**Issue by rombernardino** [newrelic/newrelic-java-agent#1773]
After doing some deps bump, the web transaction details are not available anymore. Before upgrading we knew from which endpoint the transaction was coming from and now it is all assigned as `NettyDispatcher`.

![image](https://github.com/newrelic/newrelic-java-agent/assets/22652294/d2654dab-77f6-46b5-845f-cef40e9eea32)

I tried to wrap the `@RequestBody` with `Mono<>` as [described here](https://github.com/newrelic/newrelic-java-agent/tree/main/instrumentation/spring-webflux-6.1.0) but it still didn't work.

The upgrades that have affected are Spring Boot from `3.1.4` to `3.2.3` and the agent from `8.7.0` to `8.9.1`. Also, due to compatibility with Spring Boot version, I had to upgrade Spring Cloud Dependencies from `2022.0.3` to `2023.0.0`. If I rollback to the previous versions, the transactions details start to show up again.

Could this be an incompatibility between the current versions of Spring Boot and the agent?

**Comment by meiao** [comment]
Webflux 6.1.x is not supported at this time by the agent.
We just finished work on it (#1619). It will be in the next release. Scheduled to late March

**Comment by jtduffy** [comment]
@rombernardino This should be corrected via the new [Webflux 6.1 instrumentation modules](https://github.com/newrelic/newrelic-java-agent/pull/1761) that will be introduced in the next version of the agent, currently scheduled for around March 28th.
