### ISSUE TITLE
Change connect host in `Hostname.determineAddress()` to `collector.newrelic.com`

### ISSUE THREAD

**Issue by jtduffy** [newrelic/newrelic-java-agent#1787]
When determining the application's IP address, we currently do a `socket.connect(Inet6Address.getByName("newrelic.com"), 10002)`. This shows traffic to the `newrelic.com` address, even though this isn't called out as a possible agent endpoint in the docs. Changing this to `collector.newrelic.com` will make our current docs correct.

https://github.com/newrelic/newrelic-java-agent/blob/4bfe27a522fc236a415a459374bbb1c3e226ab94/newrelic-agent/src/main/java/com/newrelic/agent/config/Hostname.java#L117

**Comment by deleonenriqueta** [comment]
Issue resolved with PR #1788
