### ISSUE TITLE
AWS DynamoDB instrumentation reports 2 externals

### ISSUE THREAD

**Issue by meiao** [newrelic/newrelic-java-agent#1793]
Description
The DynamoDB SDK uses an HTTP library to query the server.

The instrumentation module for DynamoDB reports a datastore external whenever it does a request. And the instrumentation for the HTTP library will also report an external, resulting in 2 externals for each DynamoDB request.

![image](https://github.com/newrelic/newrelic-java-agent/assets/292463/94215189-40c6-482a-b98b-d653aa57a555)

In the image, the span named `DynamoDB customers describeTable` is the external created by the DynamoDB instrumentation
And the span named `dynamodb.us-east-1.amazonaws.com - CommonsHttp/execute` is the one created by the HTTP library.

Acceptance Criteria
Each request to DynamoDB should only report one external.

Design Consideration/Limitations
One possible solution is to make the DynamoDB tracer a leaf. This way the HTTP instrumentation will not report an external.

**Comment by jbedell-newrelic** [comment]
Resolved by: https://github.com/newrelic/newrelic-java-agent/pull/1827
