### ISSUE TITLE
Add transaction guid to the intrinsics object of the TracedError payload regardless of DT setting

### ISSUE THREAD

**Issue by jtduffy** [newrelic/newrelic-java-agent#1803]
Per the updated [agent spec](https://source.datanerd.us/agents/agent-specs/blob/f1fadba677d6e9f31bf9b7025dd832a8cb0267fe/Errors.md#traced-errors), the transaction GUID must be included in the intrinsics object of the TracedError JSON payload, regardless of the DT setting.

This [line](https://github.com/newrelic/newrelic-java-agent/blob/9aee916959b3d3f15dcc3d794827e3d7dcdebadf/newrelic-agent/src/main/java/com/newrelic/agent/errors/ErrorServiceImpl.java#L468) currently restricts the addition of the transaction GUID based on DT being enabled.

**Comment by kmudduluru** [comment]
we need to verify that guid is available in both TransactionError  Event and ErrorTrace json events  regardles of DT setting (on/off) .

**Comment by kford-newrelic** [comment]
@jtduffy let's capture the end-to-end test results [here](https://docs.google.com/document/d/1E-YNzUGPI8k6BvMvDU3YhgXb0SY3mGxyn3sQoj21VPw/edit#heading=h.44upugl2nmpg)
