### ISSUE TITLE
Add support for Java 22

### ISSUE THREAD

**Issue by jasonjkeller** [newrelic/newrelic-java-agent#1805]
[Java 22](https://blogs.oracle.com/java/post/the-arrival-of-java-22) was released on March 19th, 2024. We should add OOTB support for it.

The full process for supporting a new Java runtime is detailed here:
https://docs.google.com/document/d/1HNY01nQOoVrz45u6pa2Ky1B48m4g0Upr/edit#heading=h.gjdgxs

Here's an example of the work that was done to add support for Java 21: https://github.com/newrelic/newrelic-java-agent/pull/1546

**Comment by SentryMan** [comment]
I also require this
