### ISSUE TITLE
Customer hit CVE on our snakeyaml-1.26 dependency

### ISSUE THREAD

**Issue by tbradellis** [newrelic/newrelic-java-agent#181]
Update snakeyaml to latest to resolve:
 Denial of Service (DoS)	[,1.26)	Not available	19 Dec, 2019
https://snyk.io/vuln/maven:org.yaml%3Asnakeyaml

## Expected Behavior
No change in behavior

## Steps to Reproduce
scan for snakeyaml

**Comment by tbradellis** [comment]
pr incoming

**Comment by tbradellis** [comment]
https://github.com/newrelic/newrelic-java-agent/pull/182

**Comment by tspring** [comment]
Thanks @tbradellis !
