### ISSUE TITLE
Create a ZIO (1/2) public docs feature page

### ISSUE THREAD

**Issue by kford-newrelic** [newrelic/newrelic-java-agent#1810]
### Description
Create a feature page highlighting the Java Agent support for the ZIO (1/2) frameworks (similar to what exists already with the agent's [Scala Akka HTTP instrumentation](https://docs.newrelic.com/docs/apm/agents/java-agent/frameworks/scala-akka-http-core/)).

Need to include general information about what gets instrumented, along with info about available APIs and code fragments/examples on how to use those APIs

### Acceptance Criteria
New public docs feature page introduced with guidance for customers on how to use our agent with ZIO (may want to get guidance from the Docs Team on the location of the page in the navbar, etc)

### Design Consideration/Limitations
N/A

### Dependencies
If we have this feature page available at the time the next release notes are published, we should link from it to this page. Otherwise, when this feature page becomes available, we should update the release notes to point to this feature page.

### Additional context
N/A

**Comment by obenkenobi** [comment]
Related [PR](https://github.com/newrelic/docs-website/pull/16713) merged
