### ISSUE TITLE
Correct the "Update the Java Agent" instructions

### ISSUE THREAD

**Issue by kford-newrelic** [newrelic/newrelic-java-agent#1824]
### Description
The current [documentation](https://docs.newrelic.com/docs/apm/agents/java-agent/installation/update-java-agent/) for updating the Java Agent are incorrect. `Step 3` references extracting the `newrelic-api-.jar` file but for customers that are using the API artifact, they will get this by updating their dependencies.

### Acceptance Criteria

- Modify `Step 3` to remove the reference to the `newrelic-api.jar` file
- Add a new step to reference the `newrelic-api.jar` file and that customers would need to update their dependencies (should we explicitly reference Maven?)
- Closely review the remaining content on the page - any other updates or clarifications should be included?

### Design Consideration/Limitations
N/A

### Dependencies
N/A

### Additional context
N/A

**Comment by obenkenobi** [comment]
I believe referencing maven may be best.
