### ISSUE TITLE
Investigate relationship data that can be emitted from apps that use AWS_MQ_BROKER with RabbitMQ

### ISSUE THREAD

**Issue by kford-newrelic** [newrelic/newrelic-java-agent#1832]
### Description
Trying to reduce the entity relationship data gaps when APM applications use AWS services. Need to explore what entity relationship data can be captured and emitted from the agent when `AWS_MQ_BROKER` with RabbtMQ is in use.

### Acceptance Criteria
Research spike.

### Design Consideration/Limitations
Try to capture the ARN in some way if possible but if not, other data - eg: host, port, etc - might be useable for building entity relationships.

### Dependencies
N/A

### Additional context
Once the available data is better understood, we need to flesh out the details of additional work needed to get that into the agent and documented.

**Comment by obenkenobi** [comment]
AWS MQ is both RabbitMQ and ActiveMQ compatible. Thus the following needs to be investigated:

Rabbit MQ:
  - The RabbitMQ's AMQP client instrumentation (of which we already instrument)
  - RabbitMQ's management api
 Active MQ:
  - The AMQP client 
  - The MQTTP client
  - Apps using STOMP (depends on Spring's web-socket api)
  - ActiveMQ's management api

Doc for using JMS with active MQ as it describes each possible client for ActiveMQ: https://docs.aws.amazon.com/amazon-mq/latest/developer-guide/amazon-mq-working-java-example.html

**Comment by obenkenobi** [comment]
[Link](https://github.com/orgs/newrelic/projects/87/views/1?pane=issue&itemId=61150787) to the Active MQ Ticket for AWS MQ
