### ISSUE TITLE
Remove security certificates and log warning from use_private_ssl config 

### ISSUE THREAD

**Issue by XiXiaPdx** [newrelic/newrelic-java-agent#186]
## Description

The Java Agent currently bundles SSL certificates into the agent. The applicate can decide to use those certificates for the agent to talk to the NR collector.  It is done by setting `use_private_ssl` config to true for the agent config.

## Expected Behavior

The Java Agent will not have any SSL certificates included in the agent. The Java agent will rely on the certificates in the trust store of the application app server.  

The application server could also configure the agent to look for SSL certificates at a custom certificate bundle path - `ca_bundle_path`  

`use_private_ssl` would now log a warning that the agent no longer has certificates. 

## Additional context
[The public docs on SSL config for the Java Agent](https://docs.newrelic.com/docs/agents/java-agent/configuration/configuring-your-ssl-certificates)

**Comment by tspring** [comment]
@XiXiaPdx This looks like a duplicate of #178

**Comment by XiXiaPdx** [comment]
Ohhh, there it is. You are right
