### ISSUE TITLE
Add GHA workflow to build and upload init containers to Docker Hub

### ISSUE THREAD

**Issue by kford-newrelic** [newrelic/newrelic-java-agent#1860]
### Description
As part of the k8s agent operator work, each agent needs to create a GHA workflow in https://github.com/newrelic/newrelic-agent-init-container-releases that builds and uploads init containers to Docker Hub whenever there is a new agent version released.

Note docker containers will also need to be generated for all previous agent versions that will still be supported as of the end of Q1 2024.

The Python agent team will create a GHA workflow first that does this and each agent can copy modify it for their own agent.

### Acceptance Criteria
Implementation of an appropriate new GHA workflow.

### Design Consideration/Limitations
N/A

### Dependencies
N/A

### Additional context
N/A

**Comment by jasonjkeller** [comment]
The work in https://source.datanerd.us/aws-lambda/auto-layer-releases/pull/8 will automate the publishing of images for each new agent release. The Dockerfile here https://github.com/newrelic/newrelic-agent-init-container-releases/blob/main/src/java/Dockerfile is what will be executed to build each image.

**Comment by jasonjkeller** [comment]
Resolved by https://github.com/newrelic/newrelic-agent-init-container-releases/pull/16
