### ISSUE TITLE
Discrepancy between number of JVMs listed from JFR and JVMs page

### ISSUE THREAD

**Issue by obenkenobi** [newrelic/newrelic-java-agent#1864]
When turning on JFR (i.e. realtime profiling) in the java agent for multiple apps, the number of JVMs listed is not the same. 

It may be related to how in the JVM page we report the host name plus port while in JFR we report the host name and IP address.

### How to possibly replicate it:

1. Create a docker image with 2 java apps running on different ports running on the Java Agent and with the same configuration settings.
2. Create multiple docker containers with the same image.
3. Check the New Relic UI for discrepancies in the number of JVMs.

**Comment by deleonenriqueta** [comment]
Resolved with [PR 1928](https://github.com/newrelic/newrelic-java-agent/pull/1928)
