### ISSUE TITLE
Capture Docker ID from AWS ECS Fargate

### ISSUE THREAD

**Issue by jbedell-newrelic** [newrelic/newrelic-java-agent#1904]
Existing code does not work in this case.

Details here: https://source.datanerd.us/agents/agent-specs/pull/676

Research spike - [NR-262877](https://new-relic.atlassian.net/browse/NR-262877)
Original FR - [NR-262320](https://new-relic.atlassian.net/browse/NR-262320)

[NR-262877]: https://new-relic.atlassian.net/browse/NR-262877?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[NR-262320]: https://new-relic.atlassian.net/browse/NR-262320?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by jtduffy** [comment]
This has been put on pause until we can get a customer to try out a snapshot build.
