### ISSUE TITLE
Improve container ID reporting for AWS ECS & Fargate containers

### ISSUE THREAD

**Issue by kford-newrelic** [newrelic/newrelic-java-agent#1914]
### Description
TBD

### Acceptance Criteria
TBD

### Design Consideration/Limitations
TBD

### Dependencies
TBD

### Additional context
TBD

**Comment by jtduffy** [comment]
@kford-newrelic   I think this is a dup of #1904 ?

**Comment by kford-newrelic** [comment]
Yup. Closing as a dupe of #1904
