### ISSUE TITLE
[Spike] Add support for Java 23

### ISSUE THREAD

**Issue by kford-newrelic** [newrelic/newrelic-java-agent#1933]
### Description
Java 23 is expected to GA sometime during September 2024 ([Oracle roadmap](https://www.oracle.com/java/technologies/java-se-support-roadmap.html)), so the intention is that we take a look at early access releases, update and test the Java Agent with them to determine what - if anything - breaks, then fix any breakage.

### Acceptance Criteria
Research spike. Explore the early access releases, then potentially create new issues representing break-fix.

### Design Consideration/Limitations
Should consider running a performance test.

### Dependencies
Exact GA date is TBD; should keep an eye out for availability of any early access releases.

### Additional context
N/A

**Comment by meiao** [comment]
New branch has been created that tests the agent with an early access branch of Java 23.
https://github.com/newrelic/newrelic-java-agent/tree/java-23

There were no incompatibilities found, but a test had problems.
The error is related to ActiveMQ Artemis not being compatible with Java 23.
https://issues.apache.org/jira/browse/ARTEMIS-4975
