### ISSUE TITLE
[Spike] Explore agent operation with Tomcat 11

### ISSUE THREAD

**Issue by kford-newrelic** [newrelic/newrelic-java-agent#1934]
### Description
Tomcat 11 is still in alpha (milestone) releases. Instrumentation verifier passes successfully but to proactively ensure that the agent continues to work as expected with Tomcat 11, we should explicitly explore and test it, to determine if there is any significant breakage or not. If there's breakage, additional issues should be created for break-fix.

### Acceptance Criteria
Research spike. Initial manual testing OK but then we should explore whether to create an AIT or not.

### Design Consideration/Limitations
Since there will likely be numerous milestone releases before GA, is it possible to design an AIT that will download/test whatever the latest release is, instead of fixing to a specific milestone release?

### Dependencies
N/A

### Additional context
N/A

**Comment by jbedell-newrelic** [comment]
Testing went well with the preview releases.  If nothing big changes, the agent should support this as-is.
