### ISSUE TITLE
[Spike] Explore Spring / Spring WebFlux / Spring Boot releases

### ISSUE THREAD

**Issue by kford-newrelic** [newrelic/newrelic-java-agent#1936]
### Description
Spring releases new minor/major versions every six months (May & Nov). We want to be sure that our agent continues to function as expected with any already released versions and we want to proactively be aware of any coming new releases that we need to keep an eye on.

- Review recent releases for Spring / Spring WebFlux / Spring Boot for awareness
- Review any coming release plans
- Review existing agent tests to determine limits of what's being tested. Should we introduce new tests?

### Acceptance Criteria
Research spike. Determine whether we have sufficient tests in place or need additional and create new issues for that work as needed.

### Design Consideration/Limitations
N/A

### Dependencies
N/A

### Additional context
N/A

**Comment by jtduffy** [comment]
Latest Spring Boot version: 3.3.2 - [Released](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.3-Release-Notes) on/around May 23, 2024
- Uses Spring 6.1.11
- The @ServletEndpoint, @ControllerEndpoint and @RestControllerEndpoint annotations for declaring Actuator endpoints have been deprecated (no effect on our instrumentation)
    Instead, applications should use: 
    https://docs.spring.io/spring-boot/reference/actuator/endpoints.html#actuator.endpoints.implementing-custom
  
- All verification tasks pass for Spring 6.1.11
- Spring pet client reports up normally, clean logs
- Spring webflux app reports up normally, clean logs

Two tickets opened: #2008  #2007
