### ISSUE TITLE
Netty Http2 instrumentation can throw an NPE

### ISSUE THREAD

**Issue by jbedell-newrelic** [newrelic/newrelic-java-agent#1947]
Related GTSE: https://new-relic.atlassian.net/jira/software/c/projects/NR/boards/289?selectedIssue=NR-280663

The following line in Http2RequestWrapper can throw an NPE (and thus reporting an invalid error up) when the method is null:
`httpRequest = HttpConversionUtil.toHttpRequest(msg.stream().id(), msg.headers(), true)`

Error message is: `method header cannot be null in conversion to HTTP/1.x`

We need to understand when/why the method can be null and what to do in that case.

**Comment by jasonjkeller** [comment]
The Netty classes weaved to support HTTP/2 have been refactored which resulted in the removal of the weave class that was causing the NPE.
