### ISSUE TITLE
Missing artifact for newrelic-scala-api for Scala 3

### ISSUE THREAD

**Issue by soujiro32167** [newrelic/newrelic-java-agent#1958]
Missing artifact for newrelic-scala-api for Scala 3. 
Specifically `com.newrelic.agent.java % newrelic-scala-api_3 % 8.12.0`

[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

Looking at [Scala 3 API](https://github.com/newrelic/newrelic-java-agent/blob/main/newrelic-scala3-api/src/main/scala/com/newrelic/scala/api/TraceOps.scala), I'd expect a published artifact.

However, its missing from [Maven](https://mvnrepository.com/artifact/com.newrelic.agent.java/newrelic-scala-api), where the 2.x artifacts are published

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen. )

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results
[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

## Steps to Reproduce
[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )

## Your Environment
[TIP]:  # ( Include as many relevant details about your environment as possible including the running version of New Relic software, JVM vendor and version, framework versions, and any relevant configuration. )

## Additional context
[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )

**Comment by soujiro32167** [comment]
Thanks for fixing this!
Not major obstacle, we were able to consume the 2.13 artifact in scala 3, and so far it worked 🤞

**Comment by kanderson250** [comment]
Hi @soujiro32167 , just a heads up that the Scala 3 artifact is now available on Maven Central: https://central.sonatype.com/artifact/com.newrelic.agent.java/newrelic-scala-api_3
