### ISSUE TITLE
netty-reactor instrumentation leaks Token on cancellation

### ISSUE THREAD

**Issue by chringwer** [newrelic/newrelic-java-agent#1970]
## Description
After upgrading the NR java agent to 8.12.0 we observed much higher GC pressure than before. Investigating some heap dumps revealed an issue with the reactor-netty instrumentation module which seems to not handle cancellations properly in some cases so that tokens are not expired timely.

In particular `FluxMapFuseable_Instrumentation` needs to expire the token when cancelled which is a pretty common scenario for example when doing `.flatMap(...).next()`. `LambdaSubscriber_Instrumentation` and `LambdaMonoSubscriber_Instrumentation` should handle `dispose()` and expire their tokens accordingly, I guess.

For us, patching `FluxMapFuseable_Instrumentation` with a `cancel()` implementation resolved the memory issues:

``` 
    @Weave(type = MatchType.ExactClass, originalName = "reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber")
    static final class MapFuseableSubscriber_Instrumentation<T, R> {
     ...
        public void cancel() {
            if (token != null) {
                token.linkAndExpire();
                token = null;
            }
            Weaver.callOriginal();
        }
     ...
    }
```

## Expected Behavior
Cancelling an instrumented publisher should not leak any objects 

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results
[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

## Steps to Reproduce
[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )

## Your Environment
[TIP]:  # ( Include as many relevant details about your environment as possible including the running version of New Relic software, JVM vendor and version, framework versions, and any relevant configuration. )
Java 17, NR agent 8.12.0

## Additional context
[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )

**Comment by jbedell-newrelic** [comment]
HI @chringwer , thanks for the report.  I'm having a little trouble reproducing the issue for testing.  Is there any chance you have a quick repro app?  Or perhaps a more detailed code example?

**Comment by jbedell-newrelic** [comment]
Thanks @chringwer for the bug report.  The fix should be in the next release.  (Note: It didn't quite make it into last week's release.)
