### ISSUE TITLE
Upload 8.13.0 to maven repository

### ISSUE THREAD

**Issue by AldinDuraki** [newrelic/newrelic-java-agent#1975]
Can you please provide the newest 8.13.0 version to the maven repository? Only 8.12.0 is available there. Thanks!

**Comment by jtduffy** [comment]
Hi @AldinDuraki 
Version 8.13 was released yesterday and is now available in [maven central](https://central.sonatype.com/artifact/com.newrelic.agent.java/newrelic-agent/versions).  

[Release notes](https://github.com/newrelic/newrelic-java-agent/releases/tag/v8.13.0)
