### ISSUE TITLE
Spring Data Redis

### ISSUE THREAD

**Issue by tspring** [newrelic/newrelic-java-agent#199]
Instrumentation for [reactive lettuce](https://github.com/lettuce-io/lettuce-core/wiki/Reactive-API-%285.0%29)

**Comment by XiXiaPdx** [comment]
Start point to understand the api and samples 
https://spring.io/projects/spring-data-redis

**Comment by kford-newrelic** [comment]
May ultimately be covered by #317

**Comment by kford-newrelic** [comment]
Duplicate of #317 - closing
