### ISSUE TITLE
Java 23 compatibility

### ISSUE THREAD

**Issue by meiao** [newrelic/newrelic-java-agent#2005]
## Feature Description
Make the agent compatible with Java 23.

## Additional context
The [java-23 branch](https://github.com/newrelic/newrelic-java-agent/tree/java-23) contains most of the changes needed for Java 23 compatibility. But it is using early access releases of Java 23 to run the tests.

So before merging this branch, the references to early access (ea) must be removed and the tests must be run with the GA release of Java 23.

**Comment by jasonjkeller** [comment]
Java 23 GA was released yesterday (9/17) but so far it looks like only Oracle binaries are available.
https://openjdk.org/projects/jdk/23/#
