### ISSUE TITLE
Support for mongodb-driver-sync driver

### ISSUE THREAD

**Issue by kford-newrelic** [newrelic/newrelic-java-agent#2034]
## Is your feature request related to a problem? Please describe.
Customer is missing mongodb calls for sync calls and is looking for visibility.

## Feature Description
Customer desires to have mongodb instrumentation OOTB.

## Describe Alternatives
N/A

## Additional context
While this specific request is for sync calls, during initial spiking we should get a sense for what support for async calls there are and what the potential effort to support those could look like.

## Priority
Please help us better understand this feature request by choosing a priority from the following options: 
[Really Want]

**Comment by meiao** [comment]
Starting on 3.7.0 MongoDB has started releasing its artifact as `org.mongodb:mongo-java-driver`, while still releasing it with the old name `org.mongodb:mongodb-driver-sync`. They stopped releasing the old name with version 4.0.

Our tests verify that the instrumentation applies to the old artifact name, and manually testing shows that the current instrumentation should apply to the new artifact.

**Comment by jtduffy** [comment]
Verified current instrumentation correctly applies to the latest Mongodb sync driver.
