### ISSUE TITLE
Fix Verify Instrumentation failure Slack notification

### ISSUE THREAD

**Issue by meiao** [newrelic/newrelic-java-agent#2046]
### Description
There has been failures on Verify Instrumentation workflows when it tries to notify the team's Slack channel of a failure.
This started happening at least since August 15.

https://github.com/newrelic/newrelic-java-agent/actions/runs/10769078897/job/29862913716#step:2:14

### Acceptance Criteria
Failure messages are sent to the Slack channel.

**Comment by meiao** [comment]
If possible, move the workflow to a different file, but make the PR with the bot.

**Comment by jasonjkeller** [comment]
I created a new [webhook](https://slack.com/help/articles/360041352714-Build-a-workflow--Create-a-workflow-that-starts-outside-of-Slack) to notify us in slack when the verifier fails, updated the `SLACK_WEBHOOK_URL` secret, and verified that it is working.
