### ISSUE TITLE
Investigate Handling of Persistent HTTP/2 Connections in Netty Instrumentation

### ISSUE THREAD

**Issue by deleonenriqueta** [newrelic/newrelic-java-agent#2054]
### Description

Investigate how `netty-4.1.16` instrumentation handles persistent HTTP/2 connections and explore potential ways to manage transactions that remain open for extended periods of time. 

![open-connection](https://github.com/user-attachments/assets/13bde8bb-731a-45fe-afa6-cbde91c673c5)

#### Details Related to Reproducing
- Java Agent 8.14.0
- Micronaut
- Kotlin

**Comment by kford-newrelic** [comment]
Asked customer for a repro🤞🏽

**Comment by kanderson250** [comment]
slack thread for context: https://newrelic.slack.com/archives/C0NUYPJKA/p1726158353718389

**Comment by obenkenobi** [comment]
The conclusion of this spike is that Micronaut's HTTP/2 client is triggering the same code that starts HTTP/2 transactions inside netty. The rest of the work with netty will be tracked by this ticket: https://github.com/newrelic/newrelic-java-agent/issues/2106
