### ISSUE TITLE
Update name Segment

### ISSUE THREAD

**Issue by RafaelCavazza** [newrelic/newrelic-java-agent#213]
Is there a way to update the name of a segment after it is built?

**Comment by tspring** [comment]
Hi @RafaelCavazza would [setMetricName(String)](https://newrelic.github.io/java-agent-api/javadoc/com/newrelic/api/agent/Segment.html#setMetricName(java.lang.String...)) do what you're looking for?

**Comment by RafaelCavazza** [comment]
Hi @tspring !
The doc says that this method will update the metric name. 

I would like to override the value that is set int the `Segment startSegment​(java.lang.String segmentName)` method.

Are the segmentName and metricName the same?

**Comment by kford-newrelic** [comment]
@RafaelCavazza thanks for the suggested enhancement! Unfortunately, we have limited engineering capacity and this wasn't selected for our roadmap. If you or any member of our community is interested in submitting a PR for this, we'd be happy to review it!
