### ISSUE TITLE
[Instil] Validate Scala 2.13 experience for OTel & NR agent

### ISSUE THREAD

**Issue by jodeev** [newrelic/newrelic-java-agent#223]
Benchmark the Scala instrumentation currently provided by the OTel Java agent .vs NR's Java agent. Determine whether the OTel agent can be considered for certain Scala use cases.

**Comment by GDownes** [comment]
Attempted to assign

**Comment by jodeev** [comment]
Comment added by Kevyn Ford in Aha! - [View](https://newrelic.aha.io/comments/6950754897826149013)

Per discussions with Ben Evans, this is no longer relevant. OTel agent does not have the required feature set yet.

**Comment by kford-newrelic** [comment]
Benchmarking completed and demo'ed in a recent team meeting. OTel Java agent instrumentation is _less_ comprehensive than NR's Java agent at the current time.
