### ISSUE TITLE
[Instil] Close selected Scala/Akka/Play gaps

### ISSUE THREAD

**Issue by jodeev** [newrelic/newrelic-java-agent#224]

**Comment by jodeev** [comment]
Comment added by Kevyn Ford in Aha! - [View](https://newrelic.aha.io/comments/6951062371457080048)

Vendor (Instil) has begun submitting PRs supporting enhanced instrumentation for Scala. PR review has not yet started but the expectation is that the vendor will complete this portion of the engagement in April.

**Comment by jodeev** [comment]
Comment added by Kevyn Ford in Aha! - [View](https://newrelic.aha.io/comments/6958097294926803777)

Enhanced instrumentation will be included in the upcoming 7.0.0 agent release.

**Comment by kford-newrelic** [comment]
Implemented as part of the 7.0 and 7.1 releases.
