### ISSUE TITLE
Update http Response code attribute names

### ISSUE THREAD

**Issue by jodeev** [newrelic/newrelic-java-agent#225]
<p style="text-align:start;">Implement the last piece of <a href="https://newrelic.atlassian.net/browse/AGENTS-201">AGENTS-201: Span Event Improvements</a>.</p><p style="text-align:left;">Add the following Span attributes on external spans, with the http response code for each external call made:</p><ul>
<li><p><code>http.statusCode</code></p></li>
<li><p><code>http.statusText</code></p></li>
</ul><p style="text-align:start;">These attributes should be added when using any supported http client. These attributes should also be applied to the root span.</p><p style="text-align:left;">The above attributes will be replacing the following <i>deprecated</i> attributes:</p><ul>
<li><p><code>http.responseCode</code></p></li>
<li><p><code>response.status</code></p></li>
<li><p><code>response.statusMessage</code></p></li>
</ul><p><br></p><p> <code>http.statusCode</code>  and <code>http.statusText</code>  attribute names should also be added to transactions, and old attribute names deprecated.</p><p style="text-align:start;"><br></p><p style="text-align:start;"><b>Engineering notes:</b></p><ul>
<li><p>Have to modify HttpParameters to accept a shim that might have status code.</p></li>
<li><p>Opportunistic: Redesign HttpParameters entirely; shim it in the API implementation so that the agent code only has to deal with one non-deprecated version.</p></li>
</ul><p><br></p><p><b>Acceptance criteria</b></p><ul>
<li><p>Conform to <a href="https://source.datanerd.us/agents/agent-specs/blob/master/Span-Events.md#http"><u><span style="color:#1155CC;">agent spec for attribute naming, specifically pay attention to http.statusCode and http.statusText, and make sure that this has been implemented on spans</span></u></a></p></li>
<li><p>Attribute name of <code>http.statusCode</code> and <code>http.statusText</code> on spans needs to match the attribute name on transactions</p></li>
</ul><p><br></p><p><b>Notes</b></p><p>Release notes examples: <a href="https://docs.newrelic.com/docs/release-notes/agent-release-notes/php-release-notes/php-agent-960255">https://docs.newrelic.com/docs/release-notes/agent-release-notes/php-release-notes/php-agent-960255</a></p>

Aha! Link: https://newrelic.aha.io/features/JAVA-260

**Comment by jasonjkeller** [comment]
When a transaction ends it processes the transaction and notifies its listeners:

`TransactionService.doProcessTransaction` > `listener.dispatcherTransactionFinished` (where the listener is `SpanEventsServiceImpl`) 

From there the `SpanEventsServiceImpl` processes each `Tracer` in the `Transaction` and creates a `SpanEvent` for each:

`SpanEventsServiceImpl.storeSafely` > `createAndStoreSpanEvent` > `tracerToSpanEvent.createSpanEvent`

**Comment by jodeev** [comment]
Comment added by Kevyn Ford in Aha! - [View](https://newrelic.aha.io/comments/6951063513075482923)

Engineering work in progress. Team review of design approach held and agreement on path forward reached.

**Comment by jodeev** [comment]
Comment added by Kevyn Ford in Aha! - [View](https://newrelic.aha.io/comments/6958097445801999267)

Will be included in the upcoming 7.0.0 agent release.

**Comment by jodeev** [comment]
Comment added by Kevyn Ford in Aha! - [View](https://newrelic.aha.io/comments/6959244244238727703)

Issues found during integration testing. Need to re-open for additional engineering work.

Due to priority focus on Virtuoso, pushing this out to June.
