### ISSUE TITLE
Async thread handling - Java agent .vs Open Telemetry

### ISSUE THREAD

**Issue by kford-newrelic** [newrelic/newrelic-java-agent#240]
Related to customer feedback around async thread time not being captured by the current agent.

We have an [test application](https://github.com/kittylyst/example-async) that can be used to illustrate the problem.

Want to first run the test application with the Java agent, to confirm on how the issue presents to customers.

Then want to run the test application using Open Telemetry, to compare and contrast how the instrumentation presents to customers.

Additional discussion around the issue will occur after that.

Must have, suggested by @jodeev

**Comment by jasonjkeller** [comment]
@kittylyst Can you grant access to the Java agent team to the linked sample app?

**Comment by jodeev** [comment]
more context is in this [document](https://docs.google.com/document/d/1mUOMfHNEGzDHI-scPeL8aubMv-Vh_Kc46VKPL6bBL0g/edit)

@kittylyst can provide access to the repo

**Comment by kford-newrelic** [comment]
Moving this to done - screenshots captured, etc. OTel agent not yet at the point where it can instrument these scenarios.
