### ISSUE TITLE
NewRelic fails to link transaction in Spring WebClient (reactor-netty) threads handling an error

### ISSUE THREAD

**Issue by veklov** [newrelic/newrelic-java-agent#242]
## Description
https://github.com/veklov/newrelic-reactor-instrumentation-issue

The above project demonstrates that NewRelic fails to link transactions in Spring WebClient (reactor-netty) threads handling an error. This happens only when WebClient is used within Spring WebFlux application. Standalone WebClient (reactor-netty) works just fine.

1. In the project folder execute
```
./mvnw.cmd download:wget spring-boot:run -Dnewrelic.config.license_key=<a key>
```

2. Then open http://localhost:8080/success in your browser, and you will see NewRelic distributed transaction id in server logs 
```
2021-03-13 17:11:11.220 [reactor-http-nio-2       ] [INFO ] [2251bfbf90efadaf8c56dbfd07043201] [c.n.r.DemoController] - in /success handler
2021-03-13 17:11:11.785 [reactor-http-nio-4       ] [INFO ] [2251bfbf90efadaf8c56dbfd07043201] [c.n.r.DemoController] - in doOnSuccess
```

3. Then open http://localhost:8080/error in your browser, and you will see that NewRelic distributed transaction id disappears
```
2021-03-13 17:11:22.457 [reactor-http-nio-7       ] [INFO ] [3569c2fae1491ccf1e84cb49460d5b43] [c.n.r.DemoController] - in /error handler
2021-03-13 17:11:22.529 [reactor-http-nio-7       ] [WARN ] [] [r.netty.http.client.HttpClientConnect] - [id: 0x54edef77, L:/192.168.1.5:53099 - R:www.google.com/64.233.161.104:80] The connection observed an error
io.netty.handler.timeout.ReadTimeoutException: null
2021-03-13 17:11:22.537 [reactor-http-nio-7       ] [INFO ] [] [c.n.r.DemoController] - in doOnError
2021-03-13 17:11:22.545 [reactor-http-nio-7       ] [ERROR] [] [o.s.b.a.w.r.e.AbstractErrorWebExceptionHandler] - [c9e0145d-8]  500 Server Error for HTTP GET "/error"
io.netty.handler.timeout.ReadTimeoutException: null
```

The error is triggerd by setting a small read timeout:
```
    @GetMapping("/error")
    public Mono<ResponseEntity<String>> error() {
        log.info("in /error handler");
        return clientWith10MsTimeout.get()
                .uri("http://www.google.com")
                .retrieve()
                .bodyToMono(String.class)
                .map(s -> ResponseEntity.ok()
                        .contentType(MediaType.TEXT_HTML)
                        .body(s))
                .doOnError(e -> log.info("in doOnError"));
    }

    @GetMapping("/success")
    public Mono<ResponseEntity<String>> success() {
        log.info("in /success handler");
        return client.get()
                .uri("http://www.google.com")
                .retrieve()
                .bodyToMono(String.class)
                .map(s -> ResponseEntity.ok()
                        .contentType(MediaType.TEXT_HTML)
                        .body(s))
                .doOnSuccess(s -> log.info("in doOnSuccess"));
    }
```

(migrate to Jira)

**Comment by veklov** [comment]
@tspring Hi, this issue is difficult to reproduce in unit test as it seem to be an integration issue. From the agent "token_debug" logs it looks like @Trace(async=true) + token.link(), which happens in the token lifter's onError, does not work for some reason

**Comment by veklov** [comment]
@tspring Hi, after additional debugging I have discovered that @Trace annotation works only if it is applied in a class being instrumented. It does not work on the auxiliary classes that come with the agent. At least InstrumentationImpl.createTracer is not called for the auxiliary classes. As the result, below annotations are no-op and token linking does not work:
https://github.com/newrelic/newrelic-java-agent/blob/910144d887c9e44824779c2e80fff5446443b1da/instrumentation/netty-reactor-0.9.0/src/main/java/com/nr/instrumentation/reactor/netty/TokenLinkingSubscriber.java#L59-L76

**Comment by kford-newrelic** [comment]
Not selected for next quarter's agent roadmap. Will consider for a future agent release.

**Comment by obenkenobi** [comment]
@veklov We recently created a custom snapshot of the agent that that fixes the bug. Please test it and verify it works as intended. 

Snapshot Link:
[https://github.com/newrelic/newrelic-java-agent/actions/runs/3790021989](https://github.com/newrelic/newrelic-java-agent/actions/runs/3790021989)

**Comment by obenkenobi** [comment]
> @veklov We recently created a custom snapshot of the agent that that fixes the bug. Please test it and verify it works as intended.
> 
> Snapshot Link: https://github.com/newrelic/newrelic-java-agent/actions/runs/3790021989

If you notice this log statement:

```
2022-12-27 16:26:42.256 [reactor-http-nio-4       ] [WARN ] [] [r.netty.http.client.HttpClientConnect] - [id: 0x8261116f, L:/192.168.1.140:52185 - R:www.duckduckgo.com/52.149.246.39:80] The connection observed an error
io.netty.handler.timeout.ReadTimeoutException: null
```

Our fix does not capture the transaction there as it is simply internal logging run within reactor-netty that webclient triggers during a timeout. Webflux does get the transaction ID though when logging an error. It does not affect our ability to capture transactions within reactive code itself. So you can still use custom tracing or even capture other metrics via the other reactive libraries and frameworks we use.
