### ISSUE TITLE
Add support for AWS SDK 2 DynamoDB sync/async clients 

### ISSUE THREAD

**Issue by jasonjkeller** [newrelic/newrelic-java-agent#246]
The existing AWS SDK 1 [DynamoDB instrumentation](https://github.com/newrelic/newrelic-java-agent/tree/main/instrumentation/aws-java-sdk-dynamodb-1.11.106) no longer works with the release of AWS SDK 2 due to package changes and possibly code differences as well.

We should add a new instrumentation module to support DynamoDB AWS SDK 2. 
https://github.com/aws/aws-sdk-java-v2/tree/master/services/dynamodb

Aha! Link: https://newrelic.aha.io/features/JAVA-244

**Comment by kford-newrelic** [comment]
Comment added by Kevyn Ford in Aha! - [View](https://newrelic.aha.io/comments/6980666454093299362)

Early access release provided to customer. Feedback was that additional instrumentation for async client class is requested. Will need additional engineering on this MMF.

**Comment by kford-newrelic** [comment]
Comment added by Kevyn Ford in Aha! - [View](https://newrelic.aha.io/comments/6987836400143693280)

Engineering work completed. Expect that this support will be included in the next release (likely to be sometime in Aug)

**Comment by kford-newrelic** [comment]
Comment added by Kevyn Ford in Aha! - [View](https://newrelic.aha.io/comments/6997927962242243772)

Target date for next agent release still being planned but will be moved to September

**Comment by kford-newrelic** [comment]
Comment added by Kevyn Ford in Aha! - [View](https://newrelic.aha.io/comments/7007500114571710176)

Included as part of the 7.2.0 agent release
