### ISSUE TITLE
Support new Jetty 11 release

### ISSUE THREAD

**Issue by jodeev** [newrelic/newrelic-java-agent#253]
Jetty 11 is being released, see [https://newsroom.eclipse.org/news/announcements/eclipse-foundation%E2%80%99s-eclipse-jetty-project-prepares-future-jetty-11-release ](https://newsroom.eclipse.org/news/announcements/eclipse-foundation%E2%80%99s-eclipse-jetty-project-prepares-future-jetty-11-release)

Need to assess impact and make any necessary modifications to support the new release.

Aha! Link: https://newrelic.aha.io/features/JAVA-270

**Comment by kford-newrelic** [comment]
Deferring to the next quarter (Jul-Sep)

**Comment by Stephan202** [comment]
(Jetty 11 will likely see a large uptick in adoption by Q4, following the planned [Spring 6 release with Jakarta EE 9+ support](https://spring.io/blog/2021/09/02/a-java-17-and-jakarta-ee-9-baseline-for-spring-framework-6).)

**Comment by kford-newrelic** [comment]
Migrated to Jira as https://issues.newrelic.com/browse/NR-2453
