### ISSUE TITLE
Connection pool exhaustion can occur during long network outages and the agent doesn't recover

### ISSUE THREAD

**Issue by jasonjkeller** [newrelic/newrelic-java-agent#256]
This is closely related to a previous issue: https://github.com/newrelic/newrelic-java-agent/issues/24

> In rare cases it is possible for the agent to encounter a `ConnectionPoolTimeoutException` when a thread requests a connection to one of the backend agent endpoints.

> In the case where two threads make a request to the connection manager at the same time, one will successfully obtain the lone connection and the other will wait for the connection to become available again. For both threads a 120 second timeout will begin ticking down, for the the thread that has the connection to complete its request and for the thread waiting for a connection to obtain one from the pool. If the thread with the connection times out (`java.net.SocketTimeoutException`) the connection will be released back to the pool but the thread waiting for a connection will also have timed out (`com.newrelic.agent.deps.org.apache.http.conn.ConnectionPoolTimeoutException`).

In the previous issue a [fix was put in to increase the timeout when waiting for a connection](https://github.com/newrelic/newrelic-java-agent/pull/25). With the current timeout a request would have to wait for over 4 minutes for a connection from the pool before a `ConnectionPoolTimeoutException` would occur, which is a pretty exceptional circumstance. 

Regardless, the agent should be able to gracefully recover from such exceptional circumstances rather than getting stuck in an inoperable state. We will need to investigate this further.

**Comment by stevemorard** [comment]
Have you made any progress on this issue or when do you plan to fix it ?

Thank in advance!

**Comment by GDownes** [comment]
Tested ConnectionPoolTimeoutException scenarios. Agent recovers from standard ConnectionPoolTimeoutException.  Found possible Null Pointer Exception that may prevent agent from recovering. Addressed Null Pointer Exception.

**Comment by kford-newrelic** [comment]
Not able to replicate this situation exactly but added additional null pointer exception handling via #637 . Included in the agent `7.5.0` release.
