### ISSUE TITLE
Consider Caffeine for Caching to Replace Guava After EOL of Java 7 Support

### ISSUE THREAD

**Issue by tbradellis** [newrelic/newrelic-java-agent#258]
## Feature/Problem
Replace our Guava dependency with [Caffeine](https://github.com/ben-manes/caffeine) 
We, not infrequently (support ticket searchable with thread dumps), run into deadlocks originating from guava caching.
Remediation is generally to disable the instrumentation point.

## Feature Description
We use guava 28.2-android in order to Support Java 7.  Java 7 support is scheduled for EOL soon. https://github.com/newrelic/newrelic-java-agent/issues/220

Caffeine requires 1.8+ https://github.com/ben-manes/caffeine/issues/51

We should consider switching dependencies once Java 7 Support is EOL.

The guava maintainers even recommend switching to caffeine for caching.
https://github.com/google/guava/issues/3700#issuecomment-553998148

Many more examples:
- https://github.com/google/guava/issues/3972#issuecomment-662999556
- https://github.com/google/guava/issues/3700#issuecomment-553998148
- https://github.com/google/guava/issues/3667#issuecomment-546069244
- https://github.com/google/guava/issues/3602#issuecomment-530912005
- https://github.com/google/guava/issues/3506#issuecomment-519646977
- https://github.com/google/guava/issues/3427#issuecomment-519647443
- https://github.com/google/guava/issues/1854#issuecomment-519652987
- https://github.com/google/guava/issues/971#issuecomment-515039600

## Describe Alternatives
Continue using guava and disable instrumentation points as needed when issues arise.
Use some other caching library besides caffeine or guava for caching weave extensions

## Priority
Nice to Have, for some this could be a MUST Have issue if key instrumentation is lost when disabling modules to workaround a deadlock.

**Comment by Stephan202** [comment]
@tbradellis since we discussed this topic in a private support ticket I decided to have a look at what would be involved. The result is #286. Would be nice if a New Relic engineer could schedule some time for a look :)
