### ISSUE TITLE
akka-http-2.4.5 instrumentation doesn't apply when using Scala 2.13.x

### ISSUE THREAD

**Issue by jasonjkeller** [newrelic/newrelic-java-agent#260]
When using Scala 2.13.x the `akka-http-2.4.5` instrumentation doesn't apply due to this weave violation:

```
2021-03-25T13:43:37,490+0000 [1 24] com.newrelic FINEST: com.newrelic.instrumentation.akka-http-2.4.5 - 1 violations against classloader jdk.internal.loader.ClassLoaders$AppClassLoader@73d16e93
2021-03-25T13:43:37,490+0000 [1 24] com.newrelic FINEST: WeaveViolation: MISSING_ORIGINAL_BYTECODE
2021-03-25T13:43:37,490+0000 [1 24] com.newrelic FINEST: 		Class: scala/collection/immutable/StringOps
2021-03-25T13:43:37,490+0000 [1 24] com.newrelic FINEST: 		Reason: Could not find original bytecode
```

The result is that any transactions that are normally started by the Java agent from this instrumentation when `akka.http.scaladsl.server.ContextWrapper.apply(AkkaHttpContextFunction.scala)` is executed will not exist if using Scala 2.13.x.

The reason that the instrumentation no longer applies is due to refactoring where `scala/collection/immutable/StringOps` was refactored in Scala `v2.13.0-M4` and now is found in [scala/collection/StringOps](https://github.com/scala/scala/blob/2.13.x/src/library/scala/collection/StringOps.scala).

The [StringOps](https://github.com/scala/scala/blob/v2.13.0-M3/src/library/scala/collection/immutable/StringOps.scala#L15-L21) class wraps the scala implementation of `java.lang.String` which is `scala.Predef.String`. It appears that some magic happens behind the scenes where scala `String`s are implicitly converted into instances of the `StringOps` class. 

You can see the differences documented here:
* Scala 2.12: https://github.com/scala/scala/blob/2.12.x/src/library/scala/Predef.scala#L132-L138 
* Scala 2.13: https://github.com/scala/scala/blob/2.13.x/src/library/scala/Predef.scala#L139-L147 

We'll need to build a new version of the instrumentation from the Scala 2.13 dependency.

**Comment by jasonjkeller** [comment]
I’ve got a branch here that modifies the v6.4.2 agent branch and adds a new instrumentation module named `akka-http-2.13_2.4.5` that should apply when using scala 2.13. It needs to be tested and cleaned up a bit before we can get it into an agent release.

https://github.com/newrelic/newrelic-java-agent/compare/v6.4.2...akka-http-2.13_2.4.5

**Comment by BoopBoopBeepBoop** [comment]
Note that scala convention for jar naming would place the scala major version after an underscore

`${name}_${scalaVersion}-${version}-${tag}`  
ex: `server_2.13-0.3.241`
