### ISSUE TITLE
Smoke test that JFR Service is running and sending data

### ISSUE THREAD

**Issue by XiXiaPdx** [newrelic/newrelic-java-agent#265]
We should add a smoke test that verifies the Java Agent does send JFR Data when it configured to be enabled. 

AITS:  

Currently, there is no mock Collector in the AITS for the endpoints that the Telemetry SDK sends data to. So to build this smoke test in the AITs, this new collector would need to be made.  Look to the mock trace span observer built for Infinite Tracing for inspiration. 

Agent logs:

JFR writes to Agent Logs and Debug mode for JFR logs can be enabled. There are distinct success messages that are generated. Could an AIT be made and the assertion is by parsing the log file for these success messages?

This is for this milestone - https://github.com/newrelic/newrelic-jfr-core/milestone/5

**Comment by kford-newrelic** [comment]
De-prioritized. Won't be added to the agent roadmap.
