### ISSUE TITLE
GraphQL for Java - Research Spike

### ISSUE THREAD

**Issue by jodeev** [newrelic/newrelic-java-agent#267]
Provide similar experience for GraphQL that was done for the Node Apollo. See [https://blog.newrelic.com/product-news/apollo-server-plugin/](https://blog.newrelic.com/product-news/apollo-server-plugin/)  
  
  
... for this Java graphql library:

[https://www.graphql-java.com/tutorials/getting-started-with-spring-boot/](https://www.graphql-java.com/tutorials/getting-started-with-spring-boot/)

For MVP:

- transaction naming is "deepest path" of query

Aha! Link: https://newrelic.aha.io/features/JAVA-221

**Comment by jodeev** [comment]
Comment added by Kevyn Ford in Aha! - [View](https://newrelic.aha.io/comments/6951067450213021772)

This appears to be an ad hoc customer (Chegg) escalation

**Comment by jodeev** [comment]
Comment added by Kevyn Ford in Aha! - [View](https://newrelic.aha.io/comments/6955827058516072928)

FIT team is already working with the customer to develop a custom weave package to meet their immediate needs. Agent team will review this in the future and discuss with architects whether there is a product enhancement to be considered here.

**Comment by kford-newrelic** [comment]
Comment added by Kevyn Ford in Aha! - [View](https://newrelic.aha.io/comments/6990796603997527187)

Research spike completed. Approach to implementation understood as well as how to implement to desired transaction naming.
