### ISSUE TITLE
Agent debug logging should work when configured via environment variable or the agent yaml

### ISSUE THREAD

**Issue by jasonjkeller** [newrelic/newrelic-java-agent#277]
The agent provides a debug logging system property (`-Dnewrelic.debug=true`) that, when combined with `log_level: finest`, logs a ton of useful diagnostic info about weaved classes, network/ssl activity, `WeaveViolation`s, etc.

Currently the debug setting can only be set via system property. 

It should also be configurable via the agent yaml:

```
common:
  debug: true
```

and environment variable:

```
NEW_RELIC_DEBUG=true
```

Debug logging is valuable for troubleshooting and thus it should be as easy to set as possible.

**Comment by kford-newrelic** [comment]
Migrated to Jira (https://issues.newrelic.com/browse/NR-24554). Targeted for next quarter's agent roadmap.
