### ISSUE TITLE
Prototype Instrumentation of Async Unscoped External Calls

### ISSUE THREAD

**Issue by jodeev** [newrelic/newrelic-java-agent#284]

**Comment by jodeev** [comment]
Comment added by Kevyn Ford in Aha! - [View](https://newrelic.aha.io/comments/6958809030863539447)

Moved from May start to June to ensure no impact to either JFR data optimization or Virtuoso persistence initiatives. Will convey to field sales team.

**Comment by kford-newrelic** [comment]
Completed. Results of prototyping reviewed internally. No product enhancement will be done as a result of this.
