### ISSUE TITLE
[Instil] Scala Instrumentation XML Configuration and API Build Support

### ISSUE THREAD

**Issue by jodeev** [newrelic/newrelic-java-agent#292]
**XML Configuration**
Provide customers additional instrumentation flexibility without writing code, through use of the agent XML configuration feature. The XML configuration would enable to the user to instrument anonymous functions or methods with a specified return type belonging to a specific class without needing to make updates to the code. For customers with separate Ops/Dev teams, this would be highly desirable, since an Ops team will be able to instrument code without a new release/code updates.

**API Build Support**
To provide customers with more customizable instrumentation options, a new API artifact will be produced that they can then add to their application custom instrumentation. This requires that there be multiple jar file versions corresponding to the specific Scala version they are using, since there is no binary compatibility across versions. This will allow the user to be using Scala 2.11, 2.12 or 2.13 so a finished API would need to be created for each version.

Aha! Link: https://newrelic.aha.io/features/JAVA-281

**Comment by kford-newrelic** [comment]
Comment added by Kevyn Ford in Aha! - [View](https://newrelic.aha.io/comments/6968837546329128663)

Engineering work completed - PRs will be merged in after the 7.0 release is published.

**Comment by kford-newrelic** [comment]
Implemented as part of the 7.1 release.
