### ISSUE TITLE
Update jdbc-mariaDB-1.3.0 instrumentation

### ISSUE THREAD

**Issue by XiXiaPdx** [newrelic/newrelic-java-agent#293]
## Is your feature request related to a problem? Please describe.
jdbc-mariaDB-1.3.0 instrumentation fails against  org.mariadb.jdbc:mariadb-java-client:3.0.0-alpha

It fails because 3.0.0-alpha has two `connect()` metho

https://github.com/mariadb-corporation/mariadb-connector-j/blob/60d535247e3b1fcd7c67a1456d2cef68dd850039/src/main/java/org/mariadb/jdbc/Driver.java#L32-L65d signatures in Driver.java.  1.3.0 to 2.7.2 only has one. 

## Feature Description
Once 3.0.0 settles, see if instrumentation needs to be updated to support. 

## Describe Alternatives
Capped instrumentation verification of jdbc-mariaDb-1.3.0 to  2.7.2, last version before 3.0.0-alpha.

**Comment by kford-newrelic** [comment]
Not selected for the agent roadmap.
