### ISSUE TITLE
Java 11 HTTP Library Support

### ISSUE THREAD

**Issue by jodeev** [newrelic/newrelic-java-agent#302]
ATL: https://newrelic.atlassian.net/browse/GTSE-8716

Customer needs Java 11 HTTP library support, this is blocking their ability to use traces as the library is not supported and they have to manually add.

From the customer :
So not every request through Gateway reaches Layout-manager service, this is a multi-tenant application, so it might happen to, for example, make a request to another application, so in this case, the request will go through Gateway and then reaches the other application.

What I gave you, is just a simple example (methods). My concern is that whenever I make a request to Layout-manager service I don't see the same Trace ID within Gateway and Layout-manager service.

**Comment by kford-newrelic** [comment]
Customer was provided an early access build to try out the new instrumentation; do not see a response on the support ticket.
