### ISSUE TITLE
Update compatibility document

### ISSUE THREAD

**Issue by meiao** [newrelic/newrelic-java-agent#304]
## Description
Update supported versions of Tomcat to: `from 7.0.0 to 9.0.x`.
Update supported versions of TomEE to: `from 1.5.0 to 8.0.x`
Update supported versions of Jersey to: `from 1.0.1 to 2.x`

**Comment by tbradellis** [comment]
@meiao did your findings have any implications for TomEE?

**Comment by meiao** [comment]
@tbradellis it will affect TomEE starting with version 9, when they start using the jakarta package.
https://tomee.apache.org/download.html
