### ISSUE TITLE
noticeError -  update javadocs, last error wins instead of first

### ISSUE THREAD

**Issue by XiXiaPdx** [newrelic/newrelic-java-agent#305]
Todo: 

1.  Update noticeError() javadocs. 
https://docs.newrelic.com/docs/agents/java-agent/api-guides/guide-using-java-agent-api/

2. Update public docs for another config
`ignoreErrorPriority: false`

Context:

[The docs](https://docs.newrelic.com/docs/agents/java-agent/api-guides/guide-using-java-agent-api/) (search for "the first call to noticeError wins") and [javadocs](https://newrelic.github.io/java-agent-api/javadoc/com/newrelic/api/agent/NewRelic.html#noticeError(java.lang.String)) state that the last error reported in a transaction wins.  This is the correct behavior.  The Javadocs still say first error wins.

Old slack conversation about this discrepancy with the docs and how to switch this behavior with a config setting.  

https://newrelic.slack.com/archives/G96BPDE4Q/p1585583512173900

To switch this behavior,  so first noticeError wins and is reported, a config setting in the agent can be changed to `false`.  This does not switch the behavior though for errors seen by tracers versus the noticeError API. Last tracer error still wins with this config setting. 

    `ignoreErrorPriority: false`

Draft PR in docs to add this config - https://github.com/newrelic/docs-website/pull/2353#issuecomment-844446268

**Comment by tbradellis** [comment]
I'll add the ingoreErrorPriority documentation. Once done with that piece I'll close this out.

**Comment by tbradellis** [comment]
Added configuration property PR to public docs:
https://github.com/newrelic/docs-website/pull/2607
