### ISSUE TITLE
Add @Target(ElementType.ANNOTATION_TYPE) to Trace Annotation

### ISSUE THREAD

**Issue by andrewrowe-wk** [newrelic/newrelic-java-agent#308]
## Is your feature request related to a problem? Please describe.
We have a service that runs many `@Scheduled` jobs ([we use the Spring boot schedler](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/scheduling/annotation/Scheduled.html)). When creating new scheduled jobs, it is a common pattern for us to add the `Trace` annotation to the method as well. To avoid copy/paste issues, we would like to create a new annotation that is a composition of `@Scheduled` and `@Trace`. However, after doing some research, it appears that this is not possible, because `@Trace` only supports `ElementType.METHOD` as a target, and not `ElementType.ANNOTATION_TYPE` ([see here](https://github.com/newrelic/newrelic-java-agent/blob/c98fa7495fa35a7dee703aadfb2e06ca658fe11a/newrelic-api/src/main/java/com/newrelic/api/agent/Trace.java#L39)).

## Feature Description
We would like `@Trace` to support targeting `ElementType.ANNOTATION_TYPE`.

## Describe Alternatives
1. Have a single cron method that sends callbacks to a traced method for each cron with necessary error handling to make sure that one failed job does not affect others
2. We can potentially call the cron service directly (bypass the annotation… I’ve seen what appear to be a few examples online), and provide it with a traceable method, but this seems like it would be prone to error
3. Maybe we can configure the scheduler to do something like we want (https://www.baeldung.com/spring-scheduled-tasks#setting-delay-or-rate-dynamically-at-runtime)

## Additional context
N/A

## Priority
Please help us better understand this feature request by choosing a priority from the following options: 
Nice to Have

**Comment by andrewunderwood-wf** [comment]
WOW! I need this too! What an awesome request!

**Comment by jasonjkeller** [comment]
@andrewrowe-wk Have you experimented with creating a custom `@Trace` annotation? https://docs.newrelic.com/docs/agents/java-agent/api-guides/java-agent-api-instrument-using-annotation/#custom-class

If so, I'd be curious to know if it works for your use case.

An alternative approach would be to write a simple instrumentation module that weaves any method with the `org.springframework.scheduling.annotation.Scheduled` annotation and automatically starts a transaction. This means you wouldn't have to use the `@Trace` annotation in your codebase at all as the agent would be able to auto-instrument in such cases. It would probably look like a simplified version of our [jax-rs instrumentation](https://github.com/newrelic/newrelic-java-agent/blob/main/instrumentation/jax-rs-1.0/src/main/java/com/nr/instrumentation/javax/ws/rs/api/JavaxWsRsApi_Instrumentation.java). PRs welcome. :)

**Comment by andrewrowe-wk** [comment]
@jasonjkeller Thank you! We will give that a try and let you know.

**Comment by kford-newrelic** [comment]
We appreciate the suggested enhancement but unfortunately, it was not selected for the go-forward agent roadmap.
