### ISSUE TITLE
Spring Reactive DB Drivers - Lettuce Support

### ISSUE THREAD

**Issue by kford-newrelic** [newrelic/newrelic-java-agent#317]
<p>Add out-of-the-box Java agent support for the Lettuce DB driver under the Spring Reactive framework</p><p>See MMF <a href="https://docs.google.com/document/d/1wrM0B9puN0YR3Wn9jGbNrCu-fw63Di856wh3hlwhYF0/edit?usp=sharing">doc</a></p><p>Add support for Reactive calls to Lettuce drivers so that database interactions are instrumented by the Java Agent. </p><p><span style="color:#2F3941;background-color:#F8F9F9;">Review </span><a href="https://github.com/topics/nrlabs"><span style="color:#2F3941;background-color:#F8F9F9;">https://github.com/topics/nrlabs</span></a><span style="color:#2F3941;background-color:#F8F9F9;"> instrumentation for Mongo async, Lettuce, etc.</span></p>

- [ ] Clean up the [4.0 Incubator Project](https://source.datanerd.us/java-agent/incubator/tree/master/lettuce-4.0)
- [ ] Clean up the [5.0 Incubator Project](https://source.datanerd.us/java-agent/incubator/tree/master/lettuce-5.0)

**Comment by meiao** [comment]
There is this [PR](https://github.com/newrelic/newrelic-java-agent/pull/310) with support for Lettuce.
Needs review and automatic testing.
