### ISSUE TITLE
Sample App to exercise AWS SDK 2 DynamoDB sync/async clients

### ISSUE THREAD

**Issue by XiXiaPdx** [newrelic/newrelic-java-agent#322]
Build sample app that uses the sync and async client of AWS SDK 2 DynamoDB

Use this sample to validate new instrumentation

**Comment by twcrone** [comment]
V1 work currently under https://github.com/twcrone/dynamodb-example

**Comment by twcrone** [comment]
V2 async work here https://github.com/twcrone/aws-v2-dynamoDB-sample

**Comment by kford-newrelic** [comment]
@twcrone are we going to pull this sample app into the `newrelic-java-examples` repo?
