### ISSUE TITLE
Tags don't work with multiple application names

### ISSUE THREAD

**Issue by twcrone** [newrelic/newrelic-java-agent#337]
Tags don't work with multiple application names

## Description
We are using this yml configuration to group the instances of our app

app_name: teams-automation,abc-pre-prod

labels:
project: xyz
region: east
env: preprod
site: it
name: teams-automation

When we do like this the tags are missing from the web ui.

The labels are back just if the app_name is unique among the instances

## Expected Behavior
Tags appear in Web UI

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results
TSE tried this themselves, and got the same results.  It seems like tags work fine for a single application name, but aren't forwarded to either app if there are multiple application names listed in the .yml file.  Tested this on the latest agent version.

## Steps to Reproduce
Add multiple labels to multiple apps in YML file as show above

## Additional context

(Migrate to Jira)

**Comment by kford-newrelic** [comment]
This enhancement will not be added to the agent's roadmap.
