### ISSUE TITLE
Version 7.1 generates a lot of INFO level logs

### ISSUE THREAD

**Issue by hamid646** [newrelic/newrelic-java-agent#342]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )
After upgrading to version 7.1, a lot of logs are being generated at INFO level like

    2021-07-09T12:40:01,480+0000 [1 104] com.newrelic INFO: This conversion had 49 events
    2021-07-09T12:40:01,481+0000 [1 104] com.newrelic INFO: Sending metric batch of size 132
    2021-07-09T12:40:01,568+0000 [1 104] com.newrelic INFO: Sending events batch of size 87

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen. )
These logs should be at DEBUG level

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results
[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

## Steps to Reproduce
[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )
Use java agent version 7.1

## Your Environment
[TIP]:  # ( Include as many relevant details about your environment as possible including the running version of New Relic software, JVM vendor and version, framework versions, and any relevant configuration. )
Java 11
Agent: v7.1.0

## Additional context
[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )

**Comment by jasonjkeller** [comment]
This was resolved in the jfr-core release 0.6.0 https://github.com/newrelic/newrelic-jfr-core/pull/208 which will be incorporate into Java agent release 7.5.0.
