### ISSUE TITLE
CompletableFutures instrumentation potentially causes token timeouts

### ISSUE THREAD

**Issue by XiXiaPdx** [newrelic/newrelic-java-agent#344]
## Description
CompletableFutures instrumentation currently creates tokens whenever a CompletableFuture is created. We assume that CF will be completed, whether success or error. When completed, we catch all the finish points to expire our token.

But the common usage pattern for CompletableFutures do not guarantee every CF be completed. It is typical to create a CF for success and for error. The instrumentation would then create a token for both but potentially only one will be completed.  This results in an unexpired token that will not be removed from the token cache until it times out (default is 180 seconds). 

The consequence of this is a Transaction will not finish until the token times out. So a transaction will not be reported until 3-4 minutes after it occurred. From early testing, the transaction duration is not affected (3 minutes is not added to the transaction duration). There is just a delay in reporting and also long lived tokens.

## Expected Behavior
CompletableFutures instrumentation would not create unexpired tokens, causing token timeouts. 

A potential next step  - https://newrelic.slack.com/archives/G96BPDE4Q/p1575831177351600

## Additional context
This behavior can be observed with the WIP JDK11 HttpClient instrumentation and also the AWS sdk dynamo V2  instrumentation.

**Comment by mathieufortin01** [comment]
>From early testing, the transaction duration is not affected (3 minutes is not added to the transaction duration).

Hi. I think we are running into this issue, but the transaction duration DO seem to be affected in our cases. Every transactions involving the Java11 HttpClient seems to have this behavior. A typical trx takes ~1s when looking at the traces total, but `transaction.duration` reports over 60s. Looking more into the detailed traces, we can see a bunch of `CompletableFuture.completion()` at the ~60s mark. Looking into a workaround without manually tracing those async calls.
