### ISSUE TITLE
Conflict with AspectJ weaving - java.lang.VerifyError: Inconsistent stackmap frames at branch target

### ISSUE THREAD

**Issue by jasonjkeller** [newrelic/newrelic-java-agent#347]
In rare cases there is a conflict between the New Relic Java agent and AspectJ weaving. This has been observed with `jax-rs` and `spring` instrumentation.

From: https://newrelic.atlassian.net/browse/JAVASUP-599 and https://newrelic.atlassian.net/browse/JAVA-3600

This problem occurs when we double weave a method (instrument it twice) that has a specific bytecode pattern. The bytecode pattern seems to occur when AspectJ is involved. Specifically, when customers instrument their code with an `@AfterReturning` advice. For reasons unknown to us, the AspectJ compiler leaves an extra value on top of the stack. When we double weave the method, the class fails bytecode verification and we end up with a bytecode verfiyerror as the class gets loaded. While we were able to find a solution that fixes this problem, it creates other problems that made this an even more expensive fix.

The workarounds we've identified so far:

1) Remove the `@AfterReturning` aspect from the methods. 

OR 

2) Disable AspectJ weaving for the affected application.

OR

3) Disable the instrumentation that double weaves: `jax-rs` or `spring`.

```
  class_transformer:
    com.newrelic.instrumentation.jax-rs-1.0:
        enabled: false
    com.newrelic.instrumentation.spring-4.3.0:
      enabled: false
```

OR

4) Add affected class to list of excludes (classes we don't instrument).

1 - Keeps NR instrumentation, but removes customer AspectJ instrumentation.
2 - Similar to 1, keeps NR instrumentation, but removes customer AspectJ instrumentation. Entirely removes potential for weaving conflicts.
3 - Disables the whole NR instrumentation module, so classes that are not affected will also not be instrumented.
4 - Compromise between 1 and 2, but we'll still have an instrumentation gap.

```
[Server:server-one] 15:16:13,334 ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 74) MSC000001: Failed to start service ... : java.lang.VerifyError: Inconsistent stackmap frames at branch target 1515
[Server:server-one] Exception Details:
[Server:server-one]   Location:
[Server:server-one]     com/safesigner/oauth/server/AuthzEndpoint.userCreationInfo(Ljavax/servlet/http/HttpServletRequest;Ljavax/ws/rs/core/MultivaluedMap;)Lcom/safesigner/oauth/model/CreationInfoResponse; @1512: goto
[Server:server-one]   Reason:
[Server:server-one]     Current frame's stack size doesn't match stackmap.
[Server:server-one]   Current Frame:
[Server:server-one]     bci: @1512
[Server:server-one]     flags: { }
[Server:server-one]     locals: { 'com/safesigner/oauth/server/AuthzEndpoint', 'javax/servlet/http/HttpServletRequest', 'javax/ws/rs/core/MultivaluedMap', 'com/newrelic/agent/bridge/ExitTracer', integer, null, top, top, top, top, top, top, top, top, top, top, top, top, 'javax/ws/rs/core/MultivaluedMap', 'javax/servlet/http/HttpServletRequest', 'com/safesigner/oauth/server/AuthzEndpoint', integer, 'com/safesigner/oauth/model/CreationInfoResponse', top, top, top, top, top, top, top, top, top, top, top, 'java/lang/Throwable', 'javax/ws/rs/core/MultivaluedMap', 'javax/servlet/http/HttpServletRequest', 'com/safesigner/oauth/server/AuthzEndpoint', 'javax/servlet/http/HttpServletRequest', 'javax/ws/rs/core/MultivaluedMap', 'org/aspectj/lang/JoinPoint', 'com/safesigner/oauth/model/CreationInfoResponse', 'java/lang/String', 'com/safesigner/oauth/context/Client', 'com/safesigner/oauth/model/CreationInfoResponse', top, top, top, top, top, top, top, top, top, 'com/safesigner/oauth/model/CreationInfoResponse' }
[Server:server-one]     stack: { 'com/safesigner/oauth/model/CreationInfoResponse' }
[Server:server-one]   Stackmap Frame:
[Server:server-one]     bci: @1515
[Server:server-one]     flags: { }
[Server:server-one]     locals: { 'com/safesigner/oauth/server/AuthzEndpoint', 'javax/servlet/http/HttpServletRequest', 'javax/ws/rs/core/MultivaluedMap', 'com/newrelic/agent/bridge/ExitTracer', integer, null, top, top, top, top, top, top, top, top, top, top, top, top, 'javax/ws/rs/core/MultivaluedMap', 'javax/servlet/http/HttpServletRequest', 'com/safesigner/oauth/server/AuthzEndpoint', integer, 'com/safesigner/oauth/model/CreationInfoResponse', top, top, top, top, top, top, top, top, top, top, top, top, 'javax/ws/rs/core/MultivaluedMap', 'javax/servlet/http/HttpServletRequest', 'com/safesigner/oauth/server/AuthzEndpoint', 'javax/servlet/http/HttpServletRequest', 'javax/ws/rs/core/MultivaluedMap', 'org/aspectj/lang/JoinPoint', 'com/safesigner/oauth/model/CreationInfoResponse', 'java/lang/String', 'com/safesigner/oauth/context/Client', 'com/safesigner/oauth/model/CreationInfoResponse', top, top, top, top, top, top, top, top, top, 'com/safesigner/oauth/model/CreationInfoResponse' }
[Server:server-one]     stack: { 'com/safesigner/oauth/model/CreationInfoResponse', 'com/safesigner/oauth/model/CreationInfoResponse' }
```

(Migrate to Jira)

**Comment by harshithjain** [comment]
@jasonjkeller We are also facing the same issue and we are moving from Spring 4.3 to 5.3 due to Security vulnerability. We are aware of Option 1 but that's hard to remove in our application as it involves a lot of classes. So wanted to try other options. Having said that can you help us in explaining options 2 and option 3 with some examples if you have them?

- For option 2 are you suggesting removing the AspectJ functionality itself? If I am getting this wrong, can you help me with some example on how to remove the AspectJ weaving from the application?

- For option 3 how can I decide on the version of jax-rs and spring when I am using 7.5 version of newRelic jar? I tried putting them without any versions but that didn't help me, so wanted to understand if there is some mechanism/Do i need to specify the version. if yes how can I find the version?


Thanks in advance for your help!

**Comment by jasonjkeller** [comment]
@harshithjain I'm not entirely sure on the steps to effectively disable AspectJ. I think you would need to refer to the Spring documentation on how to do that.

As far as figuring out what Java agent instrumentation is loaded for a particular service you can run the following query. You'll need to provide the `entity.guid` for the service you are inspecting and you might need to expand the time period depending on when the agent actually loaded the instrumentation modules.

```
SELECT max(newrelic.timeslice.value) FROM Metric WHERE metricTimesliceName LIKE 'Supportability/WeaveInstrumentation/Loaded/%' AND `entity.guid` = 'XYZ' FACET metricTimesliceName SINCE 5 week ago LIMIT MAX
```

Here's a screenshot of what the query will show you:

<img width="1404" alt="loaded-instrumentation" src="https://user-images.githubusercontent.com/3496648/204415572-3918e39c-bb95-4a42-bd41-0e46f1bbcd4e.png">

**Comment by rdfedor** [comment]
Running into the same issue with a project but don't use AspectJ.  Ran into the issue when upgrading to using Java 17, spring-boot-starter and Kotlin 1.7.22. Don't use @AfterReturning unless spring-boot-starter has AspectJ built into it, don't know how to disable it otherwise since I'm not calling it.  The only solution I had was to disable spring implementation but kind of defeats the purpose of having newrelic if I can't collect metrics on route performance.  This issue started after updating project dependencies without actual code change,

`implementation "org.springframework.boot:spring-boot-starter-actuator"
    implementation "org.springframework.boot:spring-boot-starter-web"
    implementation "org.springframework.boot:spring-boot-starter-mail"
    implementation "org.springframework.boot:spring-boot-starter-data-jpa"
    // Spring Boot security
    implementation "org.springframework.security.oauth.boot:spring-security-oauth2-autoconfigure:2.6.8"
    implementation "org.springframework.security.oauth:spring-security-oauth2:2.5.2.RELEASE"
    implementation "org.springframework.security:spring-security-jwt:1.1.1.RELEASE"

    implementation "org.springframework:spring-jdbc"
    implementation "com.squareup.okhttp3:okhttp:4.4.0"
    implementation "com.fasterxml.jackson.module:jackson-module-kotlin:2.13.5"
    implementation 'mysql:mysql-connector-java:8.0.32'
    implementation "javax.persistence:javax.persistence-api:2.2"
    implementation "org.hibernate:hibernate-core:5.5.7.Final"

    implementation platform("org.jetbrains.kotlin:kotlin-bom:$kotlin_version")
    implementation "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"
    implementation "com.sendgrid:sendgrid-java:4.3.0"
    implementation "com.microsoft.azure:msal4j:1.3.0"
    implementation 'io.micrometer:micrometer-registry-prometheus'
    implementation "com.twilio.sdk:twilio:7.54.1"
    implementation "io.springfox:springfox-swagger-ui:2.9.2"
    implementation "io.springfox:springfox-swagger2:2.9.2"
    implementation('com.sun.xml.bind:jaxb-ri:4.0.1') {
        exclude group: 'com.sun.xml.bind', module: 'jaxb-release-documentation'
        exclude group: 'com.sun.xml.bind', module: 'jaxb-samples'
    }
    testImplementation "org.springframework.boot:spring-boot-starter-test"
    testImplementation "io.mockk:mockk:1.10.0"`

**Comment by kford-newrelic** [comment]
We have decided against further pursuing this issue.
