### ISSUE TITLE
Starting with version 7.0.0 the newrelic java agent breaks some scala compiler functionality.

### ISSUE THREAD

**Issue by jasonjkeller** [newrelic/newrelic-java-agent#349]
Starting with version 7.0.0 (so its confirmed working with 6.5) the newrelic java agent breaks scala compiler functionality. 

Below is a repro but it requires that a type extends from the akka http Directives class.

```
import scala.reflect.runtime.{universe => ru}
import ru._

//  http       : [group: "com.typesafe.akka", name: "akka-http_2.12", version: "10.2.4"],
//  compiler   : [group: "org.scala-lang", name: "scala-compiler", version: "2.12.14"],

class CustomClass() extends akka.http.scaladsl.server.Directives {
  def hello() = println("hello")
}

object Repro {
  def runTest(): Unit = {
    test[CustomClass]
  }

  private def test[T]()(implicit tag: TypeTag[T]): Unit = {
    val tsym = tag.tpe.typeSymbol
    val apiClass = tsym.asClass
    val apiPathMethods = apiClass.info.decls

    println(apiPathMethods)
  }
}
```

The attached debugger.png compares the debugger output from the two, note that with v 6.5.0 it shows the correct # of methods, but with 7.0 we get back 0 methods instead.

![debugger](https://user-images.githubusercontent.com/3496648/126690696-66824388-0f1b-46bd-8451-52ed1f19ce2d.png)

---

Commenting out `akka-http-2.4.5` `ImplicitPathMatcherConstruction_Instrumentation` brings back the methods. Interestingly:

This works (methods returned)

```
@Weave(`type` = MatchType.BaseClass, originalName = "akka.http.scaladsl.server.ImplicitPathMatcherConstruction")
abstract class ImplicitPathMatcherConstruction_Instrumentation {
}
```

But this doesn't (No methods returned), even replacing the method implementation with `Weaver.callOriginal()`

```
@Weave(`type` = MatchType.BaseClass, originalName = "akka.http.scaladsl.server.ImplicitPathMatcherConstruction")
abstract class ImplicitPathMatcherConstruction_Instrumentation {
  implicit def _regex2PathMatcher(regex: Regex): PathMatcher1[String] = Weaver.callOriginal()
}
```

This appears to be caused by an issue with `@Weave` & `@ScalaWeave` when weaving in Scala code. Weaving Scala code into a class using theses annotations prevents reflection at runtime.

[GTSE-10455](https://newrelic.atlassian.net/browse/GTSE-10455)

**Comment by kford-newrelic** [comment]
Since this issue only occurs when reflection is used against framework classes that we instrument in Scala - which is not a common thing to do - we are not going to address this issue.

Rewriting Scala instrumentation in Java and limiting our Scala instrumentation to be written in Java is not a desirable situation long-term.
