### ISSUE TITLE
Instrumentation needed for Spring Security Config Starting with bundles for Spring Boot 2.2.2 (Spike)

### ISSUE THREAD

**Issue by tbradellis** [newrelic/newrelic-java-agent#353]
Starting in Spring Boot bundle 2.2.2 there is a change in how SecurityConfig is used.  
A new thread gets started, causing our current instrumentation to lose the Transaction context and name the Transaction by the dispatcher. The controller instrumentation doesn't get included on the Transaction so the naming is wrong and part of the Transaction is missing. 

![https://user-images.githubusercontent.com/7401258/127380075-73a0b870-5c9c-4a82-a6af-42fed3890f68.png](https://user-images.githubusercontent.com/7401258/127380075-73a0b870-5c9c-4a82-a6af-42fed3890f68.png)

## Feature Description

We need to add support for the new SecurityConfig.

## Additional context

Internal GTSE-9940

## Priority

Please help us better understand this feature request by choosing a priority from the following options: Really Want

Aha! Link: https://newrelic.aha.io/features/JAVA-333

**Comment by kford-newrelic** [comment]
@tbradellis is the customer losing metric info at the transaction level due to this issue?

**Comment by kford-newrelic** [comment]
Comment added by Kevyn Ford in Aha! - [View](https://newrelic.aha.io/comments/7026700255577658269)

Proposed solution being further vetted and tested by the team. Moving this MMF to Nov to compensate for the additional engineering time needed.
