### ISSUE TITLE
Netty 4 data chunking results in missing exception details

### ISSUE THREAD

**Issue by jasonjkeller** [newrelic/newrelic-java-agent#354]
It was reported that after upgrading from Netty 3 to Netty 4 errors just show up as `NettyDispatcher` and are not broken out by the type of error. The errors appear to be missing the exception class, error message, and stack trace details.

![netty-dispatcher-error](https://user-images.githubusercontent.com/3496648/127395218-b443bf3b-690e-4b42-8964-db26c19d012e.png)

This behavior is likely caused by chunking behavior being utilized in Netty 4:

> Netty 4 is massively supporting the chunked data (In netty 3 for single packet http request you where handling the http request and for chunked request - chunk + requests , in netty 4 this is not the case and even for single packet the netty handlers are generating http request/response and then http chunk/http last chunk. The response content is in chunks and not in response itself, while response code is in response itself.

>In order to generate chunks you would need 2 servers. One end server and one intermediate server that would proxy data from one leg to another. Then you would need to send the request and proxy the response. The response handlers that should be added to netty should be of type of `SimpleChannelInboundHandler<HttpObject>`, same with request handler.

(Migrate to Jira)

**Comment by kford-newrelic** [comment]
Not selected for further investigation.
