### ISSUE TITLE
GraphQL Instrumentation - Do not create spans for scalar return type resolvers, unless the top level

### ISSUE THREAD

**Issue by XiXiaPdx** [newrelic/newrelic-java-agent#361]
example query:
```
query {
   book {
       id (return type is scalar)
       title (return type is scalar)
   }
}
```

Don't create a resolver span for `id` and `title`, create one for `book`

example query, for the classic "Hello World" graphql example.
hello here would return a String "World"

```
query {
   hello {
   }
}
```

A resolver span for hello would be created because it is top level.

**Comment by kford-newrelic** [comment]
De-prioritized. Not added to the agent roadmap.
