### ISSUE TITLE
Failed grpc calls that are handled by application lead to false positive errors

### ISSUE THREAD

**Issue by Entea** [newrelic/newrelic-java-agent#368]
# Failed grpc calls that are handled by application lead to false positive errors

## Description
I have code that does something like this:
```
try { grpc_call() } catch(Exception e) { compensate_for_error() }
```
However, newrelic keeps reporting failed grpc calls, although they don't affect the appilcation at all
## Expected Behavior
Grpc call errors that are handled by the application should not be reported as errors. Or there should exist a way to ignore such errors (a separate config entry that allows to ignore errors based on grpc service and method names e.g. "com.example.SomeService#someCall=ignored")

## Your Environment
jdk-11, grpc-java-1.34.1

**Comment by kford-newrelic** [comment]
@Entea we apologize but unfortunately, we don't have the engineering bandwidth to investigate this issue. Not selected for the product roadmap.
