### ISSUE TITLE
Deeper database instance level instrumentation for Informatica db connections

### ISSUE THREAD

**Issue by tbradellis** [newrelic/newrelic-java-agent#369]
## Is your feature request related to a problem? Please describe.
The agent does not pick up Instance level db information for Informatica db connections.
## Feature Description
Provide db connection details and db instance name/address with OTB instrumentation.
## Not much in the way of alternatives.
code is behind third party implementation so custom instrumentation for db level info isn't viable.
## Additional context and Alternatives
This will require research into the Informatica jdbc driver(s) implementation and the wrappers being used.  Commonly, wrappers prevent us from grabbing the instance level information. It may be possible to get the information by disabling the Weave on wrapper classes.  However some attempt to do this was made in a support ticket....Attempts were unsuccessful.  A deeper dive into the implementation may or may not provide a means to achieve this with disabling instrumentation.  Research time will need to be allocated to determining the best route to provide instance level db instrumentation for Informatica.

**Comment by sorodol** [comment]
Hi, 

Do we have update on this issue?

Reference New Relic Case #452400

**Comment by kford-newrelic** [comment]
Request appears to require instrumenting closed source APIs.

While we appreciate your feature request submission, this issue has not been chosen for the agent go-forward roadmap.
