### ISSUE TITLE
Selective monitoring of Tomcat applications

### ISSUE THREAD

**Issue by malchorne** [newrelic/newrelic-java-agent#372]
## Is your feature request related to a problem? Please describe.
We have recently been looking into the volume of data ingested into New Relic and found that the default pages in Tomcat (Welcome to Tomcat & Tomcat Manager application) are adding significantly to the volumes of data we store.

These areas are used by our IT team and our Load Balancer - so we need them switched on - however we do not need to have New Relic monitoring them.  We have multiple application contexts on the Tomcat instances - so working in this way allows simple configuration in the Load Balancer.

It looks like this is possible with IIS - but not with Tomcat.

## Feature Description
We would like to be able to disable the monitoring of the application - we have seen that there is support for "agent_enabled" parameter - however this cannot be applied to a single context under Tomcat.

I think that to achieve what we need we would ideally have to disable at the top level in the web.xml - but then enable the individual <customer_application>.xml context  files as required.

## Describe Alternatives
We have discussed this with the New Relic team - and it was recommended that we make a feature request. (ticket #466539)

## Additional context
The other option would be for us to be able to drop this data using a DROP_DATA rule.  However apparently this will not be possible due to the nature of the information.

This data is causing us additional unnecessary variable expense.  Which may lead to a longer term monitoring technology decision.

## Priority
Really Want

**Comment by kford-newrelic** [comment]
We appreciate your feature request submission however this issue has not be chosen for the go-forward agent roadmap.
