### ISSUE TITLE
expected_status_codes is not honored when there is an exception in the transaction

### ISSUE THREAD

**Issue by meiao** [newrelic/newrelic-java-agent#376]
## Description
Setting a `expected_status_code` will not mark an error as expected when there is an exception in the transaction.

## Expected Behavior
If a transaction returns with a status code that is in the `expected_status_code` an error from this transaction should be marked as expected regardless of the existence of an exception.

This is how `ignored_status_code` works.

**Comment by meiao** [comment]
This is likely due to the difference between ThrowableError and HttpTracedError.

**Comment by meiao** [comment]
The repository below has a simple app to reproduce the problem.
https://github.com/meiao/repro-nr-376

**Comment by sdmcintyre** [comment]
Any idea when this might get looked at? This causes many false alarms in our monitoring due to things like input validation errors (HTTP bad request).

**Comment by tbradellis** [comment]
I think the problem starts here with `markExpected:`
https://github.com/newrelic/newrelic-java-agent/blob/bf6cb39760c3d5e66d8614cd698a95bcb381c347/newrelic-agent/src/main/java/com/newrelic/agent/errors/ErrorServiceImpl.java#L441

We only check whether it's expected on the Throwable. As @meiao hinted on `ThrowableError` and `HttpTracedError`.  When we get to `HttpTracedError` we don't consult the status code to see if we need to set markedExpected differently based on status.  I have a local change and will run some tests with a change for this.
Essentially, I think we should just check if the status code is expected and reset `markedExpected` here:
https://github.com/newrelic/newrelic-java-agent/blob/bf6cb39760c3d5e66d8614cd698a95bcb381c347/newrelic-agent/src/main/java/com/newrelic/agent/errors/ErrorServiceImpl.java#L467

**Comment by tbradellis** [comment]
Correction...we also need to check this for ThrowableError.

**Comment by tbradellis** [comment]
https://github.com/newrelic/newrelic-java-agent/blob/bellis/expected-error-response-status/newrelic-agent/src/main/java/com/newrelic/agent/errors/ErrorServiceImpl.java#:~:text=boolean%20responseStatusExpected%20%3D%20errorCollectorConfig,markedExpected%20%3D%20responseStatusExpected%20%7C%7C%20throwableExpected%3B

**Comment by sdmcintyre** [comment]
Do we need to update our New Relic Agent to apply the fix?

**Comment by meiao** [comment]
Yes. Agent 7.5.0 has the fix.
