### ISSUE TITLE
DT by default in Agents

### ISSUE THREAD

**Issue by kford-newrelic** [newrelic/newrelic-java-agent#385]
**Goals:** New Relic’s agents have distributed tracing enabled by default. New Relic’s agents use w3c TraceContext 1.0 for cross-industry interop by default.

New Relic deprecates (not remove) CAT. Intention is to allow CAT functionality in the near term. Initially we would allow customers to configure agents explicitly to step back to CAT.

**Benefits:** Customers can see traces in New Relic that were gathered by multiple vendor’s exporters. New Relic deprecates CAT, which will simplify its messaging about distributed tracing.

**Dependencies** : Ratification of w3c TraceContext, close parity gaps with CAT (scalability, support for service maps with DT, ... previously also high granularity external calls but that is now 'covered by OTel experience').

**Additional Functionality:**

- Conduct performance testing to determine min/default/max span reservoir sizes
- Implement local config file driven ability to set the span reservoir size
- Support agent connect response limiting of max span reservoir size
- Enhance public documentation to help customers understand span reservoir size tuning recommendations

Aha! Link: https://newrelic.aha.io/features/JAVA-91

**Comment by jasonjkeller** [comment]
Project plan: https://docs.google.com/document/d/1UihN2YMJ7kYqZcw74G1sP-GJHknjdH3f1KUugOepgfE/edit#

**Comment by jasonjkeller** [comment]
Notes on a couple of key decisions pertaining to these efforts:
- Server side config is out of scope.
- CAT will be deprecated, not removed.
- Because CAT is only deprecated these changes don't require a major version bump.
- The span harvest cycle will remain locked at 60 seconds.

**Comment by kford-newrelic** [comment]
Included as part of the `7.4.0` release
