### ISSUE TITLE
Add 'AddRolledUpMetricName' to the Segment API

### ISSUE THREAD

**Issue by smiklos** [newrelic/newrelic-java-agent#389]
## Is your feature request related to a problem? Please describe.

I'm implementing monitoring for a sangria based scala graphql project. 
I would like to have some of the segments I create via the API to also report their metric under a rollup metric.

Currently Segments have a name but also a  setMetricName method, both of which just names/renames the underlying tracer.
There is no way to reuse the metric and report it under a rollup metric name like we can do for TracedMethods. 

## Feature Description
A clear and concise description of the feature you want or need.
Similarly to TracedMethods, I would like to add rollup metric names to Segments as well.

Adding the `AddRolleupMetricName` method the public Segment Api would do the trick.
The implementation could delegate to the underlying tracer.

## Describe Alternatives
A clear and concise description of any alternative solutions or features you've considered. Are there examples you could link us to?
Currently the only alternative I'm aware of is to record a metric manually.

As for a feature request, we could also just have the tracer be exposed on Segment but I don't know if that's desirable 

## Additional context
Add any other context here.

## Priority
Please help us better understand this feature request by choosing a priority from the following options: 
[Really Want]

**Comment by kford-newrelic** [comment]
@smiklos thank you for the feature request but unfortunately, we do not have the engineering bandwidth to implement this. Not selected for the product roadmap.
