### ISSUE TITLE
Provide support for self-attaching the agent

### ISSUE THREAD

**Issue by vpavic** [newrelic/newrelic-java-agent#407]
## Is your feature request related to a problem? Please describe.
Enabling New Relic's java agent in a dockerized application is a bit awkward because it typically includes:
- adding the agent to Docker image: this requires some custom build logic if we want to pull the agent from Maven Central, like other dependencies
- enabling the agent using `-javaagent` flag via `JAVA_TOOL_OPTIONS` environment variable: this is the awkward part, since we have to refer to a path inside the container

## Feature Description
It would be nice if the New Relic agent would offer the programmatic way to self-attach, which would then be used from within the application (most likely it's main method). See the equivalent feature offered from [Elastic APM's java agent](https://www.elastic.co/guide/en/apm/agent/java/1.x/setup-attach-api.html).

This could then be hidden behind an arbitrary means of external configuration, such as an environment variable, but that isn't tied to something as rigid as `JAVA_TOOL_OPTIONS: -javaagent:/path/to/new-relic-agent.jar`. It would also enable the easier assembly of docker image, as the agent would simply become a dependency like any other.

## Describe Alternatives
The alternatives are currently present (i.e. default) options for setting up java agent.

## Additional context
n/a

## Priority
Somewhere between _Nice to Have_ and _Really Want_. :slightly_smiling_face:

**Comment by kford-newrelic** [comment]
@vpavic Thank you for the feature request - unfortunately, we do not have the engineering capacity to implement this. Not selected for the product roadmap.
