### ISSUE TITLE
Add public config for Span reservoir size and ensure that correct value is being applied

### ISSUE THREAD

**Issue by jasonjkeller** [newrelic/newrelic-java-agent#414]
Agents should implement a new public config that allows customers to change the Span reservoir size used for DT. The config should work with yaml, system property, and environment variables of the following forms:

Yaml
```
  span_events:
    max_samples_stored: 1000
```

System property
```
-Dnewrelic.config.span_events.max_samples_stored=1000
```

Environment variable
```
NEW_RELIC_SPAN_EVENTS_MAX_SAMPLES_STORED=1000
```

---

The default reservoir size will remain 1000. Agents need to report the locally set reservoir size to the [Connect Service](https://source.datanerd.us/agents/agent-specs/blob/master/Connect-LEGACY.md#span-event-harvest-config) which will send back the final limit to be applied by the agent. This is so that the Connect Service can impose an acceptable limit in cases where an extremely high limit was configured locally. Currently, the Connect Service will impose a max limit of 10,000. See [Connect spec](https://source.datanerd.us/agents/agent-specs/blob/master/Connect-LEGACY.md) for full details.

~~The collector changes to support this behavior are live in staging. You can add your own staging account to this [feature flag](https://staging-featureflag.datanerd.us/flags/8504/edit) or simply use the [Java Agent Testing](https://staging.onenr.io/0a2wdNm9EjE) staging account that is already added.~~

When the agent receives the final limit from the Connect Service and applies it, a `Supportability/SpanEvent/Limit` supportability metric must be reported with the value of the final decided upon Span reservoir size. See [Span-Events spec](https://source.datanerd.us/agents/agent-specs/blob/master/Span-Events.md#metrics) for full details.

---

Add tests for the new config and supportability metric. Ensure that all test suites (unit, functional, instrumentation, and AITs) pass.

**Comment by XiXiaPdx** [comment]
The collector changes that support this behavior are now live in staging and production for all accounts.  https://newrelic.slack.com/archives/C0290QGR02V/p1631555632078400

**Comment by XiXiaPdx** [comment]
@jasonjkeller Could we set the default to 2000? That seems to be the consensus with the other agents.

**Comment by jasonjkeller** [comment]
@XiXiaPdx I'm guessing that 2000 will be fine but it would be great to back that assumption up with performance data from OATS so we can say with certainty whether the overhead impact is negligible or not.

**Comment by jasonjkeller** [comment]
@XiXiaPdx I'm going to work on running OATS now.

**Comment by jasonjkeller** [comment]
This was resolved by https://github.com/newrelic/newrelic-java-agent/pull/443 and https://github.com/newrelic/newrelic-java-agent/pull/460
