### ISSUE TITLE
Update the agent to support Java 17

### ISSUE THREAD

**Issue by jasonjkeller** [newrelic/newrelic-java-agent#418]
This should be pretty straightforward, see the work that was done to support [Java 16](https://github.com/newrelic/newrelic-java-agent/pull/366) for guidance.

- [x] Upgrade ASM version
- [x] Update use of ASM Opcodes in agent (see `WeaveUtils.ASM_API_LEVEL`)
- [x] Address all classes with the following comment: `NOTE: If you are upgrading from org.ow2.asm:asm / org.ow2.asm:asm-tree make sure to double check that this class hasn't changed between versions.`
- [x] Configure tests to run with Java 17 JRE
- [x] Update `JavaVersionUtils` and related test
- [x] Add `Java17IncompatibleTest` marker interface and annotate tests that are incompatible with Java 17
- [x] Ensure all unit tests pass
- [x] Ensure all functional tests pass
- [x] Ensure all instrumentation tests pass

**Comment by kford-newrelic** [comment]
Our `7.4.0` release now supports Java 17!

Appreciate you sharing your thoughts about our timeline to get to Java 17 - we intend to support newer Java versions sooner going forward.
