### ISSUE TITLE
Scala instrumentation - Monix async framework support

### ISSUE THREAD

**Issue by kford-newrelic** [newrelic/newrelic-java-agent#424]
Provide OOTB instrumentation support for the Monix async framework, as requested by customers

Aha! Link: https://newrelic.aha.io/features/JAVA-338

**Comment by kford-newrelic** [comment]
Comment added by Kevyn Ford in Aha! - [View](https://newrelic.aha.io/comments/7026702235349367108)

New instrumentation delayed due to the need to address multiple GHA migration/build related issues. Moving this MMF to Nov to compensate.

**Comment by twcrone** [comment]
This instrumentation has been implemented and merged to main and should be in our next release.
