### ISSUE TITLE
Missing Checksums

### ISSUE THREAD

**Issue by oniGino** [newrelic/newrelic-java-agent#425]
Your APM releases, both source code zips/tars as well as compiled jars. should have associated sha256 checksums  

There is no way to validate that a source tar ball hasn't been modified during download via MiTM
or that a compiled jar on your CDN hasn't been manipulated.

Please include checksums with all releases. (signed checksums would be even better)

Thank you

**Comment by meiao** [comment]
We do provide checksums in Maven Central.

https://repo1.maven.org/maven2/com/newrelic/agent/java/newrelic-agent/7.3.0/
