### ISSUE TITLE
Remove deprecated features from default config file

### ISSUE THREAD

**Issue by meiao** [newrelic/newrelic-java-agent#436]
## Description
The default config file uses deprecated features. That will lead new configurations to keep using those features.

## Expected Behavior
The default configuration does not use deprecated features.

## Notes
Examples of deprecated features currrently in use:
- ignore_errors -> change to ignore_classes

**Comment by kford-newrelic** [comment]
Migrated to Jira - https://issues.newrelic.com/browse/NR-24601. Targeted for next quarter's agent roadmap.
