### ISSUE TITLE
Better logging / supportability metrics surrounding Distributed Tracing.

### ISSUE THREAD

**Issue by kford-newrelic** [newrelic/newrelic-java-agent#440]
This request from support as much as from the customer. While troubleshooting this ticket, we were able to use the agent logs to determine that two services (call them Upstream and Downstream) where each correctly configured for distributed tracing, and were each adding their own distributed tracing headers to \_most\_ requests. Yet distributed tracing wasn't tracking the request across services. It appeared as if something was interfering with the distributed tracing headers mid flight. Unfortunately, we don't have a product that would allow us to look directly at the headers on an HTTP request, and the customer did not have a method for doing this either, so we've been unable to determine what's going wrong.

I brought this up in Java pairing. After discussing this issue with the Java support hero, it was recommended that I enter the following as a feature request. The Java agent doesn't log or report HTTP headers by default because they might contain sensitive data, but our own DT headers should not. So what we'd like to see is a way to configure the agent to log DT headers when they are seen on an inbound request, so that we can prove explicitly whether they are absent or malformed. Also, it would help to have this logging include transaction context, so that we can tell if one endpoint is successfully seeing headers but another is not on the same application. Finally, it would be useful to include a Supportability metric that is generated each time a DT header is seen on an inbound request. We currently have one for when a DT header is added by the agent, but not for when a DT header from an upstream agent is seen and acknowledged by the downstream agent.

Aha! Link: https://newrelic.aha.io/features/JAVA-339

**Comment by XiXiaPdx** [comment]
>Finally, it would be useful to include a Supportability metric that is generated each time a DT header is seen on an inbound request.

I'm pretty sure this already exists in the agent.  See here. 

https://github.com/newrelic/newrelic-java-agent/search?q=%22SUPPORTABILITY_ACCEPT_PAYLOAD_SUCCESS%22

**Comment by kford-newrelic** [comment]
@XiXiaPdx I think this is looking for the actual values to be captured too - not just whether it was successfully seen/processed or not. As a real world example, we had a customer where the DT headers were being added _twice_. Would have been helpful to have been able to see that as part of troubleshooting.

**Comment by meiao** [comment]
We do have other Supportability metrics around that.

https://github.com/newrelic/newrelic-java-agent/blob/1be967c1e5646e0e739b15258c86fcb0ce51a845/newrelic-agent/src/main/java/com/newrelic/agent/MetricNames.java#L396-L431

There is one specific for that error (Supportability/TraceContext/TraceParent/Ignored/Multiple), it was probably unknown for the support heroes until a deep dive in the code to find out what happens when multiple headers are found.

**Comment by kford-newrelic** [comment]
Comment added by Kevyn Ford in Aha! - [View](https://newrelic.aha.io/comments/7026703500191883669)

Determined that existing supportability metrics would allow for the needed troubleshooting for issues like the one reported by one of our customers. Discussed this with the FR submitted and there was agreement. Closing this MMF.
