### ISSUE TITLE
Support for higher-kinded types and the tagless final pattern in Scala

### ISSUE THREAD

**Issue by kford-newrelic** [newrelic/newrelic-java-agent#441]
This customer likes the work we've done in Java on the Scala API, but he'd like to see us add additional support for higher-kinded types and the tactless final pattern. These are described here: https://dzone.com/articles/beautiful-simple-testable-functional-effects-for-s

Aha! Link: https://newrelic.aha.io/features/JAVA-340

**Comment by richard-gibson** [comment]
We have now added API support for tracing transactions and segments in cats-effect 2 and 3. While documented examples use `cats.effect.IO` these apis have been created using `cats.effect.Sync`. This means that the NewRelic cats effect APIs can be used for other instances of `Sync[F]` in a tagless final pattern. However the type `F` would need to instrumentation support to ensure Transaction information is passed between threads. Currently there is instrumentation support for cats effect 2+3 IO, ZIO and scala Future

**Comment by kford-newrelic** [comment]
Comment added by Kevyn Ford in Aha! - [View](https://newrelic.aha.io/comments/7051629952941065733)

Agent release `7.5.0` will include support for these Scala types.
