### ISSUE TITLE
Support custom attributes for segments

### ISSUE THREAD

**Issue by pontello** [newrelic/newrelic-java-agent#47]
[Java Agent 5.13.0](https://docs.newrelic.com/docs/release-notes/agent-release-notes/java-release-notes/java-agent-5130) added support for setting custom attributes if you use [TracedMethod](https://newrelic.github.io/java-agent-api/javadoc/com/newrelic/api/agent/TracedMethod.html).

I wish I could do the same when using [Segments](https://newrelic.github.io/java-agent-api/javadoc/com/newrelic/api/agent/Segment.html). :smiley:

**Comment by tspring** [comment]
Thanks for the suggestion. Would adding attributes to the underlying tracer via segment.getTransaction().getTracedMethod() be sufficient for your use case?

**Comment by pontello** [comment]
Hi @tspring ,

Unfortunately no, my use case is a custom instrumentation for an async external call using native java 11 HttpClient. The method itself doesn't hang because it is an external async call.

Thanks

**Comment by tspring** [comment]
@pontello I added support for custom attributes to Spans via the Segment API, if you'd like to give it a try and let me know if it solves your issue. Thanks again! https://github.com/newrelic/newrelic-java-agent/pull/67
