### ISSUE TITLE
[Feature requests] A tool to move instrumentation logic to compile-time instead of runtime.

### ISSUE THREAD

**Issue by manhdaovan** [newrelic/newrelic-java-agent#488]
## Is your feature request related to a problem? Please describe.
env: JDK 8, Alpine Linux v.3.12.0, 2CPU, 4GB RAM server, Payara server v.5.2020.7, Newrelic java agent 7.1.1

Newrelic adds a lot of overhead to my application startup time. For example:
- Newrelic agent took \~6.5secs to startup
  ```
  2021-10-05T17:05:46,940+0900 [1 1] com.newrelic INFO: Premain startup complete in 6,339ms
  ```
- Newrelic agent also adds extra cost to app starting up time
  - Payara startup time (which load all modules of payara itself)
    - No Newrelic / Having Newrelic: ~3.5secs / ~8secs
      ```
      No NR: [2021-10-05T16:54:41.044+0900] [] [INFO] [NCLS-CORE-00017] [javax.enterprise.system.core] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1633420481044] [levelValue: 800] Payara Micro  5.2020.7 #badassmicrofish (2130) startup time : Embedded (1,218ms), startup services(2,210ms), total(3,428ms)
      Having NR: [2021-10-05T17:05:55.266+0900] [] [INFO] [NCLS-CORE-00017] [javax.enterprise.system.core] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1633421155266] [levelValue: 800] Payara Micro  5.2020.7 #badassmicrofish (2130) startup time : Embedded (3,058ms), startup services(4,891ms), total(7,949ms)
      ```
  - App deploy (which load the whole app) time
    - No Newrelic / Having Newrelic: ~8secs / ~12secs
      ```
      No NR: [2021-10-05T16:54:49.423+0900] [] [INFO] [] [javax.enterprise.system.core] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1633588963155] [levelValue: 800] r-pay-api was successfully deployed in 7,373 milliseconds.
      Having NR: [2021-10-05T17:06:08.442+0900] [] [INFO] [] [javax.enterprise.system.core] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1633589492531] [levelValue: 800] r-pay-api was successfully deployed in 12,333 milliseconds.
      ```
      
## Feature Description
AFAIK, Newrelic does some logics like `Load instrumentation modules -> detect what modules app using -> instrument the modules` to instrument source code of the app, which may cause overhead when app starting up.

I just wonder if all instrumentation source code can be generated before compiling time by a tool provided by Newrelic or not?
I think about the flow:
- Before (current flow): `App source (with all dependencies) -> Compile -> Binary file(app.jar) -> deploy (java -javaagent=newrelic.jar -jar app.jar)`
- After: `(1)app source (with all dependencies) -> (2)tool -> (3) instrumented app source code -> (4)Compile -> (5)Binary file(app.jar) -> (6)deploy (java -jar app.jar)`

There are some changes in step (2), (3), and (6).
- Step (2) is what I want. That is a tool provided by Newrelic, which `Load instrumentation modules -> detect what modules app using -> instrument the modules` and generate the instrumented source code, as mentioned [here](https://github.com/newrelic/newrelic-java-agent/wiki/Transactions#java-agent-bytecode-weaving) 
  - Eg: `./newrelic --class_transformer=xxx.yyy.zzz app.jar`, where:
    - `class_transformer` is the module that will be instrumented, described [here](https://docs.newrelic.com/docs/agents/java-agent/configuration/java-agent-configuration-config-file/#Custom_Instrumentation). Eg: `com.newrelic.instrumentation.tomcat-8.5.2`. Can be multiple.
    - `app.jar` is the compiled app (or maybe the dir of source code of the app)
- Step (3) is a source code (or compiled binary file) that already has been instrumented.
- Step(6) we don't need `-javaagent` option here anymore since the instrumentation has been added to the source code of the app already.

With this approach, I think we can reduce the app startup time, by moving the logic of instrumentation into compile-time instead of runtime.

## Describe Alternatives
A clear and concise description of any alternative solutions or features you've considered. Are there examples you could link us to?

No. I will add it here as soon as I find one out.
Currently, I'm taking a look at [aspectj](https://github.com/eclipse/org.aspectj), but nothing sure to say.

## Additional context
Add any other context here.

No

## Priority
Please help us better understand this feature request by choosing a priority from the following options: 

[Really Want]

**Comment by abbychau** [comment]
interesting. I would like to see potential compile-time works like this to optimize the boot time of newrelic.

NewRelic seems slow to me now.

**Comment by kford-newrelic** [comment]
@manhdaovan thanks for the really great idea! Unfortunately, what you're describing is a completely different product from our Java Agent - which would be quite an undertaking to build. While we can understand your concern about your application startup time with use of our agent, many of our customers have deemed that time to be reasonably acceptable if it allows them to gain access to instrumentation without having to modify their source code or introduce additional steps in their build/deploy workflow. Thanks again!
