### ISSUE TITLE
Expose W3c Trace Context 

### ISSUE THREAD

**Issue by pontello** [newrelic/newrelic-java-agent#49]
I wish I could get `traceparent` and `tracestate` related to current transaction. 

[DistributedTracePayload](https://newrelic.github.io/java-agent-api/javadoc/com/newrelic/api/agent/DistributedTracePayload.html) is proprietary and somehow deprecated as newrelic moves toward open telemetry.

Thanks

**Comment by tspring** [comment]
A W3C trace API is on our roadmap. I've linked to this issue in an internal Jira issue for when we get to that work. In the meantime, I'm going to close this, but if you have any questions or anything, feel free to reopen. Thank you for the suggestion!
