### ISSUE TITLE
Document the new way for customers to manage SSL Certificate in the Java Agent

### ISSUE THREAD

**Issue by abhihub** [newrelic/newrelic-java-agent#50]

**Comment by breedx-nr** [comment]
I think this is probably referring to the fact that we removed nrcerts when we open sourced the agent.  Can you elaborate on what you are looking for here @abhihub?  There is pretty well known [public documentation](https://docs.oracle.com/cd/E19830-01/819-4712/ablqw/index.html) about cert management in the JVM...so I'm curious what else we're looking to provide.  Thanks!
