### ISSUE TITLE
Web Service instrumentation cannot be turned off without disabling all instrumentation

### ISSUE THREAD

**Issue by meiao** [newrelic/newrelic-java-agent#501]
## Description
During development of the flag `instrumentation.web_services.enabled`, some code was left behind and should be deleted.

In InstrumentationContextManager's constructor:
```
if (agentConfig.getValue("instrumentation.web_services.enabled", false)) {
  Agent.LOG.log(Level.FINEST, "web_services instrumentation is enabled");
  matchVisitors.put(new WebServiceVisitor(), NO_OP_TRANSFORMER);
} else if (!classTransformerConfig.isDefaultInstrumentationEnabled()) {
  Agent.LOG.log(Level.FINEST, "web_services instrumentation is disabled because it is not explicitly enabled");
} else {
  matchVisitors.put(new WebServiceVisitor(), NO_OP_TRANSFORMER);
}
```
The first block is correct, enable the visitor if the feature is on.
The third block should be removed, it was erroneously left behind when the value of the if statement was "switched".
See commit 7a05386058b6caacc4831b2179594453ba3149de in the internal java_agent repository.

The current code enables the WebServiceVisitor even if the `instrumentation.web_services.enabled` flag is set to false.

**Comment by kford-newrelic** [comment]
Not prioritized for the agent roadmap.
