### ISSUE TITLE
Need instrumentation support in aws-java-sdk-sqs-1.10.44 for SqsAsyncClient

### ISSUE THREAD

**Issue by tha2015** [newrelic/newrelic-java-agent#540]
## Is your feature request related to a problem? Please describe.

I'm using spring-integration-aws 2.5.1 ,  spring-cloud-aws-messaging 2.3.2 , AWS SDK 1.12.102 to send messages to AWS SQS but I cannot find  AmazonSQSAsyncClient  traces on New Relic. From my investigation, newrelic-java-agent doesn't have instrumentation support in aws-java-sdk-sqs-1.10.44 so calls to AmazonSQSAsyncClient are not recorded (although AWS SDK 2.x is supported).

## Feature Description
Please provide instrumentation support in aws-java-sdk-sqs-1.10.44 for SqsAsyncClient, similar to instrumentation support in aws-java-sdk-sqs-2.1.0

SqsAsyncClient is supported in aws-java-sdk-sqs-2.1.0: See   https://github.com/newrelic/newrelic-java-agent/blob/f18215d145bd6992c0fe74a8c503459799e108ca/instrumentation/aws-java-sdk-sqs-2.1.0/src/main/java/software/amazon/awssdk/services/sqs/SqsAsyncClient_Instrumentation.java

SqsAsyncClient is NOT supported in aws-java-sdk-sqs-1.10.44: See  : https://github.com/newrelic/newrelic-java-agent/tree/f18215d145bd6992c0fe74a8c503459799e108ca/instrumentation/aws-java-sdk-sqs-1.10.44/src/main/java/com/amazonaws/services

## Describe Alternatives
I'm thinking about using XML to do custom instrumentation

## Additional context
Currently Spring based applications don't support AWS SDK 2.x yet. So instrumentation support  for AWS SDK 1.x is very important. Although New Relic docs mention that AmazonSQSAsyncClient is supported, but it simply doesn't work for Spring based applications.

From https://docs.newrelic.com/docs/apm/agents/java-agent/getting-started/compatibility-requirements-java-agent/, it mentions that "AmazonSQS and AmazonSQSAsync clients 1.3.22 to latest" is supported

## Priority
Please help us better understand this feature request by choosing a priority from the following options: 
[Must Have]

**Comment by kford-newrelic** [comment]
@tha2015 unfortunately, we will not be able to devote engineering focus to updating older instrumentation modules.
