### ISSUE TITLE
Not able to have correlation in traces for Scala Future

### ISSUE THREAD

**Issue by twcrone** [newrelic/newrelic-java-agent#541]
The customer has two issues with Scala instrumentation.

The response time reported in APM for the API is smaller than sum of the segments.

issue 1

The response time in the APM screen is a time-sliced metric. The duration in the Percentile screen is an attribute of the Transaction event https://docs.newrelic.com/attribute-dictionary/?event=Transaction&attributeSearch=duration.

The duration is a reasonable value. The issue is the response time (time slice metrics) has a different value from duration.

issue 2

The traces section doesn't have any information. We are seeing the following error logs in our application, so I believe the traceId is not being able to pass properly to segments.

2021-10-26T00:27:13,453+0000 [1 9640] com.newrelic ERROR: Inconsistent state! tracer != last tracer for com.newrelic.agent.TransactionActivity@0 (com.newrelic.agent.tracers.OtherRootTracer@2bb84d6f != com.newrelic.agent.tracers.OtherRootTracer@57045b99)
They followed our documentation.

https://docs.newrelic.com/jp/docs/apm/agents/java-agent/frameworks/scala-installation-java/

Here is the code snippet.

val x: Future[Int] = asyncTrace("segment name")(Future {
Thread.sleep(5000)
1
})
x.foreach(println) // prints 1 on completion of Future

Scala SME comment:

I think this deserves escalation. Inconsistent state! tracer != last tracer is a pretty serious issue, and can lead to inaccurate segment timing. It suggests that either segments or tokens aren't being expired correctly, and so the agent sees multiple tracers on the same thread at the same time. There's a long history of this type of error, but most of them are pre-GTSE, so you'll find them in JAVASUP or JAVA space. The most recent example I could find a bug report on was GTSE-71, which was fixed in v5.4.0, and this customer's on almost our latest version (7.3.0).

This could be an improper use of our Token or Segment APIs, or it could be current bug in our Scala instrumentation. We should run it past the Java dev team.

Associated GTSE ticket is https://newrelic.atlassian.net/browse/GTSE-12248

**Comment by kford-newrelic** [comment]
@richard-gibson the internal support ticket was closed; reaching out for a final confirmation but this may end up being a no-op

**Comment by kford-newrelic** [comment]
@richard-gibson no response from the customer on this issue - we're going to close this issue with no further action.
