### ISSUE TITLE
cats-effect 3 instrumentation throws fatal NPE

### ISSUE THREAD

**Issue by hughsimpson** [newrelic/newrelic-java-agent#544]
## Description
cat-effect 3 instrumentation sometimes throws 
```
java.lang.NullPointerException: null
    at cats.effect.internals.Utils.setThreadTokenAndRefCount(Utils.java:57)
    at cats.effect.IOFiber.run(IOFiber.scala)
    at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:435)
```
killing it instantly

## Expected Behavior
I would expect newrelic to not do that

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results
[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

## Steps to Reproduce
I am unable to reliably reproduce this locally at present, although it is nonetheless frequent

## Your Environment
Newrelic version 7.4.0
Cats-effect 3.2.9
java -version
openjdk version "11.0.9" 2020-10-20
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9+11)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.9+11, mixed mode)

**Comment by viswanath7** [comment]
What was the resolution of this issue? I'm also facing the exact same error due to new relic java agent. If the solution can be mentioned, it'd also help me tremendously.

**Comment by viswanath7** [comment]
Apparently, version 7.5.0 fixes it. 
https://github.com/newrelic/newrelic-java-agent/pull/530
