### ISSUE TITLE
SqlObfuscator does not obfuscate certain html documents 

### ISSUE THREAD

**Issue by XiXiaPdx** [newrelic/newrelic-java-agent#568]
It was reported and confirmed that the agent does not obfuscate certain html documents that are parameters in queries. https://newrelic.atlassian.net/browse/GTSE-12323

In that linked issue, the document-content.json is the parameter that fails to be fully obfuscated. 

On this branch, I added a test that uses the resource and is failing to obfuscate. 
https://github.com/newrelic/newrelic-java-agent/tree/fail-html-obfuscate

Expected Behavior: 

The html document is obfuscated into `?`

To Resolve:

What  exactly is slipping through the SqlObfuscator?

Does the agent spec for sql obfuscation cover this use case? If it doesn't, this is a feature request and would require cross agent spec changes and discussion.

**Comment by meiao** [comment]
This is due the way that queries incoming from PreparedStatements are treated.
There is also a related issue that a query that escapes single quotes using `\'` will have any content after that hidden.
[Internal link](https://newrelic.slack.com/archives/G96BPDE4Q/p1640819017373000) with more context.
