### ISSUE TITLE
Increase Maximum TransactionError Message Size

### ISSUE THREAD

**Issue by kford-newrelic** [newrelic/newrelic-java-agent#581]
Note : This a matching MMF for [NODE-245](https://newrelic.aha.io/features/NODE-245), so that a similar customer experience will result across APM agents.

* * *

**Problem**  
Errors Inbox groups errors by error message.

Customers are reporting poor grouping because of truncated messages. Sometimes the truncated part is interesting but more often it is a result of variable length tokens that occur before the truncation making the remaining message hard to group.

Our current character limit is 256, causing the truncating of error messages and the grouping logic to fail, making Errors Inbox full of duplicate looking errors.

**What We Can Do About This**

Let's increase our character limit so that messages are not truncated. The advice from errors inbox team is from 256 characters to 1024 characters.

Aha! Link: https://newrelic.aha.io/features/JAVA-346

**Comment by XiXiaPdx** [comment]
Draft PR that increases the max message size the agent will send - https://github.com/newrelic/newrelic-java-agent/pull/582
