### ISSUE TITLE
./gradlew clean test gets scalaTestCompile failure

### ISSUE THREAD

**Issue by twcrone** [newrelic/newrelic-java-agent#584]
## Is your feature request related to a problem? Please describe.
Zinc compiler issues snuck in again...

`./gradlew clean test` locally fails

```
Execution failed for task ':instrumentation:akka-http-2.11_2.4.5:compileTestScala'.
> scala/tools/nsc/ast/parser/Scanners$Scanner$$anonfun$fetchSingleQuote$1$1
```

## Feature Description
Should not fail the local test build with all defaults set.

## Priority
Really Want

**Comment by twcrone** [comment]
https://3.88.106.22/s/yce3rhlb2fsaq

**Comment by GDownes** [comment]
Removed Scala from default 'gradle clean test'

Zinc compiler issues prevent compiling multiple scala versions together.
Excluded Scala test tasks by default.
Included -PincludeScala project property to enable Scala test tasks.
Provided an example of new project property usage in the readme.
Removed noScala project property and usage.
