### ISSUE TITLE
Agent+Logging Initiative - Research Spike & Prototyping

### ISSUE THREAD

**Issue by kford-newrelic** [newrelic/newrelic-java-agent#595]
Cross agent initiative to add logging transmission capabilities to the Java agent, to reduce the "friction" customers experience trying to use our log ingestion capability.

**Related materials:**

- [Log Appenders (App Code Direct Forwarding to API)](https://newrelic.atlassian.net/wiki/spaces/TDP/pages/2304835656/Log+Appenders+App+Code+Direct+Forwarding+to+API)
- [Java Agent + Logging Technical Plans](https://docs.google.com/document/d/1EUMuvdQ4ZCg1nEOyRpovVNMAZdi8HXIFF2ne08jyjHg/edit)

**Deliverable**

Intention for this effort is to research proposed options and implement a working prototype that can be used to solidify implementation plans, determine sampling strategy, etc.

**Success Criteria**

- ☐

  Working prototype that can send application logs to NR1 can be demonstrated
- ☐

  Log sampling strategy options identified for decisioning
- ☐

  Other risks, constraints and assumptions identified for review

Aha! Link: https://newrelic.aha.io/features/JAVA-347

**Comment by jasonjkeller** [comment]
Work related to prototyping can be found on the [logging-initiative](https://github.com/newrelic/newrelic-java-agent/tree/logging-initiative) feature branch.

**Comment by jasonjkeller** [comment]
Prototype is done on the [logging-initiative](https://github.com/newrelic/newrelic-java-agent/tree/logging-initiative) branch.
