### ISSUE TITLE
Fix AITs on GHA

### ISSUE THREAD

**Issue by twcrone** [newrelic/newrelic-java-agent#602]
There are issues with our AITs running on GHA.  In order to fully move off of Jenkins and begin to have better visibility to ALL our builds, we need to fix these for the new CI environment.

Tracking ongoing efforts in internal Google spreadsheet.
https://docs.google.com/spreadsheets/d/1ONlTajK0ak_HOBbQemG5DOO7YFF8UTmxObVyPaXe_bs/edit#gid=0

**Comment by twcrone** [comment]
We are closing this for now and tracking via a Google spreadsheet as ongoing engineering cleanup work.

**Comment by kford-newrelic** [comment]
Closing as completed. Some remaining AITs will need to be addressed but those will have specific Jira tickets created.
