### ISSUE TITLE
Unable to figure out which version of log4j is shipped with the agent.

### ISSUE THREAD

**Issue by noorul** [newrelic/newrelic-java-agent#612]
# Unable to figure out which version of log4j is shipped with the agent.

## Description
Tools like [trivy](https://github.com/aquasecurity/trivy) are not reporting the latest vulnerability from the agent JAR.

## Expected Behavior
Uber/fat jar should have manifest information related to the dependent libraries used so that tools can figure which version of the libraries are used.

## Steps to Reproduce

Download the latest agent jar and look for manifest file/metadata that has dependent library-related information.

**Comment by jinzishuai** [comment]
wondering about the same thing.  So far, I am checking the code to ensure that such as https://github.com/newrelic/newrelic-java-agent/compare/v7.4.1...v7.4.2

**Comment by jasonjkeller** [comment]
The two patched Java agent versions use the following Log4j versions:
- Java agent 7.4.1 - ['org.apache.logging.log4j:log4j-core:2.15.0'](https://github.com/newrelic/newrelic-java-agent/blob/e92d9c9c5ff3127170f0b9b4441fc57c03401766/newrelic-agent/build.gradle#L89)
- Java agent 7.4.2 - ['org.apache.logging.log4j:log4j-core:2.16.0'](https://github.com/newrelic/newrelic-java-agent/blob/9343c34de14ac6dd172992d2344c79cc83f10b09/newrelic-agent/build.gradle#L89)

Java agent versions 4.12.0 thru 7.4.0 used a vulnerable version of Log4j:  ['org.apache.logging.log4j:log4j-core:2.11.2'](https://github.com/newrelic/newrelic-java-agent/blob/14b29f2cab31d42dfa99436dd8e32b7a3281e986/newrelic-agent/build.gradle#L89)

Java agent versions prior to 4.12.0 used Logback.

**Comment by noorul** [comment]
@jasonjkeller How can a tool like trivy determine this? Or how one can manually figure this out from the newrelic.jar?

**Comment by jasonjkeller** [comment]
@noorul Unfortunately that is not my area of expertise and I cannot provide any real insight on how security scanners do what they do. 

I assume that trivy simply looks for filenames in its scan. In this case the Java agent doesn't package the `log4j-core` jar because it relocates those files.

You can manually figure it out by looking in the `build.gradle` file that I linked in the above examples. I suspect it wouldn't be hard for a scanner tool to check in such a manner as well.

**Comment by kford-newrelic** [comment]
@noorul thanks for the suggestion on the manifest file enhancement. Unfortunately, we have limited engineering capacity and we won't be able to add this to our agent roadmap.
