### ISSUE TITLE
SQL obfuscation performance improvements

### ISSUE THREAD

**Issue by meiao** [newrelic/newrelic-java-agent#633]
## Description
Currently all queries are converted to a raw query and later on it may be obfuscated or discarded altogether.
If instead of converting the queries back and forth we store the components and lazily evaluate it can reduce CPU and memory use.

## Modifications
DefaultSqlTracer.PreparedStatementSql is moved to its own file. A field is added to its constructor indicating the `record_sql` mode.
- data can be discarded at this point to preserve memory
- de/obfuscation should be lazy, since not all SQL is stored.
- de/obfuscation should happen in an agent thread.
- once processed, the value is cached.

In DefaultSqlTracer#recordMetrics change `rawSql` from String to PreparedStatementSql and use it forward.

## Note
Even if the PreparedStatementSql thinks the query is obfuscated, it should be obfuscated because a `PreparedStatement` could  have hardcoded parameters which should be removed.

**Comment by kford-newrelic** [comment]
Was not able to include in FY23Q1's agent release. Not selected for next quarter's agent roadmap. Will consider for a future agent release.

**Comment by kford-newrelic** [comment]
Not prioritized for the agent roadmap.
