### ISSUE TITLE
Add new instrumentation for Slick 3.4.0+

### ISSUE THREAD

**Issue by meiao** [newrelic/newrelic-java-agent#643]
Current instrumentation for Slick will not apply to version 3.4.
3.4.0-M1 was released late December.

https://github.com/slick/slick

(Migrate to Jira)

**Comment by lenin122** [comment]
Also, after https://github.com/newrelic/newrelic-java-agent/issues/874 it's logical to fix this, because latest play contains slick **3.4.1** inside play-slick 5.1.0 module

**Comment by kford-newrelic** [comment]
Reviewing PR #1071
