### ISSUE TITLE
Kotlin Coroutines AITs

### ISSUE THREAD

**Issue by twcrone** [newrelic/newrelic-java-agent#646]
AITs need to be added for Kotlin Coroutines PR.

Doug provided some details on a sample app he used that might be modified for our purposes:

Here’s the link: https://newrelic.sharefile.com/d-s5f92eb3a8c2844fc965445e6d3b28165

1. The tar file is Kotlin Web App using Coroutines.
2. You’ll need to edit build.gradle and change the path in this line to your local Java agent jvmArgs = [‘-javaagent:/Users/dhilpipre/newrelic-kotlin/newrelic.jar’]
3. To start the app run:  ./gradlew appStart.    I usually just Ctl-C to stop
4. The java file is a simple client that iterates through and calls various URLs in the web app to generate traffic.

Estimation to complete:  1 week

**Comment by twcrone** [comment]
Related to https://github.com/newrelic/newrelic-java-agent/issues/647

**Comment by kford-newrelic** [comment]
Bumped from the `7.6.0` release. Will target for a future release.
