### ISSUE TITLE
Kotlin Coroutines Instrumentation Tests

### ISSUE THREAD

**Issue by twcrone** [newrelic/newrelic-java-agent#647]
The Kotlin Coroutine Instrumentation will need Instrumentation tests before being merged to core agent repo.

The original repo can be found here for more details:

https://github.com/newrelic-experimental/newrelic-java-kotlin-coroutines

Estimation:  1 week engineering effort

**Comment by kford-newrelic** [comment]
Bumped from the `7.6.0` release. Will target for a future release.

**Comment by twcrone** [comment]
After concluding this SPIKE, we have decided to not merge into core agent code and have customer continue to use as an extension.  https://github.com/newrelic/newrelic-java-agent/issues/834
