### ISSUE TITLE
Move Cats Effect's Util to the New Relic namespace

### ISSUE THREAD

**Issue by meiao** [newrelic/newrelic-java-agent#663]
## Is your feature request related to a problem? Please describe.
[cats.effect.internals.Utils](https://github.com/newrelic/newrelic-java-agent/blob/main/instrumentation/cats-effect-3/src/main/java/cats/effect/internals/Utils.java) is a class provided by New Relic. It caused a problem that looked like it was in Cats Effect and a [ticket](https://github.com/typelevel/cats-effect/issues/2527) was opened there.

To avoid confusion like that this class should be moved to the `com.nr.agent.instrumentation...` namespace.

**Comment by kford-newrelic** [comment]
Migrated to Jira (https://issues.newrelic.com/browse/NR-24535), closing. Targeting for the next quarter's roadmap.
