### ISSUE TITLE
agent-gradle-plugin breaks Gradle Configuration cache on an Android project

### ISSUE THREAD

**Issue by lwasyl** [newrelic/newrelic-java-agent#692]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )
When applying `newrelic` Gradle plugin from `com.newrelic.agent.android:agent-gradle-plugin:6.4.1`, Gradle configuration cache is broken

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen. )
Newrelic plugin doesn't break configuration cache

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results
[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )
Not applicable

## Steps to Reproduce
[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )
 - have an Android project
 - apply newrelic plugin according to [the documentation](https://docs.newrelic.com/docs/mobile-monitoring/new-relic-mobile-android/install-configure/install-android-apps-gradle-android-studio)
 - run build with configuration cache, for example `./gradlew app:assembleDebug --configuration-cache`
 - observe Gradle errors pointing out that NewRelic's plugin implementation is not compatible with configuration cache

## Your Environment
[TIP]:  # ( Include as many relevant details about your environment as possible including the running version of New Relic software, JVM vendor and version, framework versions, and any relevant configuration. )
 - com.newrelic.agent.android:agent-gradle-plugin:6.4.1

```
openjdk version "17.0.1" 2021-10-19
OpenJDK Runtime Environment Temurin-17.0.1+12 (build 17.0.1+12)
OpenJDK 64-Bit Server VM Temurin-17.0.1+12 (build 17.0.1+12, mixed mode, sharing)
```

- Android Gradle Plugin 7.0.4
- Gradle 7.3.3

## Additional context
[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )
Here's Gradle log:
```
2 problems were found storing the configuration cache.
- Plugin 'newrelic': read system property 'NewRelic.AgentArgs'
  See https://docs.gradle.org/7.3.3/userguide/configuration_cache.html#config_cache:requirements:undeclared_sys_prop_read
- Task `:app:transformClassesWithNewrelicTransformForDevDebug` of type `com.android.build.gradle.internal.pipeline.TransformTask`: cannot serialize object of type 'org.gradle.api.internal.project.DefaultProject', a subtype of 'org.gradle.api.Project', as these are not supported with the configuration cache.
  See https://docs.gradle.org/7.3.3/userguide/configuration_cache.html#config_cache:requirements:disallowed_types
```

![image](https://user-images.githubusercontent.com/3951580/151955540-1c2f8f76-e656-456a-adeb-65207eaa6274.png)

[configuration-cache-report (1).html.zip](https://github.com/newrelic/newrelic-java-agent/files/7978120/configuration-cache-report.1.html.zip)

**Comment by lwasyl** [comment]
I'm not sure if this is the right repository, I couldn't find any repository relevant to `gradle` or `android`, so I picked this one. Feel free to forward the report internally to a relevant team

**Comment by meiao** [comment]
This would be the proper repository:
https://github.com/newrelic/android-gradle-plugin

**Comment by meiao** [comment]
Redirecting to the proper repository.

**Comment by natanloterio** [comment]
Guys, which is the proper repository?

**Comment by kartik0198** [comment]
@meiao kindly pick this, it's been unpicked from last 1 year. Couldn't find any newrelic android agent repository to report this issue there.

**Comment by meiao** [comment]
@natanloterio @kartik0198
The agent-gradle-plugin is the responsibility of a different team.
Currently their repository is private, but they are in the process of open sourcing it.

I will post the link here when it is available.

**Comment by SmialyKot** [comment]
Hi @meiao, any update on this issue?

**Comment by tamtom** [comment]
same still waiting
