### ISSUE TITLE
JBoss EAP 7 doesn't load all JVM charts due to dispatcher name changing

### ISSUE THREAD

**Issue by jasonjkeller** [newrelic/newrelic-java-agent#697]
The [JVM page should show various tabs](https://docs.newrelic.com/docs/apm/agents/java-agent/features/jvms-page-java-view-app-server-metrics-jmx#dashboard-tabs) which are gated based on the web server dispatcher name. With previous versions of JBoss and JBoss EAP those dispatchers were reported as `JBoss` or `JBoss Web` which matches this [APM UI logic](https://source.datanerd.us/APM/rpm_site/blob/bd47ac73911909782ede033d76f94afc66469658/app/presenters/instances_app_server_presenter.rb#L143-L144) and causes the relevant tabs to display.

With JBoss EAP 7, up to 7.3 ([7.4+ is not supported](https://github.com/newrelic/newrelic-java-agent/issues/694)), the dispatcher now reports as `JBoss EAP` which will not match any of the logic to display the JVM tabs.

Why though do the Threads and App server transactions tabs show up for the `JBoss EAP` dispatcher based on the logic in that table?

We will need to create a PR to update the APM UI (similar to [this one](https://source.datanerd.us/APM/rpm_site/pull/28954)) to support JBoss EAP 7.

(Migrate to Jira)

**Comment by kford-newrelic** [comment]
Duplicate
