### ISSUE TITLE
Kafka Client supported ranges in compatibility doc is confusing.

### ISSUE THREAD

**Issue by tbradellis** [newrelic/newrelic-java-agent#706]
Our documentation is confusing for the kafka client versions for metrics. 
supports [Kafka Clients](https://docs.newrelic.com/docs/agents/java-agent/instrumentation/use-kafka-message-queues) 0.10.0.0 to 2.8.1 (for metric and event data) and also
[Kafka Clients](https://docs.newrelic.com/docs/agents/java-agent/instrumentation/use-kafka-message-queues) 0.11.0.0 to latest (for distributed tracing, metric, and event data). What would be the compatible version  for metrics?

https://docs.newrelic.com/docs/apm/agents/java-agent/getting-started/compatibility-requirements-java-agent/
We should update this to remove the confusing overlapping ranges. Specify the supported ranges as coded in `verifyInstrumentation` for Kafka Client modules.

(Migrate to Jira)

**Comment by kford-newrelic** [comment]
Not selected for next quarter's agent roadmap. Will consider for a future agent release.

**Comment by kford-newrelic** [comment]
@tbradellis does this issue still exist or did the doc reference get cleaned up?

**Comment by jasonjkeller** [comment]
Resolved by https://github.com/newrelic/docs-website/pull/16946
