### ISSUE TITLE
Large spikes of "Time spent in JVM" after upgrading to 7.5.0

### ISSUE THREAD

**Issue by maxwell-carbon** [newrelic/newrelic-java-agent#710]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )

We're (belatedly) upgrading our Java agent from 6.4.2 to 7.5.0. When we do so in our staging environment, the "Time spent in JVM" increases substantially, as you can see in the following graph:

![image](https://user-images.githubusercontent.com/85514919/154582245-de4adac9-02bf-4ce9-a26d-7eeed0028147.png)

The first line is our deployment upgrading from 6.4.2 to 7.5.0. The second deployment is downgrading from 7.5.0 to 7.4.3.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen. )

I'd expect the graph to be approximately the same before and after the upgrade to 7.5.0.

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results
[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

I'm not sure the guides in the template apply here -- everything is technically working, just poorly.

Additionally, as our application is running in Aptible, running arbitrary commands directly on the host isn't possible.

## Steps to Reproduce
[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )

## Your Environment
[TIP]:  # ( Include as many relevant details about your environment as possible including the running version of New Relic software, JVM vendor and version, framework versions, and any relevant configuration. )

The app in question is a sizable Scala/Play monolith that's over 100K SLOC.
* JVM: Latest Amazon Corretto 11
* Scala: 2.12.12
* Play: 2.7.5

## Additional context
[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )

We don't have any JFR-related configuration set, either in the newrelic.yml file (which was unmodified during this upgrade) nor via the `NEW_RELIC_JFR_*` variables.

**Comment by maxwell-carbon** [comment]
7.6.0 still has this problem.

**Comment by kford-newrelic** [comment]
@maxwell-carbon thanks for bringing this to our attention - we're sorry to hear that you're experiencing a problem upgrading to a new agent version.

At the moment, have you decided to stay on `7.4.3`?

**Comment by maxwell-carbon** [comment]
@kford-newrelic yes, we're sticking with 7.4.3 for now, which has been working well enough for us.

**Comment by kford-newrelic** [comment]
@maxwell-carbon Unfortunately, this isn't specific enough for us to be able to investigate further. If its possible for you in the future to create a sample app that reproduces the problem, that would might allow us to focus in on a problem area - say a specific instrumentation module. In our performance tests, we didn't notice anything significant between versions but those tests may not be triggering the behavior you're seeing.
