### ISSUE TITLE
Support for Tomcat 10

### ISSUE THREAD

**Issue by pvarga88** [newrelic/newrelic-java-agent#712]
## Is your feature request related to a problem? Please describe.
No

## Feature Description
Tomcat 10 is required by apps built for JakartaEE (which replaces JavaEE). It is not possible to run such apps on older versions of Tomcat.
Tomcat 10 has been available for well over one year already.

## Describe Alternatives
There are none

## Additional context
N/A

## Priority
Must Have for our team

**Comment by kford-newrelic** [comment]
Deferring to the next quarter (Jul-Sep)

**Comment by kford-newrelic** [comment]
Migrated to Jira as https://issues.newrelic.com/browse/NR-13494. Targeted for next quarter's roadmap.
