### ISSUE TITLE
org.apache.kafka:kafka-clients:3.0.0 is not instrumented

### ISSUE THREAD

**Issue by averkhovtsev-xm** [newrelic/newrelic-java-agent#713]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )
KafkaProducer and KafkaConsumer metrics are not sent to Newrelic.

Following are the logs when log_level: finest and audit_mode: true 

2022-02-17T17:11:29,700+0000 [44652 1] com.newrelic FINER: Storing TracedWeaveInstrumentation: com.newrelic.instrumentation.kafka-clients-metrics-0.10.0.0 - org/apache/kafka/clients/producer/KafkaProducer.doSend((Lorg/apache/kafka/clients/producer/ProducerRecord;Lorg/apache/kafka/clients/producer/Callback;)Ljava/util/concurrent/Future;)
2022-02-17T17:11:29,715+0000 [44652 1] com.newrelic FINEST: Skipping instrumentation module com.newrelic.instrumentation.kafka-clients-metrics-0.10.0.0. The most likely cause is that com.newrelic.instrumentation.kafka-clients-metrics-0.10.0.0 shouldn't apply to this application.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen. )
Metrics should be sent to Newrelic.

## Your Environment
[TIP]:  # ( Include as many relevant details about your environment as possible including the running version of New Relic software, JVM vendor and version, framework versions, and any relevant configuration. )
com.newrelic.agent.java:newrelic-agent:7.5.0
adoptopenjdk/openjdk11:alpine-jre

## Additional context
[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )

**Comment by meiao** [comment]
We have found gaps in our instrumentation for kafka 3+.
See #711.

**Comment by meiao** [comment]
For Kafka 3, you should look for the instrumentation module `com.newrelic.instrumentation.kafka-clients-metrics-2.0.0`. It is expected that the 0.10.0.0 module will not load for kafka versions higher than 2.0.0.

**Comment by averkhovtsev-xm** [comment]
the metrics related instrumentation is implemented in kafka-clients-metrics-0.10.0.0 module, so if it is not applied then no metrics are published to Newrelic. The module 2.0.0 itself seems to have small value.
Btw, the 0.10.0.0 module is loaded for kafka versions higher than 2.0.0, i tested it for  kafka-clinets-2.6.0 and 2.8.1.

**Comment by meiao** [comment]
Interesting, both modules (0.10.0.0 and 2.0.0) are loaded for versions 2.0.0 thru 3.0.0. We usually avoid that.
But for 3.0.0 it is expected that 0.10.0.0 is not loaded.
