### ISSUE TITLE
U/F/I Tests: Implement ApplicationLoggingConfig tests

### ISSUE THREAD

**Issue by jasonjkeller** [newrelic/newrelic-java-agent#733]
Write tests for these four `ApplicationLoggingConfig*` classes:

- https://github.com/newrelic/newrelic-java-agent/blob/6f45eec3c20287cda7a1ea418d4fb4c44f2bc6f7/newrelic-agent/src/test/java/com/newrelic/agent/config/ApplicationLoggingConfigImplTest.java#L5-L7
- https://github.com/newrelic/newrelic-java-agent/blob/6f45eec3c20287cda7a1ea418d4fb4c44f2bc6f7/newrelic-agent/src/test/java/com/newrelic/agent/config/ApplicationLoggingForwardingConfigTest.java#L5-L7
- https://github.com/newrelic/newrelic-java-agent/blob/6f45eec3c20287cda7a1ea418d4fb4c44f2bc6f7/newrelic-agent/src/test/java/com/newrelic/agent/config/ApplicationLoggingLocalDecoratingConfigTest.java#L5-L7
- https://github.com/newrelic/newrelic-java-agent/blob/6f45eec3c20287cda7a1ea418d4fb4c44f2bc6f7/newrelic-agent/src/test/java/com/newrelic/agent/config/ApplicationLoggingMetricsConfigTest.java#L5-L7

These tests should follow a similar pattern to `InfiniteTracingConfigImplTest`, `InfiniteTracingSpanEventsConfigTest`, and `InfiniteTracingTraceObserverConfigTest`.

**Comment by tbradellis** [comment]
Decided to Open a separate PR for each test in the interest of keep the commit/PR small
https://github.com/newrelic/newrelic-java-agent/pull/774

**Comment by tbradellis** [comment]
ApplicationLoggingForwardingConfigTest:
https://github.com/newrelic/newrelic-java-agent/pull/776

**Comment by tbradellis** [comment]
Local decorating test:
https://github.com/newrelic/newrelic-java-agent/pull/777

**Comment by tbradellis** [comment]
logging metrics tests
https://github.com/newrelic/newrelic-java-agent/pull/778
