### ISSUE TITLE
Stretch Goal: Implement instrumentation for Log4j1

### ISSUE THREAD

**Issue by jasonjkeller** [newrelic/newrelic-java-agent#744]
This is partially done in that there is already an instrumentation module that is generating log level metrics:
https://github.com/newrelic/newrelic-java-agent/tree/logging-initiative/instrumentation/apache-log4j-1

This instrumentation still needs the following:
- [ ] Create LogEvents
- [ ] Create a supportability metric indicating that the module loaded: `Supportability/Logging/enabled/Java/Log4j1`
- [ ] Append agent metadata to log messages
- [ ] Instrumentation tests

**Comment by kford-newrelic** [comment]
Considering dropping support for Log4j 1

**Comment by kford-newrelic** [comment]
Not prioritized for the agent roadmap. Enhanced logs-in-context support will not be extended to Log4j 1.
