### ISSUE TITLE
Stretch Goal: Implement instrumentation for Java Util Logging (JUL)

### ISSUE THREAD

**Issue by jasonjkeller** [newrelic/newrelic-java-agent#745]
This is partially done in that there is already an instrumentation module that is generating log level metrics:
https://github.com/newrelic/newrelic-java-agent/tree/logging-initiative/instrumentation/java.logging-jdk8

This instrumentation still needs the following:
- [ ] Create LogEvents
- [ ] Create a supportability metric indicating that the module loaded: `Supportability/Logging/enabled/Java/JUL`
- [ ] Append agent metadata to log messages
- [ ] Instrumentation tests

**Comment by kford-newrelic** [comment]
Implemented in #1049
