### ISSUE TITLE
Stretch Goal: Implement instrumentation for Logback 1.1

### ISSUE THREAD

**Issue by jasonjkeller** [newrelic/newrelic-java-agent#746]
Write instrumentation for Logback 1.1.

This instrumentation still needs the following:
- [x] Create log level metrics
- [x] Create LogEvents
- [x] Create a supportability metric indicating that the module loaded: `Supportability/Logging/enabled/Java/LogbackClassic1.1`
- [x] Append agent metadata to log messages
- [x] Instrumentation tests

**Comment by kford-newrelic** [comment]
Added in the `7.10.0` agent release.
