### ISSUE TITLE
Stretch Goal: Implement instrumentation for Tomcat JULI logger

### ISSUE THREAD

**Issue by jasonjkeller** [newrelic/newrelic-java-agent#747]
Write instrumentation for Tomcat JULI logger. This is the [default Tomcat logger](https://tomcat.apache.org/tomcat-8.5-doc/logging.html).

This instrumentation still needs the following:
- [ ] Create log level metrics
- [ ] Create LogEvents
- [ ] Create a supportability metric indicating that the module loaded: `Supportability/Logging/enabled/Java/TomcatJULI`
- [ ] Append agent metadata to log messages
- [ ] Instrumentation tests

**Comment by kford-newrelic** [comment]
Not selected for the agent roadmap.
