### ISSUE TITLE
Unable to fetch kafka and aerospike metrics from New Relic

### ISSUE THREAD

**Issue by VedanshToTheNew** [newrelic/newrelic-java-agent#756]
we are unable to see Kafka and aerospike metrics from our app, MySQL Database is available but metrics are not available.
furthermore, metrics are not available for int1-app-web-delivery tasks also.
![image (2) (1) (1)](https://user-images.githubusercontent.com/78462883/156342325-faabb8f8-bf0a-4626-9b2f-a94259f8ee0a.png)
![image (1) (1) (1)](https://user-images.githubusercontent.com/78462883/156342332-ef266eec-76ad-4ed3-b443-b6abb5cac537.png)

Currently, we are not using newrelic.yml. Instead, we are using environment variables defined below:
NEW_RELIC_AGENT_ENABLED=true
NEW_RELIC_DISTRIBUTED_TRACING_ENABLED=true
Versions used are defined below:
java: JRE vendor Oracle Corporation version 1.8.0_312
New Relic: New Relic Agent v7.5.0
linux: OS Linux version 4.14.262-200.489.amzn2.x86_64 arch amd64
![image (3)](https://user-images.githubusercontent.com/78462883/156337266-8bdb78c1-eba8-4b92-bdcb-c6d9434a41cb.png)

Please refer attached Snapshots
@jasonjkeller

**Comment by tarunsaxenattn** [comment]
@jasonjkeller Appreciate if you can take a look here. Thanks.

**Comment by meiao** [comment]
There is not enough information to work on this as a bug.
I've noticed a [conversation in our support site](https://discuss.newrelic.com/t/java-unable-to-see-kafka-and-aerospike-metrics/178056). Let's continue the conversation there.
We will open a bug with the proper information if we do find out it is a bug.
