### ISSUE TITLE
Memory issues when app started with agent and incorrect license key

### ISSUE THREAD

**Issue by twcrone** [newrelic/newrelic-java-agent#772]
The agent should shutdown gracefully and not report data if it is given an invalid license key.  In some cases this does not appear to be the case and the agent causes issues to running applications with incorrect key or if key is invalidated whilst the app is running.

https://newrelic.atlassian.net/browse/GTSE-13664

https://newrelic.atlassian.net/browse/GTSE-13781

**Comment by kford-newrelic** [comment]
Not prioritized for the agent roadmap.
