### ISSUE TITLE
Throughput for APM metrics is reported as 2x of actual value

### ISSUE THREAD

**Issue by twcrone** [newrelic/newrelic-java-agent#780]
Its been noticed that summary and golden metrics for APM application entities are reporting 2x the actual throughput of the service. we should investigate whether this is an issue on our end or not. 

Throughput is 130k rpm for entity-search-service, but in reality, it’s ~60k. 

https://newrelic.atlassian.net/browse/ESA-1034

**Comment by albertoolivan** [comment]
Hi @twcrone  any update on this?

**Comment by albertoolivan** [comment]
Hi @twcrone  any chance to take a look ?

**Comment by kford-newrelic** [comment]
@albertoolivan apologies but we do not have this prioritized for our roadmap yet. It's not clear when it can be prioritized yet but we continually review issues to determine which ones we can take up on our roadmap.

**Comment by kford-newrelic** [comment]
Migrated to Jira (https://issues.newrelic.com/browse/NR-24552). Targeted for next quarter's agent roadmap.
