### ISSUE TITLE
#39 regression; env vars with sys prop syntax are prioritized

### ISSUE THREAD

**Issue by jeffalder** [newrelic/newrelic-java-agent#781]
## Description
I have an application where the _environment variable_ `newrelic.config.labels` is set _and_ `NEW_RELIC_LABELS` is also set. Despite the message that the env var `newrelic.config.labels` is not supported, it appears from the data to actually take _precedence_ over `NEW_RELIC_LABELS`. 

Yes, I'm 100% sure the environment variable with dots and lower-case is used despite it looking like a system property.
Yes, I know. 
No, it's not in my control.

## Expected Behavior
`NEW_RELIC_LABELS` takes precedence; `newrelic.config.labels` is ignored.

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results
I'm using agent 7.4.3; I don't suspect you need more than that?

## Steps to Reproduce
See [test.zip](https://github.com/newrelic/newrelic-java-agent/files/8233163/test.zip)
- download the agent, drop it in the current directory
- run `./run.sh` - it will compile and run the app
- Look at the output

Environment:
```
    env.put("newrelic.config.labels", "dotted-labela:dotted-valuea");
    env.put("NEW_RELIC_LABELS", "caps-labelb:caps-valueb");
```

When I look at the connect payload through audit mode, I see this:
```
% jq '.[0].settings.labels' payload.json
"caps-labelb:caps-valueb"
% jq '.[0].labels' payload.json
[
  {
    "label_type": "dotted-labela",
    "label_value": "dotted-valuea"
  }
]
```

## Your Environment
Temurin Java 17 but repros on Azul Zulu 11 as well
Agent 7.4.3
Mac M1, Monterey 12.2.1

(Migrate to Jira)

**Comment by kford-newrelic** [comment]
Not selected for next quarter's agent roadmap. Will consider for a future agent release.
