### ISSUE TITLE
Support for httpclient 5.0

### ISSUE THREAD

**Issue by anuragagarwal561994** [newrelic/newrelic-java-agent#800]
Currently there is support for Apache HttpClient 4.0, it will be better if a support for apache http client 5.0 is also available. It has already been over 1 year since the 5.x version has been release. It would be a great addition to the instrumentation list.

**Comment by kford-newrelic** [comment]
@anuragagarwal561994 thanks for submitting this - we'll discuss this in a future prioritization meeting

**Comment by kford-newrelic** [comment]
Migrated to Jira (https://issues.newrelic.com/browse/NR-24556). Targeted for next quarter's agent roadmap.

**Comment by mattnelson** [comment]
> Migrated to Jira ([issues.newrelic.com/browse/NR-24556](https://issues.newrelic.com/browse/NR-24556)). Targeted for next quarter's agent roadmap.

Is that link intended to be public? 

This repository is listed as [Community Plus](https://opensource.newrelic.com/oss-category/#community-plus), of which, one of the requirements is `Issues and PR’s managed in GitHub`

**Comment by darkleaf** [comment]
Any updates?

**Comment by kford-newrelic** [comment]
@darkleaf we have it in our backlog/on our roadmap but unfortunately, it won't be targeted as part of our Oct-Dec quarter's work

**Comment by darkleaf** [comment]
@kford-newrelic any updates?

**Comment by darkleaf** [comment]
Up

**Comment by kford-newrelic** [comment]
We still have this on our backlog...but it's been getting bumped due to other priorities. Will trigger a discussion on this one...

**Comment by kford-newrelic** [comment]
Targeted for the Apr-Jun quarter

**Comment by darkleaf** [comment]
Why this issue was closed?

**Comment by meiao** [comment]
It was closed by mistake in our internal issue tracker. And our workato-integration hasn't mirrored the reopening yet.
