### ISSUE TITLE
Dynamo instrumentation does not work when using DAX

### ISSUE THREAD

**Issue by thomasdac** [newrelic/newrelic-java-agent#809]
## Description
I have an application that uses DynamoDB from AWS together with DAX (DynamoDB Accelerator). Instrumentation works smoothly when using Dynamo directly, separating network, Dynamo and Java times. However, when I use it through the DAX client, everything is displayed as Java time.

## Expected Behavior
Show network, Dynamo and Java times separately, just like in pure Dynamo instrumentation.

## Your Environment
- JRE 17
- Spring Boot 2.6.4
- Spring Cloud 2021.0.1
- NewRelic Java Agent 7.5.0
- AWS Java SDKv2 2.17.151
- [Amazon DAX Client 2.0.1](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DAX.client.run-application-java.html)

**Comment by kford-newrelic** [comment]
@thomasdac thanks for letting us know about the limitation on our instrumentation!

We're not sure at the moment whether we'll have the bandwidth to work on this soon but PRs are always welcome if you'd like to submit something!

**Comment by kford-newrelic** [comment]
@thomasdac We apologize but unfortunately, we do not have the engineering bandwidth to enhance our current instrumentation to support the DAX client. Not selected for the product roadmap.

**Comment by kanderson250** [comment]
This was re-opened and completed under #2800.
