### ISSUE TITLE
AWS IMDS V2 Support

### ISSUE THREAD

**Issue by ericlarssen-wf** [newrelic/newrelic-java-agent#81]
### Is your feature request related to a problem? Please describe.
AWS has created a newer protocol to communicate with the Metadata server ([context](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html)), that enables clients to use a session based request which is more secure. With the idea of deprecating the usage of the V1 protocol, we rely on the agent to no longer use that authentication method.

### Feature Description
Adopt the session based authentication with the AWS metadata server.

### Describe Alternatives
None that I can think of.

### Additional context
https://krebsonsecurity.com/2019/08/what-we-can-learn-from-the-capital-one-hack/

### Priority
Must Have

**Comment by tspring** [comment]
Hi @ericlarssen-wf , thanks for the feedback. We already support AWS IMDS v2 here: https://github.com/newrelic/newrelic-java-agent/blob/a9e42780feadcd3c0b3f555d2bef4b0b13d95598/newrelic-agent/src/main/java/com/newrelic/agent/utilization/AWS.java#L96 
Perhaps I'm misunderstanding?

**Comment by ericlarssen-wf** [comment]
Oh, didn't see that! Thanks!

**Comment by jrobison-sb** [comment]
@tspring Can you tell me the minimum version which supports IMDSv2? I don't see any tags earlier than 6.0 here. Would any of the 5.* releases support IMDSv2?
