### ISSUE TITLE
Add Marker data as attributes on LogEvents

### ISSUE THREAD

**Issue by jasonjkeller** [newrelic/newrelic-java-agent#837]
From customer:

> We use the Logstash encoder (https://github.com/logfellow/logstash-logback-encoder) to log to JSON, and Slf4j Marker ([Marker (SLF4J 2.0.0-alpha7 API)](https://www.slf4j.org/api/org/slf4j/Marker.html)) to add extra attributes to the JSON. I was kind of expecting it to show up in the New Relic Logs panel, but only the message is transmitted.

We should capture and add Marker data as attributes on LogEvents.

**Comment by jasonjkeller** [comment]
Also see: https://discuss.newrelic.com/t/java-slf4j-log-markers-in-new-relic-logs/184703

**Comment by dpinn** [comment]
re: wontfix label: OK, so no marker data on log events then?

**Comment by kford-newrelic** [comment]
@dpinn We apologize but unfortunately not. We don't have the engineering bandwidth to pursue this enhancement, so we're unable to add it to our product roadmap.

**Comment by anderssv** [comment]
Not sure what this means, but is it supported now? :)

![image](https://github.com/newrelic/newrelic-java-agent/assets/30963/286e6d27-5642-4091-8a52-35f6cf0d3df0)

**Comment by danurahadi** [comment]
@kford-newrelic hello.. this issue is still not on your product roadmap now? thanks
