### ISSUE TITLE
Support gRPC > 1.29.0

### ISSUE THREAD

**Issue by jef** [newrelic/newrelic-java-agent#84]
## Is your feature request related to a problem? Please describe.

It would be nice to use the latest gRPC libraries. 1.29.0 was release in May and there are quite a few benefits to 1.30.0+. One of many changes includes [grpc-kotlin](https://github.com/grpc/grpc-kotlin).

- https://github.com/grpc/grpc/releases
- https://github.com/grpc/grpc-java/releases

## Feature Description

Update the agent to use the latest library. I don't believe there are any breaking changes, it should be fine to upgrade. 

## Priority

Really want

**Comment by tspring** [comment]
Hi @jef . I updated our Grpc instrumentation here, if you'd like to give it try and let us know if it works well for you: https://github.com/newrelic/newrelic-java-agent/pull/92

**Comment by jef** [comment]
I'm going to close this out, but I haven't tested. I'll reopen if anything arises.

Thanks for this!
