### ISSUE TITLE
Add instrumentation for Http4s 0.23

### ISSUE THREAD

**Issue by Matzz** [newrelic/newrelic-java-agent#843]
According to [Compatibility and requirements for the Java agent | New Relic Documentation 1](https://docs.newrelic.com/docs/apm/agents/java-agent/getting-started/compatibility-requirements-java-agent/) New Relic java agent support only Http4s 0.21 - 0.22.0-M8
However the latest stable release is of http4s server 0.23.11. I tested that and indeed didn’t get metrics from the latest version.

Related issue for http4s client - https://github.com/newrelic/newrelic-java-agent/issues/429

**Comment by Matzz** [comment]
@jasonjkeller / @tbradellis 
Do you think that new instrumentation module is needed or just build.gradle modification as in https://github.com/newrelic/newrelic-java-agent/issues/429 ?

**Comment by meiao** [comment]
@Matzz #429 is still open. We haven't added instrumentation for this version of the library yet.
The PR referenced in that ticket is just for our internal testing framework to stop notifying us that the library is not compatible with newer versions of the library. Please refer to #429 for updates on the status of support for Http4s 0.23.
