### ISSUE TITLE
Ignore transaction/metrics by URL / Path?

### ISSUE THREAD

**Issue by mcouillard** [newrelic/newrelic-java-agent#845]
As supported by the Ruby agent, can this agent be enhanced to skip transaction or even metric collection by URL path regex?
https://docs.newrelic.com/docs/apm/agents/ruby-agent/api-guides/ignoring-specific-transactions/

We're using Spring Framework MVC to power Java APIs.

ElasticAPM offers this via `elastic_apm.transaction_ignore_urls`
https://www.elastic.co/guide/en/apm/agent/php/master/configuration-reference.html#config-transaction-ignore-urls

Having this allows us to skip certain ping / health checks that happen frequently for internal purposes, like load balancing.

**Comment by kford-newrelic** [comment]
@mcouillard thanks for the suggested enhancement, we appreciate it!

We'll consider this as we do future roadmap planning for our agent, thanks!

**Comment by kford-newrelic** [comment]
@mcouillard Thanks again for this good suggestion - unfortunately, we don't have the engineering bandwidth to implement this. Not added to the product roadmap.
