### ISSUE TITLE
Agent 7.8.0 Release

### ISSUE THREAD

**Issue by kbford56** [newrelic/newrelic-java-agent#871]
Prep, create and publish agent `7.8.0` release

- [x] Review, finalize and merge PRs
- [x] Build snapshot release for testing
- [x] Run unit/functional/instrumentation tests
- [x] Run agent integration tests
- [x] Run instrumentation verifier tests
- [x] Agent bug hunt
- [x] Update release notes
- [x] Stage and publish release
- [x] Post release notifications and tasks

**Comment by twcrone** [comment]
Unless I miss my mark, there are no performance tests to run for this release.
