### ISSUE TITLE
Investigate Play 2.7 instrumentation module not applying to version 2.8.16

### ISSUE THREAD

**Issue by meiao** [newrelic/newrelic-java-agent#874]
## Description
The play 2.7 instrumentation module stopped being applied to Play on version 2.8.16. 

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag]
Weave violations reported on the test:
- WeaveViolation{type=METHOD_NEW_CALL_ORIGINAL_UNSUPPORTED, clazz=play/core/server/Server$, method=getHandlerFor(Lplay/api/mvc/RequestHeader;Lscala/util/Try;)Lscala/Tuple2;}
- WeaveViolation{type=METHOD_NEW_NON_PRIVATE_UNSUPPORTED, clazz=play/core/server/Server$, method=getHandlerFor(Lplay/api/mvc/RequestHeader;Lscala/util/Try;)Lscala/Tuple2;}

(migrate to Jira)

**Comment by meiao** [comment]
From the weave violations, it is very likely that the method was renamed, or the signature was altered.

**Comment by tbradellis** [comment]
Indeed, the signature has changed:
https://github.com/playframework/playframework/commit/a5d83283669dd69dbdba1407d231113aee3a02e5
