### ISSUE TITLE
Share code for the legacy Play 1.x framework instrumentation

### ISSUE THREAD

**Issue by mridang** [newrelic/newrelic-java-agent#91]
## Is your feature request related to a problem? Please describe.
Earlier versions of the agent (4.x) had instrumentation for Play Framework 1.x. This was omitted from the 5.x release preventing us from upgrading. 

## Feature Description
A partial patch file or a Github Gist with the relevant bits shared. We can then fork this project and apply the necessary changes.

## Describe Alternatives
None.

## Additional context
This is the communication received from New Relic.

> Unfortunately, the Play 1.x instrumentation implementation does not have a mechanism to load as an extension (Pointcut vs Weaver API). As you've already deduced, it would difficult to match the old instrumentation without injecting bytecode.
>
> Despite our limited support on the following, you may extract other missing instrumentation from previous Java agent builds by extracting (unzip) the module from the newrelic.jar archive to your installed /newrelic/extensions directory (instrumentation modules are found in the /instrumentation directory).

## Priority
Blocker.

**Comment by tspring** [comment]
Hi @mridang , Unfortunately the Play-1 instrumentation used an older style pointcut instrumentation so we can't distribute it as a legacy extension. That said, here's a patch file for the instrumentation itself, though it'll likely require a few changes to AbstractTracer and maybe a few other classes at this point. Let me know if you have any questions.
[0001-play-1-revert.patch.zip](https://github.com/newrelic/newrelic-java-agent/files/5411170/0001-play-1-revert.patch.zip)

**Comment by mridang** [comment]
@jluostar

**Comment by tspring** [comment]
@mridang I'm going to go ahead and close this. Please feel free to reopen if you have any questions
